// ============================================================
// PYREVIT PRACTICE — LESSONS pyp-9 through pyp-16 (INTERMEDIATE)
// Section: Model Health / Audits & Worksets / Checks & COBie / Links & Ribbon
// File: lib/pyrevitPracticeLessonsContent/pyrevitPracticeLessons_9_16.js
// Companion project used throughout: "DPC2025" (Dharren Park Capstone 2025)
// ============================================================

export const lessons_9_16 = [

  // ============================================================
  // LESSON PYP-9 — Build a Model Health Dashboard
  // ============================================================
  {
    id: 'pyp-9', num: '09',
    title: 'Build a Model Health Dashboard',
    topic: 'Model Health', cat: 'intermediate', readTime: '10 min', free: false,
    desc: 'Run several quick health checks against DPC2025 — warning count, unplaced rooms, elements missing key parameters — and print one consolidated dashboard-style report using output.print_md() and output.print_table().',
    intro: `Most model health checks in the wild are three or four separate scripts that a BIM Manager runs one after another, scrolling through a wall of raw text each time. This lesson builds a single pushbutton for DPC2025 that runs several quick checks in one pass — document warnings, unplaced rooms, and elements missing key parameters — and prints the results as one clean, consolidated dashboard in the pyRevit output window. The focus here is as much on formatted, readable reporting with print_md() and print_table() as it is on the checks themselves, because a health check nobody can read at a glance rarely gets used twice.`,
    sections: [
      {
        id: 's1', heading: 'Designing the Dashboard as One Button, Several Checks', level: 'h2',
        content: `A model health dashboard is not one clever query — it is several small, independent checks, each producing its own small result set, all assembled and printed together under one script. Structuring the script this way keeps each check simple and easy to extend later.`,
        items: [
          'Each check should be its own small function: check_warnings(doc), check_unplaced_rooms(doc), check_missing_parameters(doc) — independent, testable, and easy to add to later',
          'The main script body calls each check function in turn and hands its result to the reporting section, rather than interleaving collection and printing logic inside every check',
          'Keeping checks independent means a future health check (e.g., duplicate marks, or the Level/Grid check from a later lesson in this course) can be dropped in as one more function call without touching the others',
        ],
        formula: { label: 'Dashboard Structure', text: 'main script -> call check_warnings(), check_unplaced_rooms(), check_missing_parameters() -> pass all three results to one reporting section' },
      },
      {
        id: 's2', heading: 'Check 1 — Counting Document Warnings', level: 'h2',
        content: `Every open Revit document exposes its own warnings through the API, and counting them is the simplest of the three checks in this dashboard.`,
        code: {
          label: 'Reading Document Warnings',
          lines: [
            'warnings = doc.GetWarnings()',
            'warning_count = len(warnings)',
            '',
            '# Optional: group by description for a more useful summary',
            'from collections import Counter',
            'descriptions = [w.GetDescriptionText() for w in warnings]',
            'by_type = Counter(descriptions)',
          ],
        },
        items: [
          'doc.GetWarnings() returns every FailureMessage currently logged against the document — no transaction or Selection is needed, since this only reads existing data',
          'A raw count is a useful headline number, but grouping by GetDescriptionText() with a Counter shows which warning types dominate (e.g., "Room Tags is outside its Room" appearing 40 times) — far more actionable than a single total',
          'This check runs in a fraction of a second even on a large model like DPC2025, since it reads warnings Revit has already computed rather than re-auditing the model live',
        ],
      },
      {
        id: 's3', heading: 'Check 2 — Finding Unplaced Rooms', level: 'h2',
        content: `Unplaced rooms are rooms that exist as a schedule row but have never actually been placed in the model — a common and easily overlooked source of incomplete area data.`,
        code: {
          label: 'Detecting Unplaced Rooms',
          lines: [
            'rooms = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(DB.BuiltInCategory.OST_Rooms)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
            '',
            'unplaced = [r for r in rooms if r.Area == 0 or r.Location is None]',
          ],
        },
        items: [
          'An unplaced Room element still exists in the model and still appears in the collector — it simply has no Location (no boundary was ever resolved) and an Area of 0',
          'Checking both r.Location is None and r.Area == 0 catches both the classic "never placed" case and rooms that briefly lost their boundary due to a deleted wall',
          'For the dashboard, only the count and a short identifying list (Room Number/Name where available, or the Element Id when the room has no Name yet) are needed — the full detail can be left to a dedicated audit tool',
        ],
      },
      {
        id: 's4', heading: 'Check 3 — Elements Missing Key Parameters', level: 'h2',
        content: `The third check looks for a short, deliberately small list of parameters that DPC2025's BIM Execution Plan considers mandatory on key categories — this is a lightweight preview of the fuller Parameter Audit Tool built later in this course.`,
        code: {
          label: 'Missing Parameter Scan',
          lines: [
            'required = ["Mark", "Comments"]',
            'category = DB.BuiltInCategory.OST_Doors',
            '',
            'elements = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(category)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
            '',
            'missing = []',
            'for el in elements:',
            '    for name in required:',
            '        p = el.LookupParameter(name)',
            '        if p is None or not p.HasValue:',
            '            missing.append((el.Id, name))',
          ],
        },
        items: [
          'For a dashboard, keep the required-parameter list short and category scope narrow (e.g., Doors only) — a full multi-category audit belongs to the dedicated Parameter Audit Tool later in this course, not a quick health-check button',
          'p.HasValue distinguishes a genuinely blank parameter from one holding an empty string or zero — a parameter can exist and still not have a meaningful value',
          'The (element id, parameter name) tuple gives the reporting step everything it needs to build a clickable, specific line item',
        ],
      },
      {
        id: 's5', heading: 'Printing a Markdown Report with output.print_md()', level: 'h2',
        content: `pyRevit's output window renders a subset of Markdown, which turns a script's results from a raw text dump into a genuinely readable report with headings, bold text, and bullet lists.`,
        code: {
          label: 'Markdown Dashboard Header',
          lines: [
            'output = script.get_output()',
            '',
            'output.print_md("# DPC2025 Model Health Dashboard")',
            'output.print_md("**Warnings:** {}".format(warning_count))',
            'output.print_md("**Unplaced Rooms:** {}".format(len(unplaced)))',
            'output.print_md("**Elements Missing Required Data:** {}".format(len(missing)))',
            'output.print_md("---")',
          ],
        },
        items: [
          '# renders as a heading, ** ** renders as bold, and --- renders as a horizontal rule — the same lightweight Markdown syntax used in READMEs and chat messages',
          'Printing the three headline numbers as a bold summary block at the top gives a BIM Manager the at-a-glance answer before they read a single row of detail',
          'print_md() is plain-text friendly too — a string with no Markdown syntax in it prints exactly as written, so it is safe to mix with ordinary print() calls',
        ],
        formula: { label: 'Why Markdown Matters Here', text: 'output.print_md() turns a flat wall of text into a scannable report — headings and bold summary numbers let a reader judge model health in the first two seconds' },
      },
      {
        id: 's6', heading: 'Printing Detail Tables with output.print_table()', level: 'h2',
        content: `Once the headline numbers are printed, the detail behind each check is far more readable as an actual table than as one print() line per row.`,
        code: {
          label: 'Rendering a Detail Table',
          lines: [
            'output.print_md("## Unplaced Rooms")',
            'rows = [[str(r.Id), r.Number or "-", r.Name or "-"] for r in unplaced]',
            'output.print_table(',
            '    table_data=rows,',
            '    columns=["Element Id", "Number", "Name"],',
            '    title="Unplaced Rooms"',
            ')',
          ],
        },
        items: [
          'output.print_table() takes a list of row lists (table_data) and a matching list of column headers (columns), rendering an actual HTML table in the output window rather than plain text',
          'Keep each check\'s table under its own print_md() sub-heading (## Unplaced Rooms, ## Missing Required Data) so the whole dashboard stays organized as one scrollable report with a clear structure',
          'For very large result sets, consider printing only the first 50 rows in the table with a trailing note ("+ 214 more — see full export"), since a multi-thousand-row HTML table can make the output window sluggish',
        ],
        formula: { label: 'Report Structure', text: 'print_md() summary block at the top -> one print_md() sub-heading + print_table() pair per check -> a single scrollable, consistently formatted dashboard' },
      },
      {
        id: 's7', heading: 'Assembling and Running the Full Dashboard', level: 'h2',
        content: `With all three checks and the two output helpers in place, the script.py for this pushbutton reads top to bottom as a simple, linear sequence — collect, collect, collect, then report.`,
        items: [
          'Run each check function first and store its result in a variable before printing anything — this keeps the collection logic and the reporting logic cleanly separated, and means a check that raises an exception fails before any partial report is printed',
          'Wrap the whole script body in a single try/except at the top level so an unexpected error in one check (e.g., a category that does not exist in a stripped-down test model) produces a clear message instead of a raw Python traceback',
          'Test the dashboard against DPC2025 after intentionally introducing a known issue (temporarily unplacing a room, deleting a Mark value) to confirm each check actually surfaces the problem before trusting the tool on a real health review',
        ],
      },
    ],
    takeaways: [
      'A model health dashboard is best structured as several small, independent check functions, each collecting its own result, called in turn from one main script.',
      'doc.GetWarnings() reads the document\'s already-logged warnings; grouping by GetDescriptionText() with a Counter is far more actionable than a single raw count.',
      'Unplaced rooms are detected by checking for r.Location is None or r.Area == 0 on the full Rooms collection — the room still exists as an element even though it was never placed.',
      'LookupParameter(name) combined with a p.HasValue check finds elements missing required data, distinguishing a truly blank parameter from an empty-but-present one.',
      'output.print_md() renders lightweight Markdown (headings, bold, horizontal rules) so a dashboard\'s headline numbers are scannable in seconds.',
      'output.print_table() renders an actual formatted table from a list of rows and a list of column headers, far more readable than one print() line per result.',
    ],
    resource: { label: 'Model Health Dashboard Build Guide', type: 'PDF' },
    quiz: { label: 'Model Health Dashboard Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-8', title: 'Build a Quick Purge & Audit Button' },
    next: { id: 'pyp-10', title: 'Build a Drawing Issue Tracker Tool' },
  },

  // ============================================================
  // LESSON PYP-10 — Build a Drawing Issue Tracker Tool
  // ============================================================
  {
    id: 'pyp-10', num: '10',
    title: 'Build a Drawing Issue Tracker Tool',
    topic: 'Model Health', cat: 'intermediate', readTime: '10 min', free: false,
    desc: 'Write revision/issue metadata — issue date, description, ISO 19650 suitability code — across a batch of sheets using a forms.ask_for_string-driven input flow, logging to shared parameters and exporting a CSV transmittal record.',
    intro: `Every drawing issue on a real project needs a record: which sheets went out, on what date, described how, and at what suitability. Doing this by hand in a spreadsheet after the fact is exactly the kind of clerical task that drifts out of sync with reality. This lesson builds an Issue Tracker tool for DPC2025 that prompts the user for the issue's metadata once, writes it onto shared parameters across every sheet in the batch, and exports a CSV issue log at the same time — so the transmittal record and the model's own data are always generated from the same single entry, never typed twice.`,
    sections: [
      {
        id: 's1', heading: 'What an Issue Record Actually Needs', level: 'h2',
        content: `Before writing any code, it is worth being precise about what a drawing issue record on DPC2025 actually captures, since this drives both the shared parameters and the CSV columns used later in the lesson.`,
        code: {
          label: 'DPC2025 Issue Record Fields',
          lines: [
            'Issue Date          e.g., "2026-07-02"',
            'Issue Description   e.g., "Issued for Coordination"',
            'Suitability Code    ISO 19650 code, e.g., "S2" or "A2"',
            'Sheet Number        per sheet, read from the sheet itself',
            'Sheet Name          per sheet, read from the sheet itself',
          ],
        },
        formula: { label: 'Core Idea', text: 'The user enters Issue Date, Description, and Suitability Code once per batch — Sheet Number and Sheet Name are read per sheet, never typed by hand' },
      },
      {
        id: 's2', heading: 'Prompting for Issue Metadata with forms.ask_for_string', level: 'h2',
        content: `pyRevit's forms module provides simple, ready-made input dialogs so a tool does not need a custom WPF window just to collect a few strings from the user.`,
        code: {
          label: 'Collecting the Issue Metadata',
          lines: [
            'from pyrevit import forms',
            '',
            'issue_date = forms.ask_for_string(',
            '    default="2026-07-02",',
            '    prompt="Enter the issue date (YYYY-MM-DD):",',
            '    title="DPC2025 Issue Tracker"',
            ')',
            '',
            'description = forms.ask_for_string(',
            '    prompt="Enter the issue description:",',
            '    title="DPC2025 Issue Tracker"',
            ')',
            '',
            'suitability = forms.ask_for_string(',
            '    default="S2",',
            '    prompt="Enter the ISO 19650 suitability code:",',
            '    title="DPC2025 Issue Tracker"',
            ')',
          ],
        },
        items: [
          'forms.ask_for_string() returns the typed string, or None if the user cancels the dialog — always check for None immediately after each call and exit cleanly (script.exit()) rather than continuing with missing data',
          'Supplying a sensible default= value (like today\'s date, or the previous suitability code) saves the user retyping the same value on every run',
          'Running three separate ask_for_string prompts in sequence is simpler to build and debug than one combined form, and is perfectly adequate for a three-field input flow like this one',
        ],
      },
      {
        id: 's3', heading: 'Selecting the Batch of Sheets', level: 'h2',
        content: `With the issue metadata collected once, the next step is resolving exactly which sheets in DPC2025 this issue applies to.`,
        code: {
          label: 'Selecting Sheets for This Issue',
          lines: [
            'from pyrevit import revit, forms',
            '',
            'all_sheets = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(DB.BuiltInCategory.OST_Sheets)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
            '',
            'selected_sheets = forms.SelectFromList.show(',
            '    sorted(all_sheets, key=lambda s: s.SheetNumber),',
            '    title="Select Sheets Being Issued",',
            '    multiselect=True,',
            '    name_attr="SheetNumber"',
            ')',
          ],
        },
        items: [
          'forms.SelectFromList.show() with multiselect=True gives the user a checkbox-style picker rather than requiring a manual pre-selection in the Revit UI before running the tool',
          'name_attr="SheetNumber" tells the picker which attribute of each Sheet element to display in the list, so the user sees sheet numbers rather than raw Element objects',
          'Sorting the source list by SheetNumber before passing it to the picker makes a long DPC2025 sheet set actually usable, instead of appearing in arbitrary collector order',
        ],
      },
      {
        id: 's4', heading: 'Writing the Issue Data onto Shared Parameters', level: 'h2',
        content: `With sheets selected and metadata collected, the write step applies the same three values across every selected sheet inside a single Transaction — this is the part of the tool that actually updates the DPC2025 model.`,
        code: {
          label: 'Writing Issue Metadata to Each Sheet',
          lines: [
            'from Autodesk.Revit.DB import Transaction',
            '',
            't = Transaction(doc, "Log Drawing Issue")',
            't.Start()',
            'try:',
            '    for sheet in selected_sheets:',
            '        sheet.LookupParameter("Issue Date").Set(issue_date)',
            '        sheet.LookupParameter("Issue Description").Set(description)',
            '        sheet.LookupParameter("Suitability Code").Set(suitability)',
            '    t.Commit()',
            'except Exception as ex:',
            '    t.RollBack()',
            '    raise ex',
          ],
        },
        items: [
          '"Issue Date", "Issue Description", and "Suitability Code" are project shared parameters bound to the Sheets category in DPC2025 — they must already be loaded and bound before this script can find them, exactly like any other shared parameter workflow',
          'Wrapping the whole loop in one Transaction rather than one per sheet keeps the operation atomic — either every selected sheet gets the new issue data, or (on an error) none of them do, thanks to the RollBack in the except block',
          'LookupParameter(name).Set(value) is the standard pyRevit/Revit API write pattern used throughout this course — confirm the returned parameter is not None before calling Set() if the parameter binding on DPC2025 has ever been uncertain',
        ],
        formula: { label: 'Atomicity Rule', text: 'One Transaction wrapping the full sheet loop means the issue log either applies to every selected sheet or is rolled back entirely — never a partially applied issue' },
      },
      {
        id: 's5', heading: 'Exporting the CSV Issue Log', level: 'h2',
        content: `The model-side write covers Revit's own record, but a real transmittal also needs a plain CSV file that can be emailed or filed alongside the issued drawings — independent of anyone opening DPC2025 itself.`,
        code: {
          label: 'Writing the CSV Transmittal Record',
          lines: [
            'import csv',
            'import os',
            '',
            'csv_path = os.path.join(os.path.expanduser("~"), "Desktop",',
            '                        "DPC2025_Issue_Log_{}.csv".format(issue_date))',
            '',
            'with open(csv_path, mode="wb") as f:',
            '    writer = csv.writer(f)',
            '    writer.writerow(["Sheet Number", "Sheet Name", "Issue Date",',
            '                      "Description", "Suitability Code"])',
            '    for sheet in selected_sheets:',
            '        writer.writerow([sheet.SheetNumber, sheet.Name, issue_date,',
            '                          description, suitability])',
            '',
            'forms.alert("Issue log exported to:\\n{}".format(csv_path))',
          ],
        },
        items: [
          'Building the CSV file name from the issue date (e.g., DPC2025_Issue_Log_2026-07-02.csv) means every issue produces its own dated, non-overwriting record automatically',
          'The CSV header row and column order should mirror the shared parameters written to the model, so the two records never drift into inconsistent terminology',
          'A closing forms.alert() confirming the saved file path saves the user from having to guess where the export landed, especially when run repeatedly across multiple issues',
        ],
      },
      {
        id: 's6', heading: 'Keeping the Model and the Transmittal in Sync', level: 'h2',
        content: `The entire value of this tool is that the Revit-side shared parameters and the CSV transmittal record are generated from the exact same run, the exact same three input values, and the exact same sheet selection — never re-typed separately.`,
        items: [
          'Running the CSV export from within the same script, immediately after the Transaction commits, guarantees the two records can never disagree — a separate "export a log later" step would reopen exactly the risk this tool is meant to close',
          'If the Transaction fails and rolls back, the script should stop before attempting the CSV export, so a failed model write never produces a transmittal record claiming an issue that did not actually happen',
          'Encourage keeping every exported CSV (not overwriting the same file) as the office\'s running drawing issue history for DPC2025, since each file is already uniquely named by date',
        ],
        formula: { label: 'Single Source of Truth', text: 'One user input flow feeds both the Revit shared parameters and the CSV export in the same script run — the model and the transmittal record can never fall out of sync' },
      },
    ],
    takeaways: [
      'A drawing issue record needs an Issue Date, Description, and ISO 19650 Suitability Code entered once, plus Sheet Number and Sheet Name read per sheet — never typed by hand per sheet.',
      'forms.ask_for_string() collects each metadata value with a default and a prompt, returning None if the user cancels — always check for None before continuing.',
      'forms.SelectFromList.show() with multiselect=True and name_attr gives the user a checkbox picker over the full DPC2025 sheet set instead of a pre-selection requirement.',
      'The write step applies LookupParameter(name).Set(value) across every selected sheet inside a single Transaction, so the whole batch commits or rolls back together.',
      'A CSV export using Python\'s csv module produces a plain-text transmittal record independent of Revit, named by issue date so each run produces its own non-overwriting file.',
      'Running the CSV export immediately after the Transaction commits (and only if it commits) keeps the Revit shared parameters and the transmittal record permanently in sync.',
    ],
    resource: { label: 'Drawing Issue Tracker Build Guide', type: 'PDF' },
    quiz: { label: 'Drawing Issue Tracker Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-9', title: 'Build a Model Health Dashboard' },
    next: { id: 'pyp-11', title: 'Build a Parameter Audit Tool — Find Missing Data' },
  },

  // ============================================================
  // LESSON PYP-11 — Build a Parameter Audit Tool — Find Missing Data
  // ============================================================
  {
    id: 'pyp-11', num: '11',
    title: 'Build a Parameter Audit Tool — Find Missing Data',
    topic: 'Audits & Worksets', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Collect a category, check a list of required parameter names against each element using LookupParameter, and report which elements are missing which fields — with clickable output links to select the offending elements.',
    intro: `The mini missing-parameter check from the health dashboard lesson deserves a proper, standalone tool of its own — one that checks a full list of required fields across a whole category and, crucially, lets a BIM Manager click straight through to the offending elements instead of hunting for them by Element Id. This lesson builds exactly that for DPC2025, and along the way contrasts Python's LookupParameter(name) pattern with the Element.HasParameter node from the companion Dynamo course, since the two approaches handle a missing parameter quite differently.`,
    sections: [
      {
        id: 's1', heading: 'Defining the Required Parameter List', level: 'h2',
        content: `A parameter audit tool needs a clear, explicit list of what "complete" means for the category being checked — this list is the single most important design decision in the whole tool.`,
        code: {
          label: 'DPC2025 Required Fields — Doors',
          lines: [
            'category = DB.BuiltInCategory.OST_Doors',
            'required_params = ["Mark", "Fire Rating", "Level", "Comments"]',
          ],
        },
        items: [
          'Keep the required list specific to one category at a time (Doors, Rooms, Equipment) — different categories have different mandatory fields, and mixing them in one pass produces a confusing, category-blind report',
          'Source this list from DPC2025\'s actual BIM Execution Plan or client data requirements, not an arbitrary guess — an audit tool is only as useful as the list of fields it checks against',
          'Store required_params as a plain Python list at the top of the script so it can be edited in one place as project requirements evolve',
        ],
      },
      {
        id: 's2', heading: 'Checking Each Element with LookupParameter', level: 'h2',
        content: `The core of the audit loops over every collected element and, for each required parameter name, checks whether that parameter exists and holds a value.`,
        code: {
          label: 'The Core Audit Loop',
          lines: [
            'elements = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(category)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
            '',
            'issues = []',
            'for el in elements:',
            '    for name in required_params:',
            '        p = el.LookupParameter(name)',
            '        if p is None or not p.HasValue:',
            '            issues.append((el, name))',
          ],
        },
        items: [
          'LookupParameter(name) returns the Parameter object if it exists on this element, or None if the parameter is missing, unbound, or simply not applicable to this instance',
          'p.HasValue catches the second failure mode: a parameter that exists but was never actually filled in, which is just as much a data gap as a missing parameter binding',
          'Storing the actual element object (not just its Id) in the issues list keeps everything needed for both the report and the later clickable links available in one place',
        ],
      },
      {
        id: 's3', heading: 'Python\'s is None Check vs. Dynamo\'s Element.HasParameter', level: 'h2',
        content: `Anyone coming from the companion Dynamo Practice course will recognize this exact problem from the Element.HasParameter node — but the two environments express the check quite differently, which is worth understanding rather than memorizing.`,
        items: [
          'In Dynamo, Element.HasParameter(element, name) is a dedicated node that returns a Boolean — you ask the question "does this parameter exist?" directly, as its own explicit step',
          'In Python, there is no separate has-parameter function — LookupParameter(name) itself returns the object or None, so the existence check and the retrieval happen in the same call, and a plain is None comparison is how Python asks the same question',
          'This is a good example of a broader pattern in moving from Dynamo to Python: Dynamo tends to expose one node per distinct question, while Python folds several related questions into the return value of a single method call',
          'Neither approach is "better" — but a script that only checks p is None without a follow-up p.HasValue check will miss elements where the parameter exists but was left blank, a distinction worth remembering regardless of which environment you are in',
        ],
        formula: { label: 'Cross-Environment Comparison', text: 'Dynamo: Element.HasParameter(element, name) -> Boolean, asked as its own step | Python: LookupParameter(name) -> Parameter object or None, existence and retrieval combined in one call' },
      },
      {
        id: 's4', heading: 'Reporting with Clickable Output Links', level: 'h2',
        content: `A list of Element Ids in a report is only barely useful — pyRevit's output window supports linkify-style output that turns an element reference into a clickable link, selecting that element in the Revit view the moment it is clicked.`,
        code: {
          label: 'Linkified Audit Report',
          lines: [
            'output = script.get_output()',
            'output.print_md("# DPC2025 Parameter Audit — Doors")',
            '',
            'for el, name in issues:',
            '    mark = el.LookupParameter("Mark")',
            '    label = mark.AsString() if mark and mark.HasValue else "(no Mark)"',
            '    output.print_md("- **{}** missing **{}** {}".format(',
            '        label, name, output.linkify([el.Id])',
            '    ))',
          ],
        },
        items: [
          'output.linkify(element_ids) builds a clickable link string that, when clicked in the output window, selects and (depending on view) zooms to those elements directly in the Revit UI',
          'Passing a list of Element Ids (even a single-item list) to linkify() keeps the function signature consistent whether the report is linking one element or a group of them',
          'Combining print_md() bold text with an inline linkify() call produces a report line that is both human-readable ("Door D01 missing Fire Rating") and immediately actionable with one click',
        ],
        formula: { label: 'Why Linkify Matters', text: 'A raw Element Id makes a reader hunt through the model manually — output.linkify() turns that same reference into a one-click selection, which is the difference between a report that gets read and one that gets acted on' },
      },
      {
        id: 's5', heading: 'Grouping the Report by Missing Field', level: 'h2',
        content: `A flat list of (element, missing field) pairs is harder to act on than the same data grouped by which field is missing, since a BIM Manager usually wants to tackle one field across many elements at once (e.g., "let\'s fix every missing Fire Rating together").`,
        items: [
          'Build a dictionary keyed by parameter name, appending each offending element to the list under its missing field, rather than printing the flat issues list in collection order',
          'Print one print_md() sub-heading per missing field (## Missing: Fire Rating), followed by the linkified list of elements under that heading, so the report reads as an actionable checklist rather than a single undifferentiated dump',
          'This grouping also makes it trivial to print a short summary count per field at the very top of the report (e.g., "Fire Rating: 12 missing, Comments: 4 missing") before the detailed lists',
        ],
      },
      {
        id: 's6', heading: 'Extending the Audit to Multiple Categories', level: 'h2',
        content: `Once the single-category version works reliably on DPC2025, the same audit logic extends naturally to checking several categories in one run, each with its own required-fields list.`,
        items: [
          'Structure the required-fields definition as a dictionary keyed by category (e.g., {OST_Doors: [...], OST_Rooms: [...]}) rather than a single flat list, so the audit loop can iterate categories and apply the correct required list to each',
          'Keep the per-category report sections clearly separated with their own print_md() headings, so a multi-category run still reads as several distinct, scannable audits rather than one merged, confusing list',
          'This is the same category-by-category expansion pattern the health dashboard and level/grid checker tools in this course rely on — one working single-category check, generalized to loop across a dictionary of categories',
        ],
        formula: { label: 'Scaling Pattern', text: 'Single category + flat required-params list -> dictionary of {category: required-params list} -> one loop iterating categories, applying the correct list to each' },
      },
    ],
    takeaways: [
      'A parameter audit tool starts from an explicit, project-specific required-fields list for one category at a time, sourced from DPC2025\'s actual BIM Execution Plan requirements.',
      'LookupParameter(name) returns the Parameter object or None in a single call, combining existence and retrieval — contrasted with Dynamo\'s dedicated Element.HasParameter Boolean node.',
      'A parameter can exist but still be blank — checking p.HasValue after confirming p is not None catches this second, equally important failure mode.',
      'output.linkify(element_ids) turns an Element Id reference into a clickable link that selects the element directly in the Revit view from the output window.',
      'Grouping the report by missing field (rather than printing a flat list) makes the audit an actionable checklist, since fixes are usually tackled one field at a time across many elements.',
      'The single-category audit pattern extends to multiple categories by keying the required-fields definition as a dictionary of {category: required list} and looping over it.',
    ],
    resource: { label: 'Parameter Audit Tool Build Guide', type: 'PDF' },
    quiz: { label: 'Parameter Audit Tool Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-10', title: 'Build a Drawing Issue Tracker Tool' },
    next: { id: 'pyp-12', title: 'Build a Workset Manager — Assign Elements in Bulk' },
  },

  // ============================================================
  // LESSON PYP-12 — Build a Workset Manager — Assign Elements in Bulk
  // ============================================================
  {
    id: 'pyp-12', num: '12',
    title: 'Build a Workset Manager — Assign Elements in Bulk',
    topic: 'Audits & Worksets', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Use DB.WorksetTable and DB.WorksetId to bulk-assign a filtered set of elements to a target workset via the ELEM_PARTITION_PARAM built-in parameter, wrapped in a Transaction.',
    intro: `"Can you move all the shell and core elements onto the Shell workset?" is one of those requests that sounds simple and turns into an hour of tedious, error-prone clicking through the UI one element at a time on a model the size of DPC2025. This lesson builds a Workset Manager tool that filters elements by category (or another criterion), resolves the target workset by name, and bulk-assigns every filtered element to it in a single Transaction — replacing an hour of manual work with a few seconds of script execution.`,
    sections: [
      {
        id: 's1', heading: 'How Revit Actually Stores Workset Assignment', level: 'h2',
        content: `A workset assignment is not a special hidden property — it is stored as an ordinary built-in parameter on the element, which means it can be read and written with exactly the same Parameter API used for every other parameter in this course.`,
        code: {
          label: 'The Workset Parameter',
          lines: [
            'BuiltInParameter.ELEM_PARTITION_PARAM',
            '',
            '# Reading an element\'s current workset parameter',
            'workset_param = element.get_Parameter(',
            '    DB.BuiltInParameter.ELEM_PARTITION_PARAM',
            ')',
            'current_workset_id = workset_param.AsInteger()',
          ],
        },
        items: [
          'ELEM_PARTITION_PARAM is the built-in parameter that stores an element\'s workset assignment as an integer WorksetId value',
          'get_Parameter(BuiltInParameter...) is the same pattern used for any other built-in parameter access — workset assignment is not a special case requiring different API surface',
          'This is only meaningful in a workshared (multi-user, central-model-linked) DPC2025 file — a non-workshared model has no worksets to assign elements to',
        ],
        formula: { label: 'Key Insight', text: 'Workset assignment is just another built-in parameter (ELEM_PARTITION_PARAM) — the same Parameter.Set() pattern used throughout this course applies here too' },
      },
      {
        id: 's2', heading: 'Resolving the Target Workset with WorksetTable', level: 'h2',
        content: `Before assigning anything, the script needs the actual WorksetId of the target workset (e.g., "Shell") — found by name through the document's WorksetTable, since worksets are referenced by Id, not by name string, when writing the parameter.`,
        code: {
          label: 'Looking Up a Workset by Name',
          lines: [
            'workset_table = doc.GetWorksetTable()',
            'target_name = "Shell"',
            '',
            'all_worksets = DB.FilteredWorksetCollector(doc)\\',
            '    .OfKind(DB.WorksetKind.UserWorkset)\\',
            '    .ToWorksets()',
            '',
            'target_workset = next(',
            '    (w for w in all_worksets if w.Name == target_name), None',
            ')',
            'if target_workset is None:',
            '    forms.alert("Workset \'{}\' not found.".format(target_name))',
            '    script.exit()',
            '',
            'target_id = target_workset.Id',
          ],
        },
        items: [
          'DB.FilteredWorksetCollector(doc).OfKind(DB.WorksetKind.UserWorkset) collects the user-created worksets in DPC2025 — filtering by kind excludes system worksets that should never be assignment targets',
          'Matching by exact w.Name string is simple and reliable as long as DPC2025\'s workset names are consistent — consider a case-insensitive comparison if workset naming has ever been inconsistent across the project',
          'Always check for a None result and exit cleanly with a clear forms.alert() message if the named workset does not exist, rather than letting a later .Id access fail with a confusing AttributeError',
        ],
      },
      {
        id: 's3', heading: 'Filtering the Elements to Reassign', level: 'h2',
        content: `The elements being bulk-assigned are usually filtered by category, but the same pattern works for any FilteredElementCollector criterion — a selection, a parameter value filter, or a combination of several.`,
        code: {
          label: 'Filtering by Category',
          lines: [
            'category = DB.BuiltInCategory.OST_Walls',
            '',
            'elements = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(category)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
          ],
        },
        items: [
          'Any of the collector patterns used elsewhere in this course apply equally here — category, active selection, or a parameter-based filter (e.g., only walls whose Comments contain "Shell") can all feed the same assignment loop',
          'For a request like "move all the shell and core elements," combining a category filter with a parameter check (or working from the user\'s current Revit selection via revit.get_selection()) is often more precise than category alone',
          'Print or forms.alert() the resulting element count before making any change, so the user can confirm the filter caught the expected number of elements before committing to a bulk reassignment',
        ],
      },
      {
        id: 's4', heading: 'Bulk-Assigning the Workset Parameter in a Transaction', level: 'h2',
        content: `With the target WorksetId resolved and the element list filtered, the actual reassignment is a straightforward parameter write, looped across every filtered element inside one Transaction.`,
        code: {
          label: 'The Bulk Assignment Transaction',
          lines: [
            'from Autodesk.Revit.DB import Transaction',
            '',
            't = Transaction(doc, "Bulk Assign to Shell Workset")',
            't.Start()',
            'try:',
            '    for el in elements:',
            '        p = el.get_Parameter(DB.BuiltInParameter.ELEM_PARTITION_PARAM)',
            '        if p and not p.IsReadOnly:',
            '            p.Set(target_id.IntegerValue)',
            '    t.Commit()',
            'except Exception as ex:',
            '    t.RollBack()',
            '    raise ex',
          ],
        },
        items: [
          'p.Set(target_id.IntegerValue) writes the workset assignment exactly like any other integer parameter — WorksetId itself is not directly what gets stored, its IntegerValue is',
          'Checking p.IsReadOnly before writing skips any element whose workset parameter cannot be changed (a rare edge case, but cheap to guard against) instead of letting the whole Transaction fail on one element',
          'A single Transaction wrapping the entire loop means the reassignment is atomic — every filtered element ends up on the new workset together, or (on an exception) none of them do',
        ],
        formula: { label: 'Core Pattern', text: 'Resolve target WorksetId via WorksetTable/FilteredWorksetCollector -> filter elements -> loop, writing ELEM_PARTITION_PARAM.Set(target_id.IntegerValue) inside one Transaction' },
      },
      {
        id: 's5', heading: 'Confirming the Reassignment', level: 'h2',
        content: `Because a bulk workset change affects how a large group of elements behaves for every collaborator on a workshared DPC2025 model, a short confirmation step after the write closes the loop for the user running the tool.`,
        items: [
          'A closing forms.alert() reporting how many elements were reassigned (e.g., "142 elements moved to Shell workset") gives immediate, concrete confirmation that the bulk operation ran as expected',
          'Spot-check a handful of the reassigned elements\' Properties palette in Revit afterward to confirm the Workset field now shows the target workset name, as a quick sanity check beyond trusting the script output alone',
          'Since worksets affect visibility and ownership in a workshared model, communicate a bulk reassignment to the rest of the DPC2025 project team before running it, the same courtesy expected of any manual bulk workset change',
        ],
      },
      {
        id: 's6', heading: 'Why This Beats the Manual UI Workflow', level: 'h2',
        content: `Revit's own UI supports selecting elements and changing their Workset property in the Properties palette — but only for whatever is currently selected, which is exactly the bottleneck this tool removes.`,
        items: [
          'Selecting "everything that should be on the Shell workset" through the UI usually means multiple manual selection passes (by category, by view, by manual pick) before the Properties palette change can even be applied',
          'A script-driven filter (category, selection, or parameter-based) captures the exact same intent in a single FilteredElementCollector call, applied consistently and repeatably every time the tool is run',
          'Because the filter criteria live in code rather than in someone\'s memory of "which elements need to move," the same tool can be re-run later as DPC2025 evolves, without needing to remember the manual selection steps that worked last time',
        ],
        formula: { label: 'Efficiency Payoff', text: 'One script run replaces multiple manual selection passes and repeated Properties-palette edits — the exact filter logic is captured in code and can be re-run identically at any time' },
      },
    ],
    takeaways: [
      'Workset assignment is stored as the built-in parameter ELEM_PARTITION_PARAM, read and written with the same Parameter API pattern used for any other parameter.',
      'DB.FilteredWorksetCollector(doc).OfKind(DB.WorksetKind.UserWorkset) resolves user worksets by name, giving the WorksetId needed to write the parameter — worksets are referenced by Id, not by name string, when assigning.',
      'Elements to reassign can be filtered by category, active selection, or a parameter-based check — any FilteredElementCollector pattern used elsewhere in this course applies equally here.',
      'The actual reassignment writes target_id.IntegerValue onto each element\'s ELEM_PARTITION_PARAM parameter, looped inside a single Transaction so the whole batch commits or rolls back together.',
      'Checking p.IsReadOnly before writing, and confirming the target workset was found before starting the Transaction, avoids a failed or partially applied bulk reassignment.',
      'A single filtered, scripted reassignment replaces multiple manual selection passes and repeated Properties-palette edits, and can be re-run identically as DPC2025 evolves.',
    ],
    resource: { label: 'Workset Manager Build Guide', type: 'PDF' },
    quiz: { label: 'Workset Manager Tool Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-11', title: 'Build a Parameter Audit Tool — Find Missing Data' },
    next: { id: 'pyp-13', title: 'Build a Level & Grid Checker Tool' },
  },

  // ============================================================
  // LESSON PYP-13 — Build a Level & Grid Checker Tool
  // ============================================================
  {
    id: 'pyp-13', num: '13',
    title: 'Build a Level & Grid Checker Tool',
    topic: 'Checks & COBie', cat: 'intermediate', readTime: '8 min', free: false,
    desc: 'Verify every Level in DPC2025 has a unique elevation and name, and every Grid has a unique name, flagging violations with a FilteredElementCollector plus a Python set/dictionary uniqueness check.',
    intro: `Duplicate levels and grids are the kind of quiet, structural mistake that causes real downstream problems — a duplicated grid line confuses a structural engineer's coordinate references, and two levels with the same elevation can silently break schedules and view ranges. This lesson builds a small, fast QA tool for DPC2025 that verifies every Level has a unique name and elevation, and every Grid has a unique name, flagging any violations found. It is also a good showcase of how much simpler a uniqueness check is in plain Python than the equivalent visual-node logic in Dynamo.`,
    sections: [
      {
        id: 's1', heading: 'Collecting Levels and Grids', level: 'h2',
        content: `Both Levels and Grids are ordinary datum elements, collected the same way as any other category with FilteredElementCollector.`,
        code: {
          label: 'Collecting Both Categories',
          lines: [
            'levels = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(DB.BuiltInCategory.OST_Levels)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
            '',
            'grids = DB.FilteredElementCollector(doc)\\',
            '    .OfCategory(DB.BuiltInCategory.OST_Grids)\\',
            '    .WhereElementIsNotElementType()\\',
            '    .ToElements()',
          ],
        },
        items: [
          'Both collections are project-wide by default (no view scoping applied), which is correct here — level and grid uniqueness is a whole-model concern, not a per-view one',
          'Levels and Grids are both relatively small collections even on a large project like DPC2025, so this check runs quickly with no special performance handling needed',
        ],
      },
      {
        id: 's2', heading: 'Checking for Duplicate Level Names', level: 'h2',
        content: `A duplicate Level name is a straightforward "have we seen this string before" check — exactly the kind of thing a Python set makes almost trivially simple to write.`,
        code: {
          label: 'Detecting Duplicate Level Names',
          lines: [
            'seen_names = set()',
            'duplicate_names = []',
            '',
            'for lvl in levels:',
            '    name = lvl.Name',
            '    if name in seen_names:',
            '        duplicate_names.append(lvl)',
            '    else:',
            '        seen_names.add(name)',
          ],
        },
        items: [
          'A Python set gives O(1) membership testing (name in seen_names) — checking whether a name has already been seen is a single fast lookup, regardless of how many levels have already been processed',
          'Because Revit already prevents two Levels from sharing an identical name within the same document in most normal workflows, this check is mainly a safety net for edge cases — linked/copied levels from another file, or a renaming script (like the ISO 19650 naming tool in the companion Dynamo course) that produced an unexpected collision',
          'The duplicate_names list holds the actual Level elements, ready to feed straight into a linkified output report exactly as in the Parameter Audit Tool lesson',
        ],
      },
      {
        id: 's3', heading: 'Checking for Duplicate Level Elevations', level: 'h2',
        content: `Two Levels with the same name are unusual, but two Levels with the same elevation and different names is a more common and more dangerous mistake — often the result of a copy-paste error when adding a new level.`,
        code: {
          label: 'Detecting Duplicate Elevations',
          lines: [
            'from collections import defaultdict',
            '',
            'by_elevation = defaultdict(list)',
            'for lvl in levels:',
            '    by_elevation[round(lvl.Elevation, 6)].append(lvl)',
            '',
            'duplicate_elevations = {',
            '    elev: lvls for elev, lvls in by_elevation.items()',
            '    if len(lvls) > 1',
            '}',
          ],
        },
        items: [
          'defaultdict(list) groups every Level by its elevation value, so any elevation with more than one Level in its group is immediately identifiable — a dictionary comprehension keeps only the groups with duplicates',
          'Rounding the elevation (round(lvl.Elevation, 6)) avoids false positives from floating-point representation differences that are not meaningfully different elevations in practice',
          'lvl.Elevation returns the value in Revit\'s internal units (decimal feet) — this is fine for a pure uniqueness comparison, since no unit conversion is needed when only comparing values against each other',
        ],
        formula: { label: 'Grouping Pattern', text: 'defaultdict(list) groups elements by a shared key value in one pass — any group with more than one member is a duplicate, found without a single nested loop' },
      },
      {
        id: 's4', heading: 'Checking for Duplicate Grid Names', level: 'h2',
        content: `Grid name uniqueness uses exactly the same set-based pattern as Level names — the two checks share the same underlying logic, applied to a different category and a different Name-equivalent property.`,
        code: {
          label: 'Detecting Duplicate Grid Names',
          lines: [
            'seen_grid_names = set()',
            'duplicate_grids = []',
            '',
            'for grid in grids:',
            '    name = grid.Name',
            '    if name in seen_grid_names:',
            '        duplicate_grids.append(grid)',
            '    else:',
            '        seen_grid_names.add(name)',
          ],
        },
        items: [
          'Grid.Name is the grid\'s label as shown in the Revit view (e.g., "A", "1", "2") — the same property referenced when structural framing or naming scripts elsewhere in this course need to identify a specific grid line',
          'Because a project the size of DPC2025 typically has dozens of grid lines across both numbered and lettered series, a duplicate here is easy to miss visually in a busy structural plan but is caught instantly by this loop',
          'The identical seen-set pattern used for Level names above reinforces how reusable this uniqueness check is — the same four lines of logic, applied to Level.Name, Level.Elevation (grouped), or Grid.Name with no structural changes',
        ],
      },
      {
        id: 's5', heading: 'Why This Is Simpler in Python Than in Dynamo', level: 'h2',
        content: `The equivalent uniqueness check in Dynamo requires several stock nodes chained together — List.UniqueItems, List.Count, list comparison nodes — to arrive at the same answer a single Python set or dictionary reaches in a handful of lines.`,
        items: [
          'In Dynamo, finding duplicates typically means comparing the full list\'s count against a List.UniqueItems-reduced count, then a further pass to identify which specific items were the duplicates — several distinct nodes and wiring steps',
          'In Python, a set naturally IS the concept of "unique items," and the seen-before check is a single boolean test with no separate reduction step required — the language\'s built-in data structures map directly onto the problem',
          'This is not a claim that Python is "better" than Dynamo in general — it is a concrete illustration of why some checks (particularly ones involving membership testing and grouping) read and run more directly in a text-based language with native set/dictionary support',
        ],
        formula: { label: 'Direct Comparison', text: 'Dynamo: List.UniqueItems + count comparison + further filtering to isolate duplicates (multiple nodes) | Python: a set\'s "in" check and a dict/defaultdict grouping (a few lines, no extra reduction step)' },
      },
      {
        id: 's6', heading: 'Reporting the Violations', level: 'h2',
        content: `With all three checks complete, the report follows the same print_md() plus linkified list pattern used by the other QA tools in this course, so the whole toolkit reads consistently.`,
        code: {
          label: 'Consolidated Report',
          lines: [
            'output.print_md("# DPC2025 Level & Grid Checker")',
            'output.print_md("**Duplicate Level Names:** {}".format(len(duplicate_names)))',
            'output.print_md("**Duplicate Level Elevations:** {}".format(len(duplicate_elevations)))',
            'output.print_md("**Duplicate Grid Names:** {}".format(len(duplicate_grids)))',
          ],
        },
        items: [
          'Print a short summary block first, then a linkified detail section per violation type, exactly matching the reporting structure used in the Model Health Dashboard lesson',
          'For duplicate elevations, print the shared elevation value alongside the linkified list of every Level sharing it, so the report shows both what the problem is and which elements are involved',
          'A clean run of this tool (zero violations across all three checks) is itself a useful, reportable result on DPC2025 — confirming the model\'s datum structure is sound is worth stating explicitly, not just staying silent when there is nothing to flag',
        ],
      },
    ],
    takeaways: [
      'Levels and Grids are collected project-wide with FilteredElementCollector, since datum uniqueness is a whole-model concern rather than a per-view one.',
      'A Python set gives fast, simple "have we seen this before" membership testing, making duplicate Level or Grid name detection a handful of lines with no extra reduction step.',
      'Grouping Levels by rounded elevation with a defaultdict(list) and filtering for groups with more than one member finds duplicate elevations, a more dangerous and less obvious mistake than duplicate names.',
      'Rounding Elevation values before comparison avoids false positives from floating-point representation noise.',
      'This uniqueness check is meaningfully simpler in Python than the equivalent Dynamo graph, since sets and dictionaries map directly onto the concept of uniqueness and grouping without extra nodes.',
      'Reporting follows the same print_md() summary plus linkified detail pattern as the other QA tools in this course, including explicitly confirming a clean result when no violations are found.',
    ],
    resource: { label: 'Level & Grid Checker Build Guide', type: 'PDF' },
    quiz: { label: 'Level & Grid Checker Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-12', title: 'Build a Workset Manager — Assign Elements in Bulk' },
    next: { id: 'pyp-14', title: 'Build a COBie Data Checker — Verify FM Fields are Populated' },
  },

  // ============================================================
  // LESSON PYP-14 — Build a COBie Data Checker — Verify FM Fields are Populated
  // ============================================================
  {
    id: 'pyp-14', num: '14',
    title: 'Build a COBie Data Checker — Verify FM Fields are Populated',
    topic: 'Checks & COBie', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Check COBie-prefixed shared parameters (COBie.Component, COBie.Type, etc.) across Rooms and Components, reporting which elements have blank or missing COBie fields before a real handover export.',
    intro: `The companion Dynamo Practice course closed with a script that bulk-populates COBie-prefixed shared parameters from an asset spreadsheet — but populating is only half the job. Before a real handover export goes out, someone needs to confirm the data actually landed everywhere it should. This lesson builds that verification step as a standalone pyRevit tool for DPC2025: a read-only checker that scans Rooms and Components for blank or missing COBie fields and reports exactly what is incomplete, well before the COBie export tool is ever run for real.`,
    sections: [
      {
        id: 's1', heading: 'This Tool Reads — It Never Writes', level: 'h2',
        content: `It is worth stating plainly at the start: this is a read-only checking tool. It does not populate COBie data (that is the bulk-population script from the companion Dynamo course), and it makes no changes to DPC2025 at all.`,
        items: [
          'Because this script never modifies the model, it needs no Transaction anywhere in its logic — every operation is a read',
          'This also means it is always safe to run at any time during the project, as often as needed, with zero risk of altering DPC2025\'s data',
          'Keeping the population script and the checking script as two separate tools mirrors good practice generally — a tool that changes data and a tool that verifies data are different responsibilities, and conflating them makes both harder to trust',
        ],
        formula: { label: 'Tool Boundary', text: 'Population (bulk-writing COBie parameters) and Checking (verifying they are filled) are deliberately separate tools — this lesson builds only the second one' },
      },
      {
        id: 's2', heading: 'The COBie-Prefixed Parameters Being Checked', level: 'h2',
        content: `As introduced in the companion Dynamo Practice course, COBie data is staged inside Revit using shared parameters prefixed "COBie." — this tool checks a defined list of those parameters across the relevant categories.`,
        code: {
          label: 'COBie Fields to Check',
          lines: [
            'room_fields = ["COBie.Space.Description"]',
            'component_fields = ["COBie.Component", "COBie.Type",',
            '                    "COBie.Component.SerialNumber"]',
            '',
            'categories_to_check = {',
            '    DB.BuiltInCategory.OST_Rooms: room_fields,',
            '    DB.BuiltInCategory.OST_DuctTerminal: component_fields,',
            '    DB.BuiltInCategory.OST_PlumbingFixtures: component_fields,',
            '}',
          ],
        },
        items: [
          'Rooms correspond to COBie\'s Space sheet, so the fields checked on Rooms are different from the Component-sheet fields checked on physical equipment categories',
          'Structuring categories_to_check as a dictionary keyed by category, mapping to the correct field list, is the same scaling pattern used in the Parameter Audit Tool lesson — one loop, per-category field lists',
          'This exact field list should be confirmed against DPC2025\'s actual bound shared parameters before relying on the tool — a field name typo here would silently report every element as "missing" a field that does not even exist under that name',
        ],
      },
      {
        id: 's3', heading: 'Scanning Categories for Blank or Missing Fields', level: 'h2',
        content: `The scanning loop is a direct extension of the audit pattern from the Parameter Audit Tool lesson, applied specifically to COBie fields across the categories dictionary.`,
        code: {
          label: 'The COBie Scan Loop',
          lines: [
            'incomplete = []',
            '',
            'for category, fields in categories_to_check.items():',
            '    elements = DB.FilteredElementCollector(doc)\\',
            '        .OfCategory(category)\\',
            '        .WhereElementIsNotElementType()\\',
            '        .ToElements()',
            '',
            '    for el in elements:',
            '        for field in fields:',
            '            p = el.LookupParameter(field)',
            '            if p is None or not p.HasValue or p.AsString() == "":',
            '                incomplete.append((el, field))',
          ],
        },
        items: [
          'p.AsString() == "" catches a third failure mode specific to text-based COBie fields: a parameter that technically "has a value" in the sense of being set, but was set to an empty string rather than left genuinely untouched',
          'Checking all three conditions (missing parameter, no value, empty string) together gives a more complete picture than any single check alone — COBie data entered inconsistently by different team members can fail in any of these three ways',
          'Grouping incomplete entries by category as the loop proceeds (rather than one flat list) makes the eventual report naturally organized by Rooms vs. each Component category',
        ],
      },
      {
        id: 's4', heading: 'Reporting Incomplete COBie Data', level: 'h2',
        content: `The report follows the same print_md() plus print_table()/linkify() pattern established earlier in this course, organized so a BIM Manager can see exactly what is missing before scheduling the real handover export.`,
        code: {
          label: 'COBie Completeness Report',
          lines: [
            'output.print_md("# DPC2025 COBie Data Completeness Check")',
            'output.print_md("**Total Incomplete Fields Found:** {}".format(len(incomplete)))',
            '',
            'output.print_md("## Rooms — COBie.Space.Description")',
            'room_issues = [(el, f) for el, f in incomplete',
            '               if el.Category.Id == DB.ElementId(',
            '                   DB.BuiltInCategory.OST_Rooms)]',
            'for el, field in room_issues:',
            '    output.print_md("- Room {} {}".format(',
            '        el.Number, output.linkify([el.Id])))',
          ],
        },
        items: [
          'A summary count at the top gives an immediate sense of how much work remains before handover, before the reader scrolls into the per-category detail',
          'Linkified entries let the BIM Manager (or whoever is chasing down the missing data) click straight through to the specific Room or Component that needs attention',
          'Because this tool may be run repeatedly in the weeks leading up to handover as data gets progressively filled in, a consistent report format lets the same team track completeness improving over successive runs',
        ],
      },
      {
        id: 's5', heading: 'A Read-Only Tool as a Pre-Export Gate', level: 'h2',
        content: `The real value of this tool is procedural as much as technical — it gives the office a defined, repeatable checkpoint to run before the actual COBie export/extension is ever executed for a real handover deliverable.`,
        items: [
          'Running the actual Revit COBie export/extension against a model with incomplete data (as covered in the companion Dynamo course) produces a technically valid but practically useless deliverable — blank cells where facilities management needs real values',
          'Treat a fully clean run of this checker (zero incomplete fields across every checked category) as the actual go/no-go gate before scheduling the real export, rather than just running the export and hoping for the best',
          'Because the tool is read-only, it can be run as many times as needed in the run-up to handover with zero risk — encourage running it early and often rather than only once, right before the deadline, when there is no time left to fix what it finds',
        ],
        formula: { label: 'Procedural Value', text: 'A read-only checker run repeatedly in the weeks before handover — not just once at the deadline — turns COBie completeness from a last-minute scramble into a tracked, improving metric' },
      },
      {
        id: 's6', heading: 'Extending the Field List as Requirements Evolve', level: 'h2',
        content: `COBie field requirements are rarely fixed for the life of a project — DPC2025\'s specific facilities management requirements may add or adjust which fields are considered mandatory as the handover approaches.`,
        items: [
          'Because the field lists and categories_to_check dictionary are defined once, clearly, at the top of the script, adding a newly required COBie field (or a newly in-scope category) is a small, contained edit rather than a rewrite',
          'If DPC2025\'s COBie requirements specify different mandatory fields for different equipment categories (e.g., stricter requirements for life-safety equipment than for general fixtures), extend the categories_to_check dictionary with category-specific field lists rather than forcing one shared list onto every category',
          'Keeping this checker\'s field list in sync with whatever field list the population script (from the companion Dynamo course) actually writes avoids a checker that reports false gaps for fields nobody was ever asked to populate in the first place',
        ],
      },
    ],
    takeaways: [
      'This is a deliberately read-only checking tool — it never writes to DPC2025 and needs no Transaction, distinct from the bulk-population script covered in the companion Dynamo Practice course.',
      'COBie fields are checked per category using a categories_to_check dictionary mapping each category to its correct list of COBie-prefixed field names (COBie.Space.Description for Rooms, COBie.Component/COBie.Type for equipment).',
      'A complete check looks for three failure modes: a missing parameter (LookupParameter returns None), a parameter with no value, and a parameter holding an empty string.',
      'Reporting follows the established print_md() plus linkify() pattern, organized per category so the results read as an actionable pre-handover checklist.',
      'A fully clean run (zero incomplete fields) should be treated as the actual go/no-go gate before running the real COBie export/extension, not an afterthought.',
      'Because the tool is read-only and safe to re-run at any time, it should be run repeatedly in the weeks before handover, not just once at the deadline.',
    ],
    resource: { label: 'COBie Data Checker Build Guide', type: 'PDF' },
    quiz: { label: 'COBie Data Checker Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-13', title: 'Build a Level & Grid Checker Tool' },
    next: { id: 'pyp-15', title: 'Build a Linked Model Health Checker — Status, Warnings & Missing Links' },
  },

  // ============================================================
  // LESSON PYP-15 — Build a Linked Model Health Checker — Status, Warnings & Missing Links
  // ============================================================
  {
    id: 'pyp-15', num: '15',
    title: 'Build a Linked Model Health Checker — Status, Warnings & Missing Links',
    topic: 'Links & Ribbon', cat: 'intermediate', readTime: '10 min', free: false,
    desc: 'Use DB.RevitLinkType and DB.RevitLinkInstance collectors to check whether linked models in DPC2025 are loaded, unloaded, or missing, and report each link\'s status plus its own warning count in one consolidated report.',
    intro: `A multi-discipline project like DPC2025 depends on its linked models actually being present and loaded — a coordination review performed against an unloaded structural link, without anyone noticing, is worse than no review at all. This lesson builds a linked model health checker that reports the load status of every link in DPC2025 (loaded, unloaded, or not found), and — for every link that IS loaded — reaches into that linked document to report its own warning count, since a linked Document object can be queried almost exactly like the host document.`,
    sections: [
      {
        id: 's1', heading: 'RevitLinkType vs. RevitLinkInstance', level: 'h2',
        content: `Checking link health starts with understanding two distinct but related element types Revit uses to represent a linked model — a common point of confusion worth clarifying up front.`,
        code: {
          label: 'The Two Link-Related Types',
          lines: [
            'link_types = DB.FilteredElementCollector(doc)\\',
            '    .OfClass(DB.RevitLinkType)\\',
            '    .ToElements()',
            '',
            'link_instances = DB.FilteredElementCollector(doc)\\',
            '    .OfClass(DB.RevitLinkInstance)\\',
            '    .ToElements()',
          ],
        },
        items: [
          '**RevitLinkType** represents the link definition itself — the reference to the external file and its current load state (loaded, unloaded, not found) — roughly analogous to a Family Type for a linked model',
          '**RevitLinkInstance** represents each placed occurrence of that link in the model — its position, its transform — roughly analogous to a Family Instance',
          'A single RevitLinkType can, in principle, have more than one RevitLinkInstance (the same file linked in at multiple placements), so both collections are worth gathering even though DPC2025 typically links each file only once',
        ],
        formula: { label: 'Type vs. Instance for Links', text: 'RevitLinkType = the link definition and its load status | RevitLinkInstance = each placed occurrence of that link — the same conceptual split as Family Type vs. Family Instance' },
      },
      {
        id: 's2', heading: 'Reading Each Link\'s Load Status', level: 'h2',
        content: `RevitLinkType exposes its current status directly, which is the first and most important thing this checker reports for every link in DPC2025.`,
        code: {
          label: 'Checking Load Status',
          lines: [
            'for link_type in link_types:',
            '    status = link_type.GetLinkedFileStatus()',
            '    name = link_type.Name',
            '    print("{}: {}".format(name, status))',
            '',
            '# DB.LinkedFileStatus values include:',
            '#   Loaded, Unloaded, NotFound, Invalid, LocallyUnloaded',
          ],
        },
        items: [
          'GetLinkedFileStatus() returns a LinkedFileStatus enum value directly — no separate lookup or file-system check is needed to know whether Revit currently considers the link loaded',
          'NotFound specifically means Revit cannot locate the linked file at its last known path — a common and disruptive issue when a project has moved to a new server location or a linked consultant file has been renamed',
          'Unloaded (deliberately unloaded by a user) and NotFound (the file cannot be located at all) are different problems requiring different fixes — the report should distinguish them clearly rather than lumping both under a generic "not working" label',
        ],
      },
      {
        id: 's3', heading: 'Querying a Linked Document\'s Own Warnings', level: 'h2',
        content: `The most powerful part of this checker is that each loaded linked model is, itself, a full Document object — meaning its own warnings can be queried directly, exactly like the host document's warnings in the Model Health Dashboard lesson.`,
        code: {
          label: 'Accessing the Linked Document',
          lines: [
            'for link_instance in link_instances:',
            '    linked_doc = link_instance.GetLinkDocument()',
            '    if linked_doc is None:',
            '        continue  # link is unloaded/not found — no Document to query',
            '',
            '    linked_warnings = linked_doc.GetWarnings()',
            '    print("{}: {} warnings".format(',
            '        linked_doc.Title, len(linked_warnings)))',
          ],
        },
        items: [
          'link_instance.GetLinkDocument() returns the actual Document object for the linked model — but only if that link is currently loaded; it returns None for an unloaded or missing link, which is why the None check comes first',
          'Once you have linked_doc, doc.GetWarnings() and any other Document-level query used elsewhere in this course works exactly the same way, since a linked Document is a genuine Document instance under the API, not a special limited-access wrapper',
          'This means, in principle, entire checks from earlier lessons (unplaced rooms, missing parameters) could also be run against a linked document — this lesson focuses on warnings specifically, but the same GetLinkDocument() access point generalizes further',
        ],
        formula: { label: 'Key Capability', text: 'GetLinkDocument() returns a real Document object for a loaded link — every Document-level query in this course (GetWarnings and beyond) works on it identically to the host document' },
      },
      {
        id: 's4', heading: 'Matching Link Types to Their Instances', level: 'h2',
        content: `To build one consolidated report per link (status plus warning count together), the RevitLinkType and RevitLinkInstance collections need to be connected — an instance references its type, not the other way around by default.`,
        code: {
          label: 'Linking the Two Collections',
          lines: [
            'report_rows = []',
            'for link_type in link_types:',
            '    status = link_type.GetLinkedFileStatus()',
            '    matching_instance = next(',
            '        (li for li in link_instances',
            '         if li.GetTypeId() == link_type.Id), None',
            '    )',
            '',
            '    warning_count = "-"',
            '    if matching_instance is not None:',
            '        linked_doc = matching_instance.GetLinkDocument()',
            '        if linked_doc is not None:',
            '            warning_count = len(linked_doc.GetWarnings())',
            '',
            '    report_rows.append([link_type.Name, str(status), str(warning_count)])',
          ],
        },
        items: [
          'li.GetTypeId() == link_type.Id matches each instance back to its defining type, the same Id-matching pattern used for Family Type/Instance relationships elsewhere in the Revit API',
          'Building one row per RevitLinkType (rather than per instance) keeps the report at the "one row per linked file" level most people actually want to see, even if a type happens to have multiple placed instances',
          'A "-" placeholder for warning_count clearly communicates "could not be checked" for an unloaded/missing link, distinct from an actual "0 warnings" result for a healthy, loaded link with a clean structural or MEP model behind it',
        ],
      },
      {
        id: 's5', heading: 'Printing the Consolidated Link Health Report', level: 'h2',
        content: `With status and warning count resolved per link, output.print_table() renders the whole DPC2025 link health picture as a single, scannable table.`,
        code: {
          label: 'The Consolidated Report',
          lines: [
            'output.print_md("# DPC2025 Linked Model Health Report")',
            'output.print_table(',
            '    table_data=report_rows,',
            '    columns=["Linked File", "Status", "Warning Count"],',
            '    title="Linked Models"',
            ')',
          ],
        },
        items: [
          'A single table with one row per linked file gives a project lead the full picture — which links are healthy, which are unloaded, which are missing, and how many warnings each loaded link carries — in one glance, without opening each link individually',
          'This report is especially useful run immediately before a coordination review meeting, catching an unloaded or missing consultant link before it silently invalidates the review',
          'Consider re-running this check at the start of every work session on DPC2025 as a lightweight habit, since a link\'s status can change any time a file is renamed, moved, or simply not reloaded after being unloaded for performance reasons',
        ],
        formula: { label: 'Report Value', text: 'One table answering "is every link present, loaded, and clean" removes the need to manually open the Manage Links dialog and separately audit each linked model\'s warnings' },
      },
      {
        id: 's6', heading: 'Handling Edge Cases Gracefully', level: 'h2',
        content: `A robust version of this checker anticipates the ways link data can be incomplete or surprising on a real, evolving project like DPC2025, rather than assuming every link will behave identically.`,
        items: [
          'A RevitLinkType with no matching RevitLinkInstance at all (the link type exists in the project but was never actually placed) should be reported with a clear "Not Placed" note rather than silently skipped or causing a lookup error',
          'Wrap the GetLinkDocument() and GetWarnings() calls in the per-link loop in a try/except so one unusual or corrupted link cannot halt the entire report before every other link has been checked',
          'Because this script only reads data (no Transaction is required anywhere in this tool), it is always safe to run at any time, the same read-only safety property as the COBie checker from the previous lesson',
        ],
      },
    ],
    takeaways: [
      'RevitLinkType represents the link definition and its load status (roughly like a Family Type), while RevitLinkInstance represents each placed occurrence of that link (roughly like a Family Instance).',
      'link_type.GetLinkedFileStatus() returns a LinkedFileStatus enum (Loaded, Unloaded, NotFound, and others) directly, distinguishing a deliberately unloaded link from one Revit simply cannot locate.',
      'link_instance.GetLinkDocument() returns a real Document object for a loaded link, which supports the same Document-level queries (like GetWarnings()) used against the host document elsewhere in this course.',
      'Matching a RevitLinkInstance back to its RevitLinkType via GetTypeId() == link_type.Id lets the report combine status and warning count into one row per linked file.',
      'output.print_table() renders one consolidated table of every link\'s file name, status, and warning count, replacing a manual walk through the Manage Links dialog and each linked model individually.',
      'This is a read-only tool requiring no Transaction, so it is safe to run at any time — ideally as a habitual check before any coordination review on DPC2025.',
    ],
    resource: { label: 'Linked Model Health Checker Build Guide', type: 'PDF' },
    quiz: { label: 'Linked Model Health Checker Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-14', title: 'Build a COBie Data Checker — Verify FM Fields are Populated' },
    next: { id: 'pyp-16', title: 'Build a Custom Ribbon Tab for the Office' },
  },

  // ============================================================
  // LESSON PYP-16 — Build a Custom Ribbon Tab for the Office
  // ============================================================
  {
    id: 'pyp-16', num: '16',
    title: 'Build a Custom Ribbon Tab for the Office',
    topic: 'Links & Ribbon', cat: 'intermediate', readTime: '11 min', free: false,
    desc: 'Organize every tool built in this course into a proper multi-panel custom ribbon tab using bundle.yaml files for clean titles, tooltips, and icons, so the toolkit reads as one coherent product.',
    intro: `Across this course you have built eight substantial tools for DPC2025 — a health dashboard, an issue tracker, a parameter audit, a workset manager, a level/grid checker, a COBie checker, and a linked model health checker, on top of everything from the foundational course before it. Left as individual scripts scattered across a generic pyRevit tab, they read as a pile of one-off utilities. This closing lesson organizes all of it into a proper custom ribbon tab — "DPC2025 Tools" — with logically grouped panels, clean bundle.yaml metadata for every button, and a consistent visual standard, so the finished result reads as one coherent office product rather than a collection of scripts.`,
    sections: [
      {
        id: 's1', heading: 'Designing the Tab and Panel Structure', level: 'h2',
        content: `Before touching any folder structure, decide how the tools should be grouped — a good ribbon layout groups by workflow purpose, not by the order the tools happened to be built in this course.`,
        code: {
          label: 'DPC2025 Tools Tab Layout',
          lines: [
            'DPC2025 Tools (tab)',
            '  |-- QA (panel)',
            '  |     Model Health Dashboard, Parameter Audit,',
            '  |     Level & Grid Checker, COBie Data Checker,',
            '  |     Linked Model Health Checker',
            '  |',
            '  |-- Sheets (panel)',
            '  |     Drawing Issue Tracker',
            '  |',
            '  |-- Data (panel)',
            '        Workset Manager',
          ],
        },
        items: [
          'Grouping by purpose (QA, Sheets, Data) rather than by build order means a new team member can find "the tool that checks something" without needing to know this course\'s lesson numbering at all',
          'A panel with a single button (like Sheets, holding only the Issue Tracker for now) is perfectly fine — panels exist to group related future tools too, not just to hold what exists today',
          'This structure is a starting point, not a fixed rule — as DPC2025\'s toolkit grows, panels can be split further (e.g., a dedicated "Links" panel once more linked-model tools exist) without disrupting the tools already in place',
        ],
      },
      {
        id: 's2', heading: 'The pyRevit Extension Folder Structure', level: 'h2',
        content: `pyRevit builds its ribbon directly from a nested folder structure on disk — the tab, panel, and button hierarchy in the UI corresponds exactly to a matching hierarchy of folders, each with a specific suffix.`,
        code: {
          label: 'Folder Hierarchy',
          lines: [
            'DPC2025 Tools.tab/',
            '  QA.panel/',
            '    Model Health Dashboard.pushbutton/',
            '      script.py',
            '      bundle.yaml',
            '      icon.png',
            '    Parameter Audit.pushbutton/',
            '      script.py',
            '      bundle.yaml',
            '      icon.png',
            '    ...',
            '  Sheets.panel/',
            '    Issue Tracker.pushbutton/',
            '      script.py',
            '      bundle.yaml',
            '      icon.png',
            '  Data.panel/',
            '    Workset Manager.pushbutton/',
            '      script.py',
            '      bundle.yaml',
            '      icon.png',
          ],
        },
        items: [
          'The .tab, .panel, and .pushbutton suffixes on folder names are how pyRevit recognizes each level of the hierarchy — a typo in the suffix (e.g., .panle) means that level is silently skipped rather than raising a clear error',
          'Each .pushbutton folder holds the actual script.py for that tool (the code built throughout this course), alongside its bundle.yaml metadata and an icon.png',
          'Moving an already-working script.py into this structure requires no changes to the script\'s own logic — only its location and the accompanying bundle.yaml need to be set up',
        ],
        formula: { label: 'Structure Rule', text: 'Tab > Panel > Pushbutton is expressed as nested folders with matching suffixes (.tab, .panel, .pushbutton) — pyRevit builds the ribbon directly from this folder tree, no separate registration step required' },
      },
      {
        id: 's3', heading: 'Writing a Clean bundle.yaml for Each Button', level: 'h2',
        content: `A bundle.yaml file gives each pushbutton a proper title, tooltip, and other metadata — without one, pyRevit falls back to using the raw folder name as the button label, which rarely reads well in a finished ribbon.`,
        code: {
          label: 'Example bundle.yaml — Model Health Dashboard',
          lines: [
            'title: Health',
            'tooltip: >',
            '  Run a consolidated model health check on DPC2025 —',
            '  warnings, unplaced rooms, and elements missing key',
            '  required parameters — printed as one dashboard report.',
            'author: DPC2025 BIM Team',
          ],
        },
        items: [
          'title is the short label actually shown on the ribbon button — keep it brief (one or two words) since ribbon space is limited, and rely on the tooltip for the fuller explanation',
          'tooltip is shown on hover and is the right place for a full sentence or two explaining exactly what the tool does and what it reports, similar to how each lesson\'s desc field in this course summarizes its tool',
          'author (and optionally a version or contact field) helps future maintainers know who to ask when a tool needs updating — a small but genuinely useful piece of metadata on a shared office toolkit',
        ],
      },
      {
        id: 's4', heading: 'Choosing Consistent Icons', level: 'h2',
        content: `A visually consistent icon set is one of the fastest ways to make a custom ribbon tab look like a deliberate product rather than a folder of scripts someone found time to wrap in a UI.`,
        items: [
          'Use a consistent icon.png size and style across every pushbutton (pyRevit expects a specific pixel size — check the current pyRevit documentation for the exact dimensions expected by the installed version) rather than mixing differently sized or styled icons',
          'A simple, consistent visual language — for example, one icon color family for QA tools and another for Data tools — reinforces the panel grouping visually, on top of the folder-based grouping already in place',
          'Where a distinctive icon is not readily available, a plain, legible glyph or initial-letter icon in the office\'s consistent style still reads far better than pyRevit\'s generic default icon repeated on every button',
        ],
        formula: { label: 'Visual Consistency Payoff', text: 'A shared icon size, style, and color language across every pushbutton is what makes a custom tab read as "the office toolkit" rather than "someone\'s personal scripts folder"' },
      },
      {
        id: 's5', heading: 'A Consistent Naming Standard Across the Whole Toolkit', level: 'h2',
        content: `Beyond bundle.yaml and icons, the naming choices themselves — tab, panel, and button names — should follow one deliberate standard applied uniformly, the same discipline this course has applied to ISO 19650 view/sheet naming throughout.`,
        items: [
          'Keep panel names short, generic category words (QA, Sheets, Data) rather than overly specific names that will not accommodate future tools added to the same panel',
          'Keep button titles as short action-oriented labels (Health, Audit, Worksets) rather than restating the full lesson title from this course on the ribbon itself, where space is limited',
          'Apply the same capitalization and spacing convention across every single bundle.yaml title field — a mix of "Health Dashboard," "auditTool," and "WORKSETS" across different buttons undermines the coherent, professional feel the whole exercise is meant to achieve',
        ],
      },
      {
        id: 's6', heading: 'Verifying the Finished Tab in Revit', level: 'h2',
        content: `Once every tool has been moved into the new folder structure with its bundle.yaml and icon in place, the whole tab needs a final verification pass inside Revit before considering it finished.`,
        items: [
          'Reload pyRevit (the pyRevit tab\'s own Reload button, or restarting Revit) to pick up the new extension folder structure and confirm the DPC2025 Tools tab appears with all three panels in the expected order',
          'Click through every single button at least once against DPC2025 to confirm each script still runs correctly from its new location — a moved script.py occasionally reveals a hard-coded relative path assumption that only surfaces once the file has actually moved',
          'Hover over every button to read its tooltip exactly as a new team member would, checking that the wording is clear without requiring them to have read this course first',
          'Treat this finished, organized tab as the actual deliverable of the whole course — a real internal product the DPC2025 office can hand to any team member with no explanation needed beyond what the ribbon itself already communicates',
        ],
        formula: { label: 'Final Standard', text: 'A finished custom tab should be usable by a team member who has never seen this course — clear tab/panel names, clear button titles, clear tooltips, and consistent icons doing all the explaining' },
      },
    ],
    takeaways: [
      'A custom ribbon tab should group tools by workflow purpose (QA, Sheets, Data) rather than by the order they happened to be built, so a new team member can find the right tool intuitively.',
      'pyRevit builds its ribbon directly from a nested folder structure — .tab, .panel, and .pushbutton suffixed folders — with no separate registration step beyond that folder hierarchy.',
      'Each pushbutton\'s bundle.yaml sets its title (short ribbon label) and tooltip (fuller hover explanation), replacing pyRevit\'s default fallback of using the raw folder name.',
      'A consistent icon size, style, and color language across every button is what makes a custom tab read as one coherent product rather than a folder of individually wrapped scripts.',
      'Panel and button naming should follow one deliberate, uniform standard — short generic panel names and short action-oriented button titles — applied identically across every bundle.yaml.',
      'The finished tab should be verified by reloading pyRevit, clicking every button against DPC2025, and reading every tooltip as a new team member would, with no prior explanation needed.',
    ],
    resource: { label: 'Custom Ribbon Tab Build Guide', type: 'PDF' },
    quiz: { label: 'Custom Ribbon Tab Quiz', questions: 10, time: '5 min' },
    prev: { id: 'pyp-15', title: 'Build a Linked Model Health Checker — Status, Warnings & Missing Links' },
    next: { id: 'pyp-17', title: 'Build a Full ISO 19650 Naming Validator' },
  },

];
