// ============================================================
// PYREVIT — LESSONS py-17 through py-24 (ADVANCED)
// Sections: Production Tools | Office Tools | Deployment | Capstone
// File: lib/pyrevitLessonsContent/pyrevitLessons_17_24.js
// Index: lib/pyrevitLessonsData.js
// ============================================================

export const lessons_17_24 = [

  // ============================================================
  // LESSON PY-17 — Model Checker Tool
  // ============================================================
  {
    id: 'py-17', num: '17',
    title: 'Building a Model Checker Tool — Automated QA in One Click',
    topic: 'Production Tools', cat: 'advanced', readTime: '11 min', free: false,
    desc: 'Build a pyRevit pushbutton that sweeps the model for unenclosed rooms, missing parameters, and duplicate marks, then prints a formatted report.',
    intro: `Every office has a QA checklist that someone is supposed to run before a model goes out the door — and every office has a project where it quietly did not happen because there was no time. A pyRevit pushbutton removes that excuse: wire up a single button that runs a full QA sweep against the DPC2025 model and prints a readable report in seconds, with no dialogs to click through and no Excel file to open afterward. This lesson builds that tool from the ground up, using FilteredElementCollector queries you already know and pyRevit's markdown-aware output window to make the results genuinely readable.`,
    sections: [
      {
        id: 's1', heading: 'Scoping the QA Sweep', level: 'h2',
        content: `Before writing any code, a model checker needs a fixed, agreed list of what it actually checks — an unscoped "check everything" tool tends to check nothing well.`,
        items: [
          'For DPC2025, the office standard defines three checks for this tool: unenclosed rooms, elements missing a required parameter, and duplicate Mark values within a category',
          'Each check should be a small, self-contained function that returns a list of problem elements — keeping checks independent makes the tool easy to extend later',
          'Design the button to run all three checks in a single click and present one combined report, rather than three separate buttons a user has to remember to run',
          'Keep the checklist itself documented at the top of the script as a comment, so the tool\'s scope is visible to the next person who edits it',
        ],
        formula: { label: 'Tool Scope', text: 'Unenclosed Rooms + Missing Required Parameters + Duplicate Marks = one QA sweep, one button, one report' },
      },
      {
        id: 's2', heading: 'Checking for Unenclosed Rooms', level: 'h2',
        content: `An unenclosed (or unplaced) room is one of the most common and most consequential modelling errors — it silently breaks area schedules and room-based tagging. In the Revit API, an unplaced or unenclosed room reports an Area of zero.`,
        code: {
          label: 'Unenclosed Room Check',
          lines: [
            'rooms = DB.FilteredElementCollector(doc) \\',
            '    .OfCategory(DB.BuiltInCategory.OST_Rooms) \\',
            '    .WhereElementIsNotElementType() \\',
            '    .ToElements()',
            '',
            'bad_rooms = []',
            'for room in rooms:',
            '    if room.Area <= 0:',
            '        bad_rooms.append(room)',
          ],
        },
        items: [
          'Area <= 0 catches both genuinely unplaced rooms and rooms whose boundary failed to close (an unenclosed room reports zero area exactly like an unplaced one)',
          'Do not filter by Room.Location being None alone — a room can have a location point but still fail to compute an enclosed boundary',
        ],
      },
      {
        id: 's3', heading: 'Checking for Missing Required Parameters', level: 'h2',
        content: `The second check walks a category and flags any instance where an office-required parameter is empty, null, or missing entirely.`,
        code: {
          label: 'Missing Parameter Check',
          lines: [
            'def check_required_param(category, param_name):',
            '    collector = DB.FilteredElementCollector(doc) \\',
            '        .OfCategory(category) \\',
            '        .WhereElementIsNotElementType() \\',
            '        .ToElements()',
            '',
            '    missing = []',
            '    for el in collector:',
            '        param = el.LookupParameter(param_name)',
            '        if param is None or not param.HasValue or param.AsString() == "":',
            '            missing.append(el)',
            '    return missing',
            '',
            'missing_fire_rating = check_required_param(',
            '    DB.BuiltInCategory.OST_Doors, "Fire Rating")',
          ],
        },
        items: [
          'Writing this as a reusable function lets the tool check several category/parameter pairs (Doors/Fire Rating, Walls/Fire Rating, Rooms/Department) without duplicating the loop each time',
          'param.HasValue guards against a parameter that exists but has never been set, which LookupParameter alone does not distinguish from a genuinely populated empty string in every parameter storage type',
        ],
      },
      {
        id: 's4', heading: 'Checking for Duplicate Marks', level: 'h2',
        content: `Duplicate Mark values within a category are a frequent source of schedule confusion and tagging ambiguity — this check groups elements by Mark and flags any value shared by more than one element.`,
        code: {
          label: 'Duplicate Mark Check',
          lines: [
            'from collections import defaultdict',
            '',
            'def check_duplicate_marks(category):',
            '    collector = DB.FilteredElementCollector(doc) \\',
            '        .OfCategory(category) \\',
            '        .WhereElementIsNotElementType() \\',
            '        .ToElements()',
            '',
            '    marks = defaultdict(list)',
            '    for el in collector:',
            '        param = el.LookupParameter("Mark")',
            '        if param and param.HasValue:',
            '            marks[param.AsString()].append(el)',
            '',
            '    return {m: els for m, els in marks.items() if len(els) > 1}',
          ],
        },
        items: [
          'Using a dictionary keyed by Mark value makes it trivial to report exactly which elements share a duplicate, not just that a duplicate exists somewhere',
          'Run this per-category (Doors, Windows, Furniture) rather than across the whole model, since Mark uniqueness is typically only meaningful within a single category',
        ],
      },
      {
        id: 's5', heading: 'Printing a Markdown Report with output.print_md()', level: 'h2',
        content: `Unlike a plain console, the pyRevit output window renders Markdown, which makes a QA report dramatically more readable than raw print statements — headings, bold text, and bullet lists all render properly.`,
        code: {
          label: 'Markdown Report Header',
          lines: [
            'from pyrevit import script',
            '',
            'output = script.get_output()',
            '',
            'output.print_md("# DPC2025 Model QA Report")',
            'output.print_md("**Project:** DPC2025 Capstone Model")',
            'output.print_md("---")',
            '',
            'output.print_md("## 1. Unenclosed Rooms")',
            'if bad_rooms:',
            '    output.print_md(',
            '        "Found **{}** unenclosed or unplaced rooms.".format(len(bad_rooms)))',
            'else:',
            '    output.print_md("No unenclosed rooms found.")',
          ],
        },
        items: [
          'print_md() accepts standard Markdown syntax — hash headings, double-asterisk bold, and hyphen bullet lists all render as formatted text, not literal characters',
          'Use section headings for each check (Unenclosed Rooms, Missing Parameters, Duplicate Marks) so a long combined report stays scannable',
          'A short summary line at the very top of the report (pass/fail counts per check) lets a reviewer judge overall model health before reading every detail',
        ],
      },
      {
        id: 's6', heading: 'Printing Tabular Results with output.print_table()', level: 'h2',
        content: `For listing the actual failing elements, pyRevit's output.print_table() renders a proper HTML-like table in the output window — far more readable than a wall of printed Element IDs.`,
        code: {
          label: 'Tabular Report Rows',
          lines: [
            'rows = []',
            'for room in bad_rooms:',
            '    rows.append([',
            '        output.linkify(room.Id),',
            '        room.Number,',
            '        room.Name,',
            '        str(room.Area),',
            '    ])',
            '',
            'output.print_table(',
            '    table_data=rows,',
            '    title="Unenclosed Rooms",',
            '    columns=["Element", "Number", "Name", "Area"])',
          ],
        },
        items: [
          'output.linkify(element_id) produces a clickable link in the output window that selects the element back in the active Revit view when clicked — invaluable for a reviewer acting on the report',
          'Build one table per check, using the same rows/columns pattern for missing-parameter and duplicate-mark results',
          'Keep table columns minimal and consistent (Element, identifying field, the value that failed) so the eye can scan quickly down a long list',
        ],
      },
      {
        id: 's7', heading: 'Assembling the Pushbutton', level: 'h2',
        content: `With the three checks and the report-printing pattern in place, the whole tool becomes a single script.py wired to one pushbutton in the extension\'s ribbon panel, following the extension structure from the previous lesson.`,
        items: [
          'Place the checker as its own script.py inside a "QA" panel of the office extension, with a clear button image and tooltip describing exactly what it checks',
          'Run all three checks first, collecting results into variables, then print the full report in one pass at the end — this avoids a half-printed report if a later check happens to throw an exception',
          'Wrap each check call in a try/except so one failing check does not prevent the rest of the report from printing',
          'Keep the tool read-only — a model checker should never modify the model itself; it reports problems for a human to fix, keeping its blast radius to zero',
        ],
        formula: { label: 'Design Rule', text: 'A QA tool that also writes to the model is two tools pretending to be one — keep checking and fixing separate' },
      },
    ],
    takeaways: [
      'A model checker tool should run a fixed, documented set of checks in one click rather than growing into an unscoped "check everything" script.',
      'Unenclosed or unplaced rooms are reliably detected by testing Room.Area <= 0, since both conditions report zero area.',
      'A reusable check_required_param() function lets one tool audit multiple category/parameter pairs without duplicating the collector loop.',
      'Grouping elements by Mark value in a dictionary is a simple, effective way to surface duplicate Mark values within a category.',
      'output.print_md() renders real Markdown in the pyRevit output window — headings, bold text, and bullets — unlike a plain console.',
      'output.print_table() renders readable HTML-like tables, and output.linkify() makes rows clickable to select the corresponding element in the model.',
    ],
    resource: { label: 'PyRevit Model Checker Build Guide', type: 'PDF' },
    quiz: { label: 'Model Checker Tool Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-16', title: 'Organising Scripts into a Custom PyRevit Extension' },
    next: { id: 'py-18', title: 'Automating Drawing Sheets & Title Block Data' },
  },

  // ============================================================
  // LESSON PY-18 — Sheets & Titleblock Automation
  // ============================================================
  {
    id: 'py-18', num: '18',
    title: 'Automating Drawing Sheets & Title Block Data',
    topic: 'Production Tools', cat: 'advanced', readTime: '10 min', free: false,
    desc: 'Batch-write titleblock parameter values across every sheet in the model in a single one-click, transaction-wrapped tool.',
    intro: `Titleblock data entry is exactly the kind of task pyRevit exists to eliminate — a project name correction, a new "Checked By" initials, or an updated issue date should never require opening every sheet in a 200-sheet set by hand. This lesson builds a pushbutton that collects every sheet in the DPC2025 model and writes titleblock parameter values across all of them in a single transaction, turning a task that used to eat an afternoon into a five-second click.`,
    sections: [
      {
        id: 's1', heading: 'Two Ways to Reach Titleblock Data', level: 'h2',
        content: `Titleblock information can be reached two ways in the Revit API — through the titleblock family instances themselves, or through the ViewSheet elements they are placed on. Each has a different practical use.`,
        items: [
          'Collecting OST_TitleBlocks gets the titleblock family instances directly, useful when a parameter lives on the titleblock family itself (e.g., a shared parameter placed on the titleblock type)',
          'Collecting ViewSheet elements gets the sheets themselves, useful for sheet-level parameters like Sheet Number, Sheet Name, and any project parameter bound to the Sheets category',
          'Some values (like a project name or drawn-by field) may be duplicated on both — decide which one is the authoritative source before writing a bulk-update script, to avoid two tools disagreeing with each other',
        ],
        formula: { label: 'Choosing the Source', text: 'Titleblock family instance = titleblock-family-level data | ViewSheet element = sheet-level data' },
      },
      {
        id: 's2', heading: 'Collecting Every Titleblock Instance', level: 'h2',
        content: `The titleblock family instances placed on sheets are collected like any other category, filtered to instances rather than types.`,
        code: {
          label: 'Collecting Titleblocks',
          lines: [
            'titleblocks = DB.FilteredElementCollector(doc) \\',
            '    .OfCategory(DB.BuiltInCategory.OST_TitleBlocks) \\',
            '    .WhereElementIsNotElementType() \\',
            '    .ToElements()',
            '',
            'print("Found {} titleblock instances".format(len(titleblocks)))',
          ],
        },
        items: [
          'Each returned element is one titleblock instance placed on one sheet — a model with 150 sheets returns 150 titleblock instances (assuming one titleblock per sheet)',
          'A titleblock instance carries its own instance parameters (Drawn By, Checked By, Date) separately from the ViewSheet it sits on, even though they visually sit on the same piece of paper',
        ],
      },
      {
        id: 's3', heading: 'Collecting Every ViewSheet', level: 'h2',
        content: `Where the target parameter lives at the sheet level instead, collecting ViewSheet elements directly is the more direct route.`,
        code: {
          label: 'Collecting Sheets',
          lines: [
            'sheets = DB.FilteredElementCollector(doc) \\',
            '    .OfClass(DB.ViewSheet) \\',
            '    .ToElements()',
            '',
            'for sheet in sheets:',
            '    print("{} - {}".format(sheet.SheetNumber, sheet.Name))',
          ],
        },
        items: [
          'ViewSheet is a class filter (OfClass), not a category filter — sheets are not filtered with OfCategory the way most model elements are',
          'sheet.SheetNumber and sheet.Name are exposed as direct properties on ViewSheet, in addition to being readable/writable as ordinary parameters',
        ],
      },
      {
        id: 's4', heading: 'Writing Bulk Values in a Single Transaction', level: 'h2',
        content: `Writing to 150 sheets one at a time inside 150 separate transactions is both slow and unnecessary — pyRevit wraps the entire bulk update in one Transaction so it commits (or rolls back) as a single atomic operation.`,
        code: {
          label: 'Bulk Titleblock Update',
          lines: [
            'from pyrevit import revit, DB',
            '',
            'doc = revit.doc',
            '',
            'project_name = "DPC2025 Capstone"',
            'checked_by = "D. Park"',
            'issue_date = "2026-07-02"',
            '',
            'titleblocks = DB.FilteredElementCollector(doc) \\',
            '    .OfCategory(DB.BuiltInCategory.OST_TitleBlocks) \\',
            '    .WhereElementIsNotElementType() \\',
            '    .ToElements()',
            '',
            'with revit.Transaction("Update Titleblock Data"):',
            '    for tb in titleblocks:',
            '        name_p = tb.LookupParameter("Project Name")',
            '        checked_p = tb.LookupParameter("Checked By")',
            '        date_p = tb.LookupParameter("Date")',
            '',
            '        if name_p and not name_p.IsReadOnly:',
            '            name_p.Set(project_name)',
            '        if checked_p and not checked_p.IsReadOnly:',
            '            checked_p.Set(checked_by)',
            '        if date_p and not date_p.IsReadOnly:',
            '            date_p.Set(issue_date)',
          ],
        },
        items: [
          'pyRevit\'s revit.Transaction() context manager is a thin, convenient wrapper around the same Transaction start/commit pattern used in raw Revit API scripting — no manual try/commit/rollback boilerplate needed',
          'One transaction for the whole loop means one undo step in Revit if the update needs to be reversed, rather than 150 individual undo steps',
          'Always check IsReadOnly before calling Set() — some titleblock fields are calculated (like Sheet Number auto-derived fields) and cannot be written directly',
        ],
      },
      {
        id: 's5', heading: 'Prompting for Values Instead of Hardcoding', level: 'h2',
        content: `Hardcoding "D. Park" and today\'s date directly into the script means editing the script itself every time it is used — a small form makes the tool reusable without touching code.`,
        code: {
          label: 'Prompting with forms.ask_for_string',
          lines: [
            'from pyrevit import forms',
            '',
            'checked_by = forms.ask_for_string(',
            '    default="", prompt="Enter Checked By initials", title="Titleblock Update")',
            '',
            'if not checked_by:',
            '    script.exit()',
          ],
        },
        items: [
          'forms.ask_for_string() opens a simple modal text input, returning the entered value (or None if the user cancels)',
          'Always check for a None/empty return and exit gracefully — a user cancelling the dialog should not proceed to overwrite every sheet with a blank value',
          'This same prompting pattern is expanded into a full reusable form-driven tool in the next lesson\'s Parameter Manager',
        ],
      },
      {
        id: 's6', heading: 'Confirming the Update Before Running', level: 'h2',
        content: `Because this tool touches every sheet in the model in one pass, a brief confirmation step protects against running it by accident on the wrong model or with the wrong values.`,
        items: [
          'Use forms.alert() with yes/no options to show the values about to be written and require explicit confirmation before the transaction starts',
          'Print a short before/after summary to the output window after the transaction commits, so the user can confirm the update took effect without opening every sheet manually',
          'Test the tool on a duplicated test model first when adjusting the parameter names or logic, exactly as recommended for any bulk-write script',
        ],
        formula: { label: 'Safety Pattern', text: 'Prompt for values → confirm before writing → single transaction → print a summary after' },
      },
    ],
    takeaways: [
      'Titleblock data can be reached via OST_TitleBlocks (family instance data) or via DB.ViewSheet class collection (sheet-level data) — pick the authoritative source before writing a script.',
      'DB.FilteredElementCollector(doc).OfClass(DB.ViewSheet) collects every sheet in the model; sheets are filtered by class, not category.',
      'Wrapping the entire bulk update loop in a single revit.Transaction() commits (or rolls back) as one atomic operation and produces one undo step.',
      'Always check param.IsReadOnly before calling Set() — some titleblock fields are calculated and cannot be written directly.',
      'forms.ask_for_string() replaces hardcoded values with a simple prompt, making the tool reusable without editing the script each time.',
      'A confirmation step (forms.alert) before the transaction and a printed summary after protects against accidental bulk writes to the wrong values or the wrong model.',
    ],
    resource: { label: 'Titleblock Automation Reference', type: 'PDF' },
    quiz: { label: 'Sheet & Titleblock Automation Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-17', title: 'Building a Model Checker Tool — Automated QA in One Click' },
    next: { id: 'py-19', title: 'Building a Parameter Manager Tool for the Office' },
  },

  // ============================================================
  // LESSON PY-19 — Parameter Manager Tool
  // ============================================================
  {
    id: 'py-19', num: '19',
    title: 'Building a Parameter Manager Tool for the Office',
    topic: 'Office Tools', cat: 'advanced', readTime: '11 min', free: false,
    desc: 'Build a reusable, form-driven parameter editor that lets any user pick a category, a parameter, and a new value at runtime.',
    intro: `Every office ends up writing dozens of tiny scripts that each hardcode one category and one parameter — "Set Fire Rating on Doors," "Set Department on Rooms" — when really they are all the same tool with different inputs typed in. This lesson builds that one general-purpose tool instead: a Parameter Manager that lets whoever is running it choose the category, choose the parameter, and enter the new value, all through pyRevit forms, then apply it across a filtered selection in the DPC2025 model. One script replaces an entire drawer of single-purpose ones.`,
    sections: [
      {
        id: 's1', heading: 'Designing for Reuse, Not for One Task', level: 'h2',
        content: `The core design decision in this lesson is refusing to hardcode anything that the user could reasonably choose at runtime instead.`,
        items: [
          'Category, parameter name, and new value should all be runtime choices, not values typed into the script',
          'The only thing that should be hardcoded is the list of categories the tool is allowed to touch — an intentional safety boundary, not a limitation of the API',
          'A tool built this way survives office standard changes automatically — no one needs to edit code just because a new required parameter was added to the BEP',
        ],
        formula: { label: 'Reuse Principle', text: 'Hardcode only the safety boundary (allowed categories) — let the user choose everything else' },
      },
      {
        id: 's2', heading: 'Step 1 — Picking a Category with forms.SelectFromList', level: 'h2',
        content: `pyRevit\'s forms.SelectFromList presents a simple searchable picker, ideal for choosing one item from a known, bounded list.`,
        code: {
          label: 'Category Picker',
          lines: [
            'from pyrevit import forms, DB',
            '',
            'ALLOWED_CATEGORIES = {',
            '    "Doors": DB.BuiltInCategory.OST_Doors,',
            '    "Windows": DB.BuiltInCategory.OST_Windows,',
            '    "Rooms": DB.BuiltInCategory.OST_Rooms,',
            '    "Walls": DB.BuiltInCategory.OST_Walls,',
            '}',
            '',
            'category_name = forms.SelectFromList.show(',
            '    sorted(ALLOWED_CATEGORIES.keys()),',
            '    title="Select a Category",',
            '    button_name="Next")',
            '',
            'if not category_name:',
            '    script.exit()',
            '',
            'bic = ALLOWED_CATEGORIES[category_name]',
          ],
        },
        items: [
          'Keeping ALLOWED_CATEGORIES as an explicit dictionary is the safety boundary mentioned above — it prevents a user from accidentally targeting a category the tool was never tested against',
          'forms.SelectFromList.show() returns None if the user cancels — always check for this before proceeding',
        ],
      },
      {
        id: 's3', heading: 'Step 2 — Picking a Parameter from the Category', level: 'h2',
        content: `Once a category is chosen, the tool discovers which parameters actually exist on elements of that category, rather than assuming a fixed list.`,
        code: {
          label: 'Discovering Available Parameters',
          lines: [
            'elements = DB.FilteredElementCollector(doc) \\',
            '    .OfCategory(bic) \\',
            '    .WhereElementIsNotElementType() \\',
            '    .ToElements()',
            '',
            'if not elements:',
            '    forms.alert("No elements found in that category.", exitscript=True)',
            '',
            'sample = elements[0]',
            'param_names = sorted({p.Definition.Name for p in sample.Parameters',
            '                      if not p.IsReadOnly})',
            '',
            'param_name = forms.SelectFromList.show(',
            '    param_names, title="Select a Parameter", button_name="Next")',
            '',
            'if not param_name:',
            '    script.exit()',
          ],
        },
        items: [
          'Sampling the first element\'s Parameters collection gives a realistic list of writable parameters for that category, instead of hardcoding parameter names that may not apply to every project',
          'Filtering to not p.IsReadOnly upfront means the picker never even offers a parameter the tool could not write to anyway',
        ],
      },
      {
        id: 's4', heading: 'Step 3 — Entering the New Value', level: 'h2',
        content: `With category and parameter chosen, the tool prompts for the value to apply, using the simple string prompt introduced in the previous lesson.`,
        code: {
          label: 'Value Entry',
          lines: [
            'new_value = forms.ask_for_string(',
            '    default="",',
            '    prompt="Enter new value for \'{}\'".format(param_name),',
            '    title="Parameter Manager")',
            '',
            'if new_value is None:',
            '    script.exit()',
          ],
        },
        items: [
          'An empty string ("") is a valid, deliberate choice (clearing a value) and should be allowed through; only a cancelled dialog (None) should stop the script',
          'For parameters that are genuinely numeric, consider a follow-up type check (try converting to float) before writing, so a typo does not silently write bad data into a number field',
        ],
      },
      {
        id: 's5', heading: 'Step 4 — Choosing the Target Scope', level: 'h2',
        content: `Applying the new value to every element of the category model-wide is not always what the user wants — the tool should offer a choice between the current selection and the full category.`,
        code: {
          label: 'Scope Choice',
          lines: [
            'scope = forms.CommandSwitchWindow.show(',
            '    ["Current Selection", "All Elements in Category"],',
            '    message="Apply to which elements?")',
            '',
            'if scope == "Current Selection":',
            '    targets = [el for el in revit.get_selection() if el.Category and',
            '               el.Category.Id == DB.ElementId(bic)]',
            'else:',
            '    targets = elements',
          ],
        },
        items: [
          'forms.CommandSwitchWindow.show() presents large, clearly-labelled buttons — a good fit for a small, mutually exclusive choice like this one',
          'Filtering the current selection down to only elements matching the chosen category avoids applying the value to something the user selected by accident from a different category',
        ],
      },
      {
        id: 's6', heading: 'Step 5 — Applying the Value in a Transaction', level: 'h2',
        content: `With category, parameter, value, and scope all resolved, the final step is the familiar transaction-wrapped write loop.`,
        code: {
          label: 'Applying the Update',
          lines: [
            'updated = 0',
            'with revit.Transaction("Parameter Manager Bulk Update"):',
            '    for el in targets:',
            '        param = el.LookupParameter(param_name)',
            '        if param and not param.IsReadOnly:',
            '            param.Set(new_value)',
            '            updated += 1',
            '',
            'forms.alert("Updated {} of {} elements.".format(updated, len(targets)))',
          ],
        },
        items: [
          'Counting successful updates against the total target count gives an honest completion summary — some elements may not carry the chosen parameter at all despite matching the category',
          'This is the same LookupParameter/IsReadOnly/Set pattern used throughout the course — the value of this lesson is entirely in the reusable form-driven front end wrapped around it',
        ],
      },
      {
        id: 's7', heading: 'Guardrails for a General-Purpose Tool', level: 'h2',
        content: `A tool this flexible is also a tool that can do more damage than a single hardcoded script if used carelessly — a few guardrails keep it office-safe.`,
        items: [
          'Keep ALLOWED_CATEGORIES deliberately short and reviewed — add a category only after confirming the tool behaves correctly against it',
          'Always show a final confirmation (forms.alert with yes/no) summarizing category, parameter, new value, and target count before the transaction runs',
          'Log each run\'s category/parameter/value/count to a simple text file or the pyRevit output window so a bulk change can be traced back after the fact if something looks wrong later',
          'Document the tool\'s existence and purpose in the office wiki or extension readme so it is used deliberately, not undiscovered or, worse, misunderstood',
        ],
      },
    ],
    takeaways: [
      'A single Parameter Manager tool driven by forms.SelectFromList and forms.ask_for_string replaces dozens of single-purpose, hardcoded parameter scripts.',
      'Sampling an element\'s Parameters collection at runtime builds an accurate, category-specific parameter picker instead of a hardcoded, possibly outdated list.',
      'forms.CommandSwitchWindow.show() is well suited to a small, mutually exclusive scope choice like "Current Selection" vs "All Elements in Category."',
      'An explicit ALLOWED_CATEGORIES boundary keeps a flexible, general-purpose tool from being pointed at untested categories.',
      'A final confirmation step summarizing category, parameter, value, and target count before the transaction protects against costly bulk-write mistakes.',
      'Logging each run\'s inputs and result count makes a general-purpose bulk-edit tool auditable after the fact.',
    ],
    resource: { label: 'Parameter Manager Tool Blueprint', type: 'PDF' },
    quiz: { label: 'Parameter Manager Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-18', title: 'Automating Drawing Sheets & Title Block Data' },
    next: { id: 'py-20', title: 'PyRevit & Shared Parameters — Bulk Assignment & Auditing' },
  },

  // ============================================================
  // LESSON PY-20 — Shared Parameters
  // ============================================================
  {
    id: 'py-20', num: '20',
    title: 'PyRevit & Shared Parameters — Bulk Assignment & Auditing',
    topic: 'Office Tools', cat: 'advanced', readTime: '11 min', free: false,
    desc: 'Programmatically bind shared parameters to categories and audit which categories are missing an expected binding, instead of using the Manage tab dialog every time.',
    intro: `Binding a shared parameter to a category through the Manage tab dialog is fine for a one-off — but the DPC2025 office standard defines a dozen shared parameters that must be bound to a specific set of categories on every new project template, and clicking through that dialog every time is slow and error-prone. This lesson scripts the whole process: opening the shared parameter file programmatically, binding parameters to categories in bulk, and auditing an existing model to find any category that is silently missing an expected binding.`,
    sections: [
      {
        id: 's1', heading: 'Opening the Shared Parameter File Programmatically', level: 'h2',
        content: `Every shared parameter originates from a shared parameter text file — the same file referenced by the Manage tab dialog can be opened directly through the API using the Application object.`,
        code: {
          label: 'Opening the Shared Parameter File',
          lines: [
            'app = doc.Application',
            'app.SharedParametersFilename = r"C:\\OfficeStandards\\DPC2025_SharedParams.txt"',
            '',
            'shared_param_file = app.OpenSharedParameterFile()',
            '',
            'if shared_param_file is None:',
            '    forms.alert("Could not open the shared parameter file.", exitscript=True)',
          ],
        },
        items: [
          'app.SharedParametersFilename must point at a valid, accessible shared parameter text file — setting this path is the scripted equivalent of Manage tab → Shared Parameters → Browse',
          'OpenSharedParameterFile() returns None (rather than raising an exception) if the file cannot be found or opened, so always check for None before proceeding',
          'Keep the office shared parameter file at one canonical network path so this script — and every team member\'s manual Manage tab setting — stay in sync',
        ],
      },
      {
        id: 's2', heading: 'Finding a Parameter Definition Inside Groups', level: 'h2',
        content: `A shared parameter file organizes its parameters into named Groups — the API needs to search within a group to retrieve the specific ExternalDefinition for a parameter by name.`,
        code: {
          label: 'Retrieving a Parameter Definition',
          lines: [
            'def find_definition(shared_param_file, group_name, param_name):',
            '    group = shared_param_file.Groups.get_Item(group_name)',
            '    if group is None:',
            '        return None',
            '    for definition in group.Definitions:',
            '        if definition.Name == param_name:',
            '            return definition',
            '    return None',
            '',
            'fire_rating_def = find_definition(',
            '    shared_param_file, "DPC2025 Parameters", "Fire Rating Verified")',
          ],
        },
        items: [
          'Definitions.get_Item() (or a search loop, since not every API version exposes lookup-by-name directly) retrieves the ExternalDefinition object needed for binding',
          'A definition found this way is only a reference to the parameter\'s definition — it is not yet bound to any category until an explicit binding step runs',
        ],
      },
      {
        id: 's3', heading: 'Binding a Parameter to Categories', level: 'h2',
        content: `With a definition in hand, binding it to one or more categories requires building a CategorySet and an InstanceBinding (or TypeBinding), then registering it through the document\'s Binding Map — all inside a transaction.`,
        code: {
          label: 'Binding a Shared Parameter',
          lines: [
            'categories = app.Create.NewCategorySet()',
            'categories.Insert(doc.Settings.Categories.get_Item(',
            '    DB.BuiltInCategory.OST_Doors))',
            'categories.Insert(doc.Settings.Categories.get_Item(',
            '    DB.BuiltInCategory.OST_Windows))',
            '',
            'binding = app.Create.NewInstanceBinding(categories)',
            '',
            'with revit.Transaction("Bind Shared Parameter"):',
            '    doc.ParameterBindings.Insert(',
            '        fire_rating_def, binding, DB.BuiltInParameterGroup.PG_DATA)',
          ],
        },
        items: [
          'NewInstanceBinding binds the parameter to instances of the given categories; NewTypeBinding binds it to types instead — choose based on whether the parameter should vary per-instance or per-type',
          'ParameterBindings.Insert() both creates a new binding and registers it against the document in one call — no separate "apply" step is needed once inside the transaction',
          'Binding a parameter that is already bound to some categories generally requires Insert with the existing binding\'s updated CategorySet, or ReInsert for updating an existing binding — verify current behaviour against the Revit API version in use',
        ],
      },
      {
        id: 's4', heading: 'Batch-Binding a List of Parameter/Category Pairs', level: 'h2',
        content: `The real time saving comes from driving this process off a simple data structure — a list of (parameter name, group, categories) tuples — rather than repeating the binding code by hand for each one.`,
        code: {
          label: 'Batch Binding Table',
          lines: [
            'BINDINGS = [',
            '    ("Fire Rating Verified", "DPC2025 Parameters",',
            '     [DB.BuiltInCategory.OST_Doors, DB.BuiltInCategory.OST_Walls]),',
            '    ("QA Reviewed", "DPC2025 Parameters",',
            '     [DB.BuiltInCategory.OST_Rooms, DB.BuiltInCategory.OST_Doors]),',
            ']',
            '',
            'with revit.Transaction("Batch Bind Shared Parameters"):',
            '    for param_name, group_name, bics in BINDINGS:',
            '        definition = find_definition(shared_param_file, group_name, param_name)',
            '        if definition is None:',
            '            continue',
            '        cat_set = app.Create.NewCategorySet()',
            '        for bic in bics:',
            '            cat_set.Insert(doc.Settings.Categories.get_Item(bic))',
            '        binding = app.Create.NewInstanceBinding(cat_set)',
            '        doc.ParameterBindings.Insert(',
            '            definition, binding, DB.BuiltInParameterGroup.PG_DATA)',
          ],
        },
        items: [
          'This table-driven pattern means a new office-standard parameter only requires adding one line to BINDINGS, not writing new binding code',
          'Wrapping the whole batch in one transaction commits every binding together or none at all if something fails partway through',
        ],
      },
      {
        id: 's5', heading: 'Auditing Existing Bindings', level: 'h2',
        content: `A companion audit script checks an existing model against the same BINDINGS table to find any category that is missing an expected parameter — catching drift on older projects that were never re-run against the current standard.`,
        code: {
          label: 'Binding Audit Script',
          lines: [
            'binding_map = doc.ParameterBindings',
            'existing_names = set()',
            'it = binding_map.ForwardIterator()',
            'it.Reset()',
            'while it.MoveNext():',
            '    existing_names.add(it.Key.Name)',
            '',
            'missing = []',
            'for param_name, group_name, bics in BINDINGS:',
            '    if param_name not in existing_names:',
            '        missing.append(param_name)',
            '',
            'if missing:',
            '    output.print_md("## Missing Shared Parameter Bindings")',
            '    for name in missing:',
            '        output.print_md("- **{}** is not bound in this model".format(name))',
            'else:',
            '    output.print_md("All expected shared parameters are bound.")',
          ],
        },
        items: [
          'ParameterBindings.ForwardIterator() is the standard way to walk every existing binding in the document, since ParameterBindings does not support simple indexing or "in" checks directly',
          'This audit only confirms a parameter of that name is bound somewhere — a more thorough version would also confirm it is bound to every expected category, not merely bound at all',
          'Run the audit script on any DPC2025 model received from a consultant or an older project phase to catch bindings that quietly never got applied',
        ],
      },
      {
        id: 's6', heading: 'Why Script This Instead of Using the Manage Tab', level: 'h2',
        content: `The Manage tab dialog is not wrong for a one-off adjustment, but it does not scale to office-wide consistency the way a script does.`,
        items: [
          'A script applied identically across every new project template guarantees the same parameters land on the same categories every time, with no manual dialog steps to forget',
          'The BINDINGS table becomes the single source of truth for what the office standard actually requires — readable by any team member, not just discoverable by clicking through the Manage tab on a finished project',
          'Auditing by hand (opening the Manage tab and reading the binding list category by category) does not scale past a handful of parameters; the scripted audit does',
        ],
        formula: { label: 'Scaling Rule', text: 'One dialog click scales to one project; one script scales to every project the office ever touches' },
      },
    ],
    takeaways: [
      'app.OpenSharedParameterFile() opens the shared parameter text file programmatically, the scripted equivalent of the Manage tab\'s Browse dialog.',
      'A parameter\'s ExternalDefinition is retrieved by searching Groups and Definitions inside the shared parameter file by name.',
      'Binding requires a CategorySet, an InstanceBinding or TypeBinding, and doc.ParameterBindings.Insert() — all wrapped in a transaction.',
      'Driving bindings off a BINDINGS table of (parameter, group, categories) tuples makes adding a new office-standard parameter a one-line change, not new code.',
      'ParameterBindings.ForwardIterator() walks existing bindings in a document, enabling an audit script that flags any expected parameter missing from a model.',
      'Scripting shared parameter binding guarantees office-wide consistency across every project template in a way that manual Manage tab clicks cannot.',
    ],
    resource: { label: 'Shared Parameter Automation Guide', type: 'PDF' },
    quiz: { label: 'Shared Parameters Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-19', title: 'Building a Parameter Manager Tool for the Office' },
    next: { id: 'py-21', title: 'Building a Family Load & Manage Tool' },
  },

  // ============================================================
  // LESSON PY-21 — Family Load & Manage Tool
  // ============================================================
  {
    id: 'py-21', num: '21',
    title: 'Building a Family Load & Manage Tool',
    topic: 'Deployment', cat: 'advanced', readTime: '10 min', free: false,
    desc: 'Batch-load families from a shared office library folder and build a companion tool that reports which loaded types are actually in use.',
    intro: `Loading families one at a time through Revit\'s Insert tab dialog is tolerable for a handful of files, but the DPC2025 office library folder holds hundreds of families across dozens of subfolders, and a new project template needs a curated subset loaded every time it is set up. This lesson builds a tool that batch-loads an entire folder of .rfa files in one pass, plus a companion reporting tool that identifies which loaded family types are actually placed in the model versus sitting unused — the exact candidates a purge pass should target.`,
    sections: [
      {
        id: 's1', heading: 'Loading a Single Family with doc.LoadFamily()', level: 'h2',
        content: `The Revit API exposes family loading directly on the Document object — no dialog required.`,
        code: {
          label: 'Loading One Family',
          lines: [
            'from pyrevit import revit, DB',
            '',
            'doc = revit.doc',
            'family_path = r"C:\\OfficeLibrary\\Furniture\\Desk_1200x600.rfa"',
            '',
            'with revit.Transaction("Load Family"):',
            '    loaded = doc.LoadFamily(family_path)',
            '',
            'print("Loaded: {}".format(loaded))',
          ],
        },
        items: [
          'doc.LoadFamily(path) returns True/False (or, in some overloads, the loaded Family object directly) indicating whether the load succeeded',
          'Loading a family with the same name as one already in the project follows Revit\'s standard overwrite behaviour — treat this the same way as loading manually, with the same caution on a live production model',
          'Like any model-modifying API call, LoadFamily must run inside a transaction',
        ],
      },
      {
        id: 's2', heading: 'Batch-Loading a Folder of Families', level: 'h2',
        content: `Rather than listing individual file paths, the batch tool walks an entire folder (and its subfolders) collecting every .rfa file to load in one run.`,
        code: {
          label: 'Batch Load from a Folder',
          lines: [
            'import os',
            '',
            'LIBRARY_ROOT = r"C:\\OfficeLibrary\\DPC2025_Approved"',
            '',
            'rfa_paths = []',
            'for root, dirs, files in os.walk(LIBRARY_ROOT):',
            '    for f in files:',
            '        if f.lower().endswith(".rfa"):',
            '            rfa_paths.append(os.path.join(root, f))',
            '',
            'output.print_md("Found **{}** family files to load.".format(len(rfa_paths)))',
            '',
            'loaded_count = 0',
            'failed = []',
            'with revit.Transaction("Batch Load Families"):',
            '    for path in rfa_paths:',
            '        try:',
            '            if doc.LoadFamily(path):',
            '                loaded_count += 1',
            '            else:',
            '                failed.append(path)',
            '        except Exception as ex:',
            '            failed.append(path)',
          ],
        },
        items: [
          'os.walk() recurses through every subfolder automatically, matching a library organized into subfolders by discipline or category (Furniture, Doors, Fixtures)',
          'Wrapping each individual load in try/except keeps one corrupt or incompatible family file from halting the entire batch',
          'Reference the library at a shared network path, never a personal drive letter — exactly the portability rule that applies to any office-wide automation tool',
        ],
      },
      {
        id: 's3', heading: 'Filtering the Batch by Subfolder or Name', level: 'h2',
        content: `A full batch load is not always appropriate — a new residential project template does not need the office\'s entire structural connection library. Filtering the walk keeps the load targeted.`,
        items: [
          'Filter os.walk() results by folder name (e.g., only load from the "Furniture" and "Doors" subfolders) when a project only needs a subset',
          'Filter by filename substring (e.g., skip anything containing "_OLD" or "_deprecated") to exclude library content the office has flagged as retired but not yet deleted',
          'Present the filtered list to the user via forms.SelectFromList with multi-select enabled before loading, so the final set is a deliberate choice rather than a blind bulk operation',
        ],
        code: {
          label: 'Confirming the Load List',
          lines: [
            'selected = forms.SelectFromList.show(',
            '    sorted(os.path.basename(p) for p in rfa_paths),',
            '    title="Select Families to Load",',
            '    multiselect=True,',
            '    button_name="Load Selected")',
          ],
        },
      },
      {
        id: 's4', heading: 'Reporting Loaded Family Types', level: 'h2',
        content: `After loading, it is useful to enumerate every FamilySymbol (family type) now available in the project, confirming exactly what landed and under what names.`,
        code: {
          label: 'Listing Family Types',
          lines: [
            'symbols = DB.FilteredElementCollector(doc) \\',
            '    .OfClass(DB.FamilySymbol) \\',
            '    .ToElements()',
            '',
            'for sym in symbols:',
            '    print("{} : {}".format(sym.Family.Name, sym.Name))',
          ],
        },
        items: [
          'FamilySymbol is the API class representing a family type — collecting OfClass(DB.FamilySymbol) returns every type across every loadable family category in one pass',
          'Grouping printed results by sym.Family.Name gives a readable, family-by-family breakdown rather than one long flat list',
        ],
      },
      {
        id: 's5', heading: 'Finding Unused Family Types — Purge Candidates', level: 'h2',
        content: `The companion tool answers a different question: of everything currently loaded, which family types have zero placed instances anywhere in the model — the exact definition of a safe purge candidate.`,
        code: {
          label: 'Unused Type Report',
          lines: [
            'all_symbols = DB.FilteredElementCollector(doc) \\',
            '    .OfClass(DB.FamilySymbol) \\',
            '    .ToElements()',
            '',
            'placed_instances = DB.FilteredElementCollector(doc) \\',
            '    .OfClass(DB.FamilyInstance) \\',
            '    .WhereElementIsNotElementType() \\',
            '    .ToElements()',
            '',
            'used_type_ids = {inst.GetTypeId() for inst in placed_instances}',
            '',
            'unused = [sym for sym in all_symbols if sym.Id not in used_type_ids]',
            '',
            'output.print_md("## Unused Family Types (Purge Candidates)")',
            'rows = [[output.linkify(sym.Id), sym.Family.Name, sym.Name] for sym in unused]',
            'output.print_table(table_data=rows, columns=["Type", "Family", "Type Name"])',
          ],
        },
        items: [
          'GetTypeId() on each placed FamilyInstance gives the type actually in use — comparing every loaded symbol\'s Id against this set is a direct, reliable way to find zero-instance types',
          'This check only covers instance-based families placed as FamilyInstance elements — system families and some annotation categories are not covered by this pattern and would need a separate check',
          'A type appearing as "unused" here is a candidate for the built-in Purge Unused command, not something this tool deletes itself — reporting and deleting are kept as separate, deliberate steps',
        ],
      },
      {
        id: 's6', heading: 'Combining Both Tools into One Panel', level: 'h2',
        content: `Load and Report are natural companions and belong together in the extension\'s ribbon, even though they are two separate pushbuttons.`,
        items: [
          'Place "Load Family Library" and "Report Unused Types" as two buttons in the same "Family Management" panel, since they are typically used in sequence — load for a new project, then periodically check what is going stale',
          'Keep the report tool strictly read-only; it identifies candidates for a human (or the standard Purge Unused command) to act on, matching the same checking-vs-fixing separation from the model checker tool',
          'Run the unused-type report periodically through the life of the DPC2025 project, not just once at setup, since types can become unused later as design decisions change',
        ],
      },
    ],
    takeaways: [
      'doc.LoadFamily(path), wrapped in a transaction, loads a single .rfa file directly without opening the Insert tab dialog.',
      'os.walk() over a shared library root collects every .rfa path recursively, enabling a one-pass batch load of an entire office library folder or subfolder.',
      'Wrapping each individual family load in try/except prevents one corrupt or incompatible file from halting an entire batch operation.',
      'Collecting DB.FamilySymbol via FilteredElementCollector enumerates every loaded family type currently available in the project.',
      'Comparing all loaded FamilySymbol ids against the set of GetTypeId() values from placed FamilyInstance elements identifies unused types — safe purge candidates.',
      'A reporting tool should identify purge candidates without deleting anything itself, leaving the actual purge to a human decision or the standard Purge Unused command.',
    ],
    resource: { label: 'Family Load & Manage Toolkit Guide', type: 'PDF' },
    quiz: { label: 'Family Load & Manage Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-20', title: 'PyRevit & Shared Parameters — Bulk Assignment & Auditing' },
    next: { id: 'py-22', title: 'ISO 19650 Compliance Checker — Naming & Data Validation' },
  },

  // ============================================================
  // LESSON PY-22 — ISO 19650 Compliance Checker
  // ============================================================
  {
    id: 'py-22', num: '22',
    title: 'ISO 19650 Compliance Checker — Naming & Data Validation',
    topic: 'Deployment', cat: 'advanced', readTime: '11 min', free: false,
    desc: 'Validate every sheet and view name against the ISO 19650 naming pattern using real regular expressions, with clickable results in the output window.',
    intro: `Dynamo can approximate regex-style naming checks with a chain of string nodes, but pyRevit has a real advantage here: Python\'s built-in re module gives full, proper regular expression support with none of the workarounds. This lesson builds an ISO 19650 naming compliance checker for DPC2025 that validates every sheet and view name against the Project-Originator-Volume-Level-Type-Role-Number pattern, and — thanks to pyRevit\'s output window — prints results as clickable links that select the offending element directly back in the model.`,
    sections: [
      {
        id: 's1', heading: 'The ISO 19650 Naming Pattern for DPC2025', level: 'h2',
        content: `ISO 19650 defines a structured, hyphen-separated naming pattern for information containers. For DPC2025, the agreed BEP pattern is:`,
        code: {
          label: 'DPC2025 Naming Pattern',
          lines: [
            'Project - Originator - Volume - Level - Type - Role - Number',
            '',
            'Example:  DPC-ARC-ZZ-01-DR-A-0001',
            '           │    │  │  │  │ │   │',
            '           │    │  │  │  │ │   └─ Number (4 digits)',
            '           │    │  │  │  │ └───── Role (A = Architectural)',
            '           │    │  │  │  └──────── Type (DR = Drawing)',
            '           │    │  │  └─────────── Level (01, or ZZ = multiple)',
            '           │    │  └────────────── Volume/System (ZZ = whole project)',
            '           │    └───────────────── Originator (e.g., ARC)',
            '           └────────────────────── Project (DPC = DPC2025)',
          ],
        },
        formula: { label: 'Naming Rule', text: 'DPC-Originator-Volume-Level-Type-Role-Number, exactly matching the field lengths agreed in the DPC2025 BEP' },
      },
      {
        id: 's2', heading: 'Writing the Regex with Python\'s re Module', level: 'h2',
        content: `A regular expression expresses the entire multi-field naming rule in a single line — no chained string-splitting logic required.`,
        code: {
          label: 'Naming Validation Regex',
          lines: [
            'import re',
            '',
            'PATTERN = re.compile(',
            '    r"^DPC-[A-Z]{3}-[A-Z0-9]{2}-[A-Z0-9]{2}-[A-Z]{2}-[A-Z]-\\d{4}$")',
            '',
            'def is_compliant(name):',
            '    return bool(PATTERN.match(name))',
          ],
        },
        items: [
          'Compiling the pattern once with re.compile() is more efficient than calling re.match() with a raw string pattern on every iteration of a large sheet set',
          'The caret (^) and dollar sign ($) anchors ensure the whole name matches the pattern end-to-end, not just a fragment somewhere inside it',
          'Adjust field lengths and character classes to match the exact BEP definition — not every project uses identical field widths, and this pattern should be treated as a per-project constant',
        ],
      },
      {
        id: 's3', heading: 'Collecting Sheet and View Names to Validate', level: 'h2',
        content: `With the pattern ready, the next step collects every sheet and view name in the model to check it against.`,
        code: {
          label: 'Collecting Names',
          lines: [
            'sheets = DB.FilteredElementCollector(doc).OfClass(DB.ViewSheet).ToElements()',
            'views = DB.FilteredElementCollector(doc).OfClass(DB.View) \\',
            '    .WhereElementIsNotElementType().ToElements()',
            '',
            'views = [v for v in views if not v.IsTemplate]',
          ],
        },
        items: [
          'View collection must exclude view templates (v.IsTemplate) since templates are not real, nameable deliverables and should not be checked against the naming convention',
          'Sheets are checked by their Sheet Number field (the part expected to follow the naming pattern exactly), while views may follow a related but distinct convention defined separately in the BEP',
        ],
      },
      {
        id: 's4', heading: 'Running the Check and Identifying the Failing Field', level: 'h2',
        content: `A simple pass/fail is useful, but identifying exactly which field failed speeds up manual correction dramatically — this requires splitting a non-compliant name and comparing it field by field.`,
        code: {
          label: 'Field-Level Diagnosis',
          lines: [
            'FIELD_NAMES = ["Project", "Originator", "Volume", "Level", "Type", "Role", "Number"]',
            'FIELD_PATTERNS = [r"DPC", r"[A-Z]{3}", r"[A-Z0-9]{2}",',
            '                  r"[A-Z0-9]{2}", r"[A-Z]{2}", r"[A-Z]", r"\\d{4}"]',
            '',
            'def diagnose(name):',
            '    parts = name.split("-")',
            '    if len(parts) != len(FIELD_NAMES):',
            '        return "Wrong number of fields (expected {}, got {})".format(',
            '            len(FIELD_NAMES), len(parts))',
            '    for field, part, pattern in zip(FIELD_NAMES, parts, FIELD_PATTERNS):',
            '        if not re.match("^" + pattern + "$", part):',
            '            return "{} field \'{}\' does not match expected pattern".format(',
            '                field, part)',
            '    return "Unknown issue"',
          ],
        },
        items: [
          'Splitting on the hyphen and checking each field against its own smaller pattern isolates exactly which segment broke the naming rule, rather than reporting a generic failure',
          'This diagnostic function is only called for names that already failed the full PATTERN check — it exists purely to explain the failure, not to perform the primary check',
        ],
      },
      {
        id: 's5', heading: 'Printing Clickable Results with output.linkify', level: 'h2',
        content: `pyRevit\'s output window supports clickable element links, so a non-compliant sheet in the report can be clicked to select it directly in the model — a real advantage over a static Excel export.`,
        code: {
          label: 'Clickable Compliance Report',
          lines: [
            'output.print_md("# DPC2025 ISO 19650 Naming Compliance Report")',
            '',
            'rows = []',
            'for sheet in sheets:',
            '    if not is_compliant(sheet.SheetNumber):',
            '        rows.append([',
            '            output.linkify(sheet.Id),',
            '            sheet.SheetNumber,',
            '            diagnose(sheet.SheetNumber),',
            '        ])',
            '',
            'if rows:',
            '    output.print_table(',
            '        table_data=rows,',
            '        title="Non-Compliant Sheets",',
            '        columns=["Sheet", "Number", "Issue"])',
            'else:',
            '    output.print_md("All sheet numbers are compliant.")',
          ],
        },
        items: [
          'output.linkify(element_id) renders a clickable link in the output window; clicking it selects the corresponding element in the active Revit view, letting a reviewer jump straight from the report to the sheet',
          'This is functionally similar to using revit.get_selection() to programmatically set the active selection, but linkify keeps the interaction driven by the reviewer clicking each row individually, rather than selecting everything at once',
          'Print one table for sheets and a second for views, since they may follow related but distinct naming rules under the DPC2025 BEP',
        ],
      },
      {
        id: 's6', heading: 'Why This Beats the Dynamo Core-Node Workaround', level: 'h2',
        content: `Dynamo can approximate a multi-field naming check by chaining String.Split and comparison nodes, but this becomes unwieldy past two or three fields and cannot express true pattern classes (any uppercase letter, any digit) without significant extra node chains.`,
        items: [
          'Python\'s re module expresses character classes, repetition counts, and anchors directly and concisely — a full seven-field check fits in a single readable line',
          'Extending the pattern (adding a field, changing a field\'s length) is a one-line edit to the regex string, not a restructuring of a node graph',
          'The field-level diagnosis function reuses the same small per-field patterns, something that would require substantially more nodes to replicate in Dynamo',
        ],
        formula: { label: 'Regex Advantage', text: 'One compiled pattern replaces what would be a long chain of String.Split and comparison nodes in Dynamo' },
      },
    ],
    takeaways: [
      'Python\'s re module gives full regular expression support inside pyRevit — a real advantage over Dynamo\'s core-node string-chain workarounds for multi-field naming checks.',
      'Compiling the naming pattern once with re.compile() and anchoring it with ^ and $ ensures accurate, efficient, whole-string matching across a large sheet set.',
      'A field-level diagnosis function that splits a name and checks each segment against its own smaller pattern identifies exactly which field failed, speeding up manual correction.',
      'View collections must exclude view templates (v.IsTemplate) before being checked against a naming convention meant for real deliverables.',
      'output.linkify(element_id) renders clickable links in the pyRevit output window that select the corresponding element back in the active Revit view.',
      'Reporting sheets and views in separate tables acknowledges that they may follow related but distinct naming rules under a project\'s BEP.',
    ],
    resource: { label: 'ISO 19650 Compliance Checker Guide', type: 'PDF' },
    quiz: { label: 'ISO 19650 Compliance Checker Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-21', title: 'Building a Family Load & Manage Tool' },
    next: { id: 'py-23', title: 'Deploying a Custom PyRevit Extension to the Team' },
  },

  // ============================================================
  // LESSON PY-23 — Deploying an Extension to the Team
  // ============================================================
  {
    id: 'py-23', num: '23',
    title: 'Deploying a Custom PyRevit Extension to the Team',
    topic: 'Deployment', cat: 'advanced', readTime: '10 min', free: false,
    desc: 'Distribute a pyRevit extension via Git so the whole office runs one shared, version-controlled toolkit that updates with a single pull.',
    intro: `A brilliant extension sitting only on its author\'s machine helps exactly one person. The tools built across this course — the model checker, the titleblock automator, the parameter manager, the ISO 19650 checker — only become office infrastructure once every team member on DPC2025 can install them the same way and receive updates the same way. This lesson covers distributing a pyRevit extension via a Git repository, so the whole office points at one shared, version-controlled toolkit instead of a folder of scripts copied around by hand.`,
    sections: [
      {
        id: 's1', heading: 'Why Git Instead of a Shared Drive Folder', level: 'h2',
        content: `A shared network folder works until two people edit the same script at once, or until no one can tell which copy is actually current. Git solves both problems at the cost of a small learning curve.`,
        items: [
          'Every change to the extension is a tracked commit with a message, an author, and a timestamp — unlike silently overwriting a file on a shared drive',
          'Team members can update to the latest version with a single pull, rather than being told to "copy the new files over" and hoping nothing was missed',
          'Git history means a bad change can be identified and reverted, something a shared folder with no version history cannot offer',
          'A Git repository can live on any standard Git host the office already uses (GitHub, GitLab, Azure DevOps, or a self-hosted server) — nothing pyRevit-specific is required on the hosting side',
        ],
        formula: { label: 'Core Benefit', text: 'One shared, version-controlled source of truth, updated with a single pull, instead of manually copied folders' },
      },
      {
        id: 's2', heading: 'Structuring the Extension for Distribution', level: 'h2',
        content: `The extension folder built up across this course — panels for QA, Sheets, Parameters, and Compliance — becomes the root of the Git repository, following the standard pyRevit .extension folder structure.`,
        code: {
          label: 'Repository Layout',
          lines: [
            'DPC2025-PyRevit-Studio.extension/',
            '  DPC2025 Studio.tab/',
            '    QA.panel/',
            '      Model Checker.pushbutton/',
            '        script.py',
            '        icon.png',
            '    Sheets.panel/',
            '      Titleblock Update.pushbutton/',
            '        script.py',
            '    Parameters.panel/',
            '      Parameter Manager.pushbutton/',
            '        script.py',
            '    Compliance.panel/',
            '      ISO 19650 Checker.pushbutton/',
            '        script.py',
            '  README.md',
          ],
        },
        items: [
          'The .extension folder name and the internal .tab/.panel/.pushbutton naming convention are what pyRevit reads to build the ribbon — this structure does not change just because the folder now lives in Git',
          'A README at the repository root documenting install instructions and a change log is worth the small effort for a toolkit an entire office depends on',
        ],
      },
      {
        id: 's3', heading: 'Adding the Extension from a Git URL', level: 'h2',
        content: `Once the extension is pushed to a Git repository, any team member can add it to their local pyRevit installation in one of two ways.`,
        code: {
          label: 'Adding via the CLI',
          lines: [
            'pyrevit extend ui "DPC2025 Studio" https://github.com/dharrenpark/dpc2025-pyrevit-studio.git',
          ],
        },
        items: [
          'The pyrevit extend ui command clones the given Git URL into pyRevit\'s extensions folder and registers it as a UI extension in one step',
          'Alternatively, the pyRevit Extension Manager GUI offers an "Add from URL" option that does the same clone-and-register operation without touching a command line at all — the better option for less command-line-comfortable teammates',
          'After adding the extension, a pyRevit reload (or restarting Revit) is needed for the new ribbon tab and panels to appear',
        ],
      },
      {
        id: 's4', heading: 'Attach and Extension Search Paths', level: 'h2',
        content: `For pyRevit to consistently find the same shared extension across every machine in the office, the extension search paths and the active attachment need to be configured consistently.`,
        items: [
          'pyrevit attach configures which pyRevit clone (core engine version) is attached to a given Revit version — this is a separate concept from which extensions are loaded, but both need to be consistent office-wide for predictable behaviour',
          'pyRevit\'s Settings → Custom Extension Directories lists the folders pyRevit scans for extensions; confirm the cloned DPC2025 Studio extension folder sits in a path already being scanned, or add it explicitly',
          'Standardizing the clone location (e.g., always under a fixed local folder rather than a personal Documents path) keeps troubleshooting straightforward when comparing one machine to another',
          'Document the required pyrevit attach and extension search path setup as a one-time onboarding step for any new starter joining the DPC2025 team',
        ],
      },
      {
        id: 's5', heading: 'Pushing Updates — Git Pull Under the Hood', level: 'h2',
        content: `Once installed, keeping the extension current across the whole team is a matter of pulling the latest commits, not re-copying files.`,
        items: [
          'pyRevit\'s Extension Manager "Update" button runs a git pull on the extension\'s local clone, fetching and merging in the latest commits from the shared repository',
          'A team member with an uncommitted local edit to their own clone can encounter a merge conflict on update — the office standard should be that no one edits the shared clone directly, only the repository maintainer pushes changes',
          'For urgent fixes, the maintainer commits and pushes to the repository, then a simple office-wide message ("pull the DPC2025 Studio extension") is enough for everyone to receive the fix within their next update click',
          'pyRevit also supports an auto-update setting so extensions check for and apply updates automatically on a schedule, removing even the manual "click Update" step for the team',
        ],
        formula: { label: 'Update Flow', text: 'Maintainer commits and pushes → team clicks Update (or auto-update runs) → git pull → everyone is current' },
      },
      {
        id: 's6', heading: 'Governance — Who Can Change the Shared Toolkit', level: 'h2',
        content: `A shared, office-wide toolkit needs a lightweight governance model so it stays reliable rather than becoming a dumping ground for untested scripts.`,
        items: [
          'Designate a small number of maintainers with push access to the repository; other team members can propose changes via a pull request/merge request rather than pushing directly',
          'Require any change to be tested against a copy of the DPC2025 model before it is merged and distributed to the whole office',
          'Tag stable releases in Git (e.g., v1.0, v1.1) so a specific known-good state can always be referenced or rolled back to if a later change causes a problem',
          'Keep the README\'s change log current so any team member can see, in plain language, what changed and why before pulling an update',
        ],
      },
    ],
    takeaways: [
      'Distributing a pyRevit extension via Git gives every team member the same version-controlled source of truth, updated with a single pull instead of manually copied folders.',
      'The standard .extension/.tab/.panel/.pushbutton folder structure is exactly what gets committed to and cloned from the Git repository — nothing about it changes for distribution.',
      'pyrevit extend ui NAME URL (or the Extension Manager\'s "Add from URL") clones the repository and registers it as a UI extension in one step.',
      'Extension search paths and pyrevit attach must be configured consistently across machines for the shared extension to appear and behave the same way office-wide.',
      'The Extension Manager\'s "Update" action runs a git pull under the hood, and auto-update can remove even that manual step.',
      'A small maintainer group, tested changes, and tagged stable releases keep a shared, office-wide toolkit reliable rather than an uncontrolled dumping ground.',
    ],
    resource: { label: 'Extension Deployment & Git Workflow Guide', type: 'PDF' },
    quiz: { label: 'Deploying PyRevit Extensions Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-22', title: 'ISO 19650 Compliance Checker — Naming & Data Validation' },
    next: { id: 'py-24', title: 'Capstone — DPC2025 PyRevit Studio Toolkit: Full Suite Deployment' },
  },

  // ============================================================
  // LESSON PY-24 — Capstone
  // ============================================================
  {
    id: 'py-24', num: '24',
    title: 'Capstone — DPC2025 PyRevit Studio Toolkit: Full Suite Deployment',
    topic: 'Capstone', cat: 'advanced', readTime: '14 min', free: false,
    desc: 'Assemble every tool built across this course into one coherent, multi-panel extension and deploy it to the whole DPC2025 team via Git.',
    intro: `This capstone brings the entire pyRevit course together into a single piece of real office infrastructure: the DPC2025 PyRevit Studio. Instead of four separate scripts scattered across different folders, you are going to assemble the model checker, the sheet and titleblock automator, the parameter manager, and the ISO 19650 compliance checker into one coherent extension with clearly organized panels — then deploy that extension to the whole team via Git, exactly as covered in the previous lesson. By the end, DPC2025 has a real, living toolkit rather than a collection of one-off scripts, and you have a template for structuring the next one.`,
    sections: [
      {
        id: 's1', heading: 'The Brief', level: 'h2',
        content: `DPC2025 is heading into full production, and the BIM lead has asked for every automation tool built so far to be consolidated into a single, properly organized extension that the whole team can install once and keep updated from then on.

**The task**: assemble a "DPC2025 PyRevit Studio" extension containing:
1. A **QA panel** with the Model Checker tool (Lesson 17)
2. A **Sheets panel** with the Titleblock Update tool (Lesson 18)
3. A **Parameters panel** with the Parameter Manager (Lesson 19) and the Shared Parameter Auditor (Lesson 20)
4. A **Compliance panel** with the ISO 19650 Checker (Lesson 22)

Then deploy the whole extension to a Git repository so every DPC2025 team member can add it with one command and receive future fixes with one pull.`,
        formula: { label: 'Capstone Scope', text: 'Model Checker + Titleblock Automation + Parameter Manager + Shared Parameter Audit + ISO 19650 Checker = one extension, one ribbon tab, one Git repository' },
      },
      {
        id: 's2', heading: 'Step 1 — Laying Out the Extension Structure', level: 'h2',
        content: `The first step is purely organizational: deciding the tab, panel, and button structure before dropping any script.py files in place.`,
        code: {
          label: 'DPC2025 PyRevit Studio Layout',
          lines: [
            'DPC2025-PyRevit-Studio.extension/',
            '  DPC2025 Studio.tab/',
            '    QA.panel/',
            '      Model Checker.pushbutton/',
            '        script.py',
            '    Sheets.panel/',
            '      Titleblock Update.pushbutton/',
            '        script.py',
            '    Parameters.panel/',
            '      Parameter Manager.pushbutton/',
            '        script.py',
            '      Shared Param Audit.pushbutton/',
            '        script.py',
            '    Compliance.panel/',
            '      ISO 19650 Checker.pushbutton/',
            '        script.py',
            '  README.md',
          ],
        },
        items: [
          'One ribbon tab ("DPC2025 Studio") keeps every tool for this project in one predictable place, rather than scattered across the default pyRevit tab',
          'Four panels group tools by purpose (QA, Sheets, Parameters, Compliance) exactly matching how the team already thinks about these tasks',
          'Grouping the Parameter Manager and Shared Param Audit together under one Parameters panel reflects that both tools deal with the same underlying concern — keeping model data consistent',
        ],
      },
      {
        id: 's3', heading: 'Step 2 — Bringing Each Tool In Unchanged', level: 'h2',
        content: `Each script from Lessons 17 through 22 moves into its designated pushbutton folder largely as-is — the value of this capstone is in the assembly and organization, not in rewriting logic that already works.`,
        items: [
          'Copy each tested script.py into its new pushbutton folder, updating only file paths or shared constants (like the shared parameter file location) to the single DPC2025 office-standard values',
          'Give every pushbutton a clear icon and a tooltip describing exactly what it does and, where relevant, whether it modifies the model or only reports on it',
          'Keep the model checker (Lesson 17) and the shared parameter auditor (Lesson 20) clearly labelled as read-only reporting tools, distinct from the titleblock updater and parameter manager, which do write to the model',
          'Any shared helper code used by more than one tool (for example, a common Transaction-safe write helper) belongs in a lib subfolder inside the extension, imported by each script rather than duplicated across pushbuttons',
        ],
      },
      {
        id: 's4', heading: 'Step 3 — A Shared Config for Office Constants', level: 'h2',
        content: `Several tools reference the same office-standard values — the shared parameter file path, the ISO 19650 naming pattern, the approved family library root. Centralizing these avoids updating the same constant in five different scripts.`,
        code: {
          label: 'config.py — Shared Constants',
          lines: [
            '# DPC2025-PyRevit-Studio.extension/lib/dpc2025_config.py',
            '',
            'SHARED_PARAM_FILE = r"C:\\OfficeStandards\\DPC2025_SharedParams.txt"',
            'FAMILY_LIBRARY_ROOT = r"C:\\OfficeLibrary\\DPC2025_Approved"',
            'NAMING_PATTERN = r"^DPC-[A-Z]{3}-[A-Z0-9]{2}-[A-Z0-9]{2}-[A-Z]{2}-[A-Z]-\\d{4}$"',
            'PROJECT_NAME = "DPC2025 Capstone"',
          ],
        },
        items: [
          'Each pushbutton script imports from dpc2025_config instead of hardcoding its own copy of the same path or pattern',
          'When the office standard changes (a new shared parameter file version, a revised naming pattern), editing this one file updates every tool that depends on it at once',
          'This mirrors the same "hardcode only what must be hardcoded" discipline from the Parameter Manager tool, applied at the level of the whole extension rather than one script',
        ],
      },
      {
        id: 's5', heading: 'Step 4 — Testing the Assembled Extension', level: 'h2',
        content: `Before deployment, the whole assembled extension needs to be tested together, not just as four scripts that once worked individually.`,
        items: [
          'Reload pyRevit and confirm the DPC2025 Studio tab appears with all four panels and five buttons in the expected layout',
          'Run each tool in turn against a duplicated test copy of the DPC2025 model, confirming the shared config values resolve correctly for every tool',
          'Confirm the model checker and ISO 19650 checker\'s output.print_table() reports still render correctly and their linkify links still select the right elements once running from inside the consolidated extension',
          'Have at least one other team member test-install the extension from the Git repository (not just run it locally from the original development folder) before calling it ready',
        ],
      },
      {
        id: 's6', heading: 'Step 5 — Deploying via Git', level: 'h2',
        content: `With the extension assembled and tested, deployment follows the process from the previous lesson exactly: push to a Git repository, then have the team add it.`,
        code: {
          label: 'Team Install Command',
          lines: [
            'pyrevit extend ui "DPC2025 Studio" https://github.com/dharrenpark/dpc2025-pyrevit-studio.git',
          ],
        },
        items: [
          'Push the assembled extension folder to a new Git repository, with a README documenting each tool, its panel, and whether it reads or writes to the model',
          'Tag the initial release (v1.0) once the team-tested version is confirmed working, giving the office a known-good baseline to reference',
          'Communicate the install command (or the Extension Manager\'s "Add from URL" equivalent) to the whole DPC2025 team as a one-time onboarding step',
          'From this point on, any fix or new tool ships as a new commit — the team simply clicks Update to receive it',
        ],
      },
      {
        id: 's7', heading: 'What You Built', level: 'h2',
        content: `Stepping back, DPC2025 now has something meaningfully different from a folder of scripts: a real, versioned, team-installed piece of office infrastructure. A QA sweep that used to require remembering to check things by hand runs in one click. Titleblock corrections that used to mean opening every sheet now touch the whole set in one transaction. A parameter fix that used to mean writing a new script now goes through one general-purpose tool. Naming compliance that used to mean eyeballing a sheet list is now a regex-backed report with clickable links straight back into the model.

More importantly, this capstone demonstrates the actual arc of this course: starting from individual pyRevit concepts — pushbuttons, FilteredElementCollector, transactions, forms, the Revit API underneath it all — and ending with the judgment to assemble them into something an entire office depends on and can maintain going forward. The DPC2025 PyRevit Studio is not the last tool this office will ever need, but it is the template for how every future tool should be built, organized, and shipped.`,
        formula: { label: 'Capstone Complete', text: 'Four tools + one shared config + one extension structure + one Git repository = office-wide production infrastructure' },
      },
    ],
    takeaways: [
      'Consolidating the Model Checker, Titleblock Update, Parameter Manager, Shared Parameter Auditor, and ISO 19650 Checker into one extension turns individual scripts into real office infrastructure.',
      'Organize tools into panels by purpose (QA, Sheets, Parameters, Compliance) so the ribbon layout matches how the team already thinks about the tasks.',
      'A shared config module (e.g., dpc2025_config.py) centralizes office-standard constants — shared parameter file path, naming pattern, library root — so one edit updates every tool that depends on it.',
      'Test the fully assembled extension as a whole, including a test-install from the Git repository itself, before treating it as ready for the team.',
      'Deploy via pyrevit extend ui or the Extension Manager\'s "Add from URL," tagging a stable v1.0 release as the office\'s known-good baseline.',
      'Read-only reporting tools (Model Checker, Shared Parameter Auditor, ISO 19650 Checker) should stay clearly distinguished from model-modifying tools (Titleblock Update, Parameter Manager) even inside one consolidated extension.',
    ],
    resource: { label: 'DPC2025 PyRevit Studio Capstone Brief', type: 'PDF' },
    quiz: { label: 'PyRevit Capstone Quiz', questions: 10, time: '5 min' },
    prev: { id: 'py-23', title: 'Deploying a Custom PyRevit Extension to the Team' },
    next: null,
  },

]
