// lib/revitMatrixData.js
// STATIC SAMPLE DATA — placeholder for the Revit Matrix portfolio dashboard.
// Replace with a Supabase query (e.g. a `bim_projects` table) once the
// real audit data model is designed. Shape is intentionally kept simple
// so swapping the data source later doesn't require touching the UI.

export const sampleProjects = [
  {
    id: 'proj-2401',
    code: 'PROJ-2401',
    name: 'Riverside Tower',
    sector: 'Commercial',
    stage: 4,
    bep: 'ISO 19650-2',
    bepFiled: true,
    lastAuditDaysAgo: 3,
    status: 'compliant', // 'compliant' | 'drifting' | 'noncompliant'
    scores: { naming: 100, lod: 95, worksets: 100 },
    flags: [],
  },
  {
    id: 'proj-2389',
    code: 'PROJ-2389',
    name: 'Northgate Logistics Hub',
    sector: 'Industrial',
    stage: 3,
    bep: 'ISO 19650-2',
    bepFiled: true,
    lastAuditDaysAgo: 1,
    status: 'drifting',
    scores: { naming: 72, lod: 90, worksets: 68 },
    flags: ['Legacy naming scheme on 4 structural files'],
  },
  {
    id: 'proj-2412',
    code: 'PROJ-2412',
    name: 'Cedar Park Residences',
    sector: 'Residential',
    stage: 2,
    bep: null,
    bepFiled: false,
    lastAuditDaysAgo: 6,
    status: 'noncompliant',
    scores: { naming: 40, lod: 35, worksets: 55 },
    flags: ['No BEP on file — kickoff standards not enforced'],
  },
  {
    id: 'proj-2350',
    code: 'PROJ-2350',
    name: 'Marlow Bridge Crossing',
    sector: 'Infrastructure',
    stage: 5,
    bep: 'ISO 19650-2',
    bepFiled: true,
    lastAuditDaysAgo: 5,
    status: 'compliant',
    scores: { naming: 98, lod: 100, worksets: 96 },
    flags: [],
  },
  {
    id: 'proj-2398',
    code: 'PROJ-2398',
    name: 'Oakfield Business Park',
    sector: 'Commercial',
    stage: 3,
    bep: 'ISO 19650-2',
    bepFiled: true,
    lastAuditDaysAgo: 2,
    status: 'drifting',
    scores: { naming: 88, lod: 64, worksets: 91 },
    flags: ['MEP LOD 350 not met for 3 zones ahead of Stage 4 gate'],
  },
  {
    id: 'proj-2375',
    code: 'PROJ-2375',
    name: 'Harborview Mixed-Use',
    sector: 'Mixed-Use',
    stage: 4,
    bep: 'ISO 19650-2',
    bepFiled: true,
    lastAuditDaysAgo: 4,
    status: 'compliant',
    scores: { naming: 97, lod: 93, worksets: 100 },
    flags: [],
  },
];
