// lib/revitMatrixWorkflows.js
// Project-agnostic process-flow reference for Revit Matrix.
// Each workflow is the canonical, studio-standard sequence — not tied to
// any single project. The [id] drill-down's Workflow tab will later
// overlay a project's current stage/status on top of this same data.

export const workflows = [
  {
    id: 'bep-authoring',
    label: 'BEP Authoring & Approval',
    short: 'BEP',
    description: 'From EIR receipt to a signed-off BIM Execution Plan the whole task team works from.',
    color: '#2563eb',
    stages: [
      {
        title: 'Receive & Review EIR',
        role: 'BIM Manager',
        action: 'Read the Exchange Information Requirements from the Appointing Party in full — information purposes, LOD/LOI targets, delivery milestones, federation strategy.',
        checkpoint: 'EIR requirements logged against studio capability — gaps flagged before drafting starts.',
        output: 'EIR Review Log',
      },
      {
        title: 'Draft BEP',
        role: 'BIM Manager + Task Team Leads',
        action: 'Translate EIR requirements into the pre-appointment or post-appointment BEP — naming convention, CDE workflow, LOD by stage, RACI, federation strategy.',
        checkpoint: 'Draft covers every EIR clause with a corresponding BEP section — no silent gaps.',
        output: 'Draft BEP (CDE: WIP)',
      },
      {
        title: 'Internal Review',
        role: 'BIM Manager',
        action: 'Circulate the draft to discipline leads for technical sign-off before it goes external — software compatibility, workset structure, hardware/IT readiness.',
        checkpoint: 'All discipline leads confirm the BEP is workable for their team.',
        output: 'Reviewed BEP (CDE: Shared)',
      },
      {
        title: 'Submit to Appointing Party',
        role: 'BIM Manager',
        action: 'Submit the BEP for formal review, with any assumptions or deviations from the EIR clearly flagged.',
        checkpoint: 'Submission acknowledged and logged in the CDE.',
        output: 'Submitted BEP',
      },
      {
        title: 'Sign-off',
        role: 'Appointing Party + BIM Manager',
        action: 'Resolve any review comments, finalize, and obtain formal acceptance from the Appointing Party.',
        checkpoint: 'Signed BEP filed in the CDE under the project record; kickoff can proceed.',
        output: 'Approved BEP (CDE: Published)',
      },
    ],
  },
  {
    id: 'model-federation',
    label: 'Model Federation',
    short: 'Federation',
    description: 'Combining discipline models into a single coordinated federated model for review.',
    color: '#5b8cf0',
    stages: [
      {
        title: 'Discipline Model Prep',
        role: 'Discipline Leads',
        action: 'Each discipline confirms their model is at the agreed LOD, on shared coordinates, and free of unresolved local warnings before linking.',
        checkpoint: 'Shared coordinates verified against the project base point.',
        output: 'Discipline Models (Ready)',
      },
      {
        title: 'Link & Coordinate Check',
        role: 'BIM Manager',
        action: 'Link all discipline models into the federation file; verify origin alignment, levels/grids match, and no model is offset.',
        checkpoint: 'Visual spot-check across 3+ levels confirms alignment.',
        output: 'Linked Composite Model',
      },
      {
        title: 'Federate',
        role: 'BIM Manager',
        action: 'Run the federation per the BEP-defined strategy (linked model vs. Navisworks NWF), apply standard views and filters.',
        checkpoint: 'Federated model opens cleanly with all disciplines visible and correctly filtered.',
        output: 'Federated Model',
      },
      {
        title: 'Publish for Review',
        role: 'BIM Manager',
        action: 'Upload the federated model to the CDE under the agreed naming convention, notify task teams it is available for coordination review.',
        checkpoint: 'Federated model accessible to all task teams in the CDE.',
        output: 'Published Federated Model (CDE: Shared)',
      },
    ],
  },
  {
    id: 'clash-detection',
    label: 'Clash Detection & Resolution',
    short: 'Clash',
    description: 'Running coordination checks on the federated model and closing out conflicts.',
    color: '#7c3aed',
    stages: [
      {
        title: 'Run Clash Test',
        role: 'BIM Manager',
        action: 'Execute clash detection per the BEP-defined rule sets (hard clash, clearance, soft clash) across discipline pairs.',
        checkpoint: 'Clash report generated covering all rule sets defined in the BEP.',
        output: 'Clash Report (Raw)',
      },
      {
        title: 'Triage & Assign',
        role: 'BIM Manager',
        action: 'Review raw clashes, filter false positives, categorize by severity, and assign each genuine clash to the responsible discipline.',
        checkpoint: 'Every genuine clash has an assigned owner and due date.',
        output: 'Triaged Clash Log',
      },
      {
        title: 'Resolve',
        role: 'Discipline Leads',
        action: 'Discipline teams update their models to resolve assigned clashes within the agreed timeframe.',
        checkpoint: 'Discipline confirms resolution in the clash log with a brief note on the fix.',
        output: 'Updated Discipline Models',
      },
      {
        title: 'Re-Run & Verify',
        role: 'BIM Manager',
        action: 'Re-link updated models and re-run the clash test to confirm resolved items are actually closed and no new clashes were introduced.',
        checkpoint: 'Resolved clash count matches the triaged log; no regression clashes.',
        output: 'Verified Clash Report',
      },
      {
        title: 'Close Cycle',
        role: 'BIM Manager',
        action: 'Archive the clash cycle, log outstanding items for the next coordination meeting, and confirm next run date.',
        checkpoint: 'Clash cycle logged in the project coordination record.',
        output: 'Closed Clash Cycle Log',
      },
    ],
  },
  {
    id: 'ifc-export',
    label: 'IFC Export & QA',
    short: 'IFC',
    description: 'Preparing, exporting, and validating IFC deliverables against the agreed schema.',
    color: '#10b981',
    stages: [
      {
        title: 'Pre-Export Check',
        role: 'Discipline Leads',
        action: 'Confirm shared parameters, classification (Uniclass/OmniClass), and property sets are correctly applied before export.',
        checkpoint: 'Spot-check of classification fields against the BEP-defined schema.',
        output: 'Export-Ready Model',
      },
      {
        title: 'Configure & Export',
        role: 'BIM Manager',
        action: 'Apply the agreed IFC export setup (IFC2x3 or IFC4, MVD, mapping table) and export each discipline model.',
        checkpoint: 'Export completes without critical errors in the export log.',
        output: 'IFC Files (Raw)',
      },
      {
        title: 'Validate',
        role: 'BIM Manager',
        action: 'Run the exported IFC through a validation tool (e.g. Solibri, BIMcollab) to check schema compliance and data completeness.',
        checkpoint: 'Validation report shows no schema-breaking errors.',
        output: 'Validation Report',
      },
      {
        title: 'Issue Log & Fix',
        role: 'BIM Manager + Discipline Leads',
        action: 'Log any validation issues, route back to the responsible discipline for correction, and re-export if needed.',
        checkpoint: 'All flagged issues closed or formally accepted as known limitations.',
        output: 'Corrected IFC Files',
      },
      {
        title: 'Approve for Delivery',
        role: 'BIM Manager',
        action: 'Confirm final IFC set is complete, named per convention, and ready for CDE upload.',
        checkpoint: 'Final IFC package matches the delivery schedule in the BEP.',
        output: 'Approved IFC Package',
      },
    ],
  },
  {
    id: 'sign-off',
    label: 'Sign-off & CDE Publication',
    short: 'Sign-off',
    description: 'Final approval chain and formal status change from Shared to Published in the CDE.',
    color: '#f59e0b',
    stages: [
      {
        title: 'Final QA Pass',
        role: 'BIM Manager',
        action: 'Run a final check across naming, LOD, clash status, and IFC validation before requesting approval.',
        checkpoint: 'All four checks pass against the project Setup Matrix.',
        output: 'QA-Cleared Deliverable',
      },
      {
        title: 'Internal Approval',
        role: 'Project Lead / Discipline Lead',
        action: 'Internal sign-off confirming the deliverable is ready to leave the studio.',
        checkpoint: 'Approval logged with name, role, and date.',
        output: 'Internally Approved Deliverable',
      },
      {
        title: 'Submit for Client/Appointing Party Approval',
        role: 'BIM Manager',
        action: 'Move the deliverable to Shared status in the CDE and notify the Appointing Party for review.',
        checkpoint: 'CDE status correctly reflects Shared, not Published, until external sign-off.',
        output: 'Shared Deliverable (CDE: Shared)',
      },
      {
        title: 'Publish',
        role: 'BIM Manager',
        action: 'On receiving formal acceptance, change CDE status to Published and archive the prior revision per the BEP retention policy.',
        checkpoint: 'CDE status updated, revision history preserved.',
        output: 'Published Deliverable (CDE: Published)',
      },
      {
        title: 'Notify Task Teams',
        role: 'BIM Manager',
        action: 'Confirm all task teams are aware of the publication and any downstream actions required.',
        checkpoint: 'Notification sent and acknowledged.',
        output: 'Closed Publication Cycle',
      },
    ],
  },
];
