// ============================================================
// AUTODESK CONSTRUCTION CLOUD — LESSONS acc-9 through acc-16 (INTERMEDIATE)
// Section: Model Coordination & Construction Management
// File: lib/accLessonsContent/accLessons_9_16.js
// Index: lib/accLessonsData.js
// ============================================================

export const lessons_9_16 = [

  // ============================================================
  // LESSON ACC-09 — Model Coordination — Setting Up a Coordination Space
  // ============================================================
  {
    id: 'acc-9', num: '09',
    title: 'Model Coordination — Setting Up a Coordination Space',
    topic: 'Model Coordination', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Set up an ACC Model Coordination space, add model packages, and configure your first coordination workflow in the cloud.',
    intro: `Model coordination in ACC is not Navisworks in a browser — it is a fundamentally different workflow. Where Navisworks requires someone to manually assemble a federated model and run tests on a desktop machine, ACC Coordinate runs clash detection automatically in the cloud as models are updated. The key is setting up the Coordination Space correctly from the start — defining which models participate, how they are organised, and what tests to run. This lesson covers that setup in detail.`,
    sections: [
      {
        id: 's1', heading: 'What is a Coordination Space?', level: 'h2',
        content: `A **Coordination Space** in ACC is the container within which model coordination happens. It defines which model files are included in coordination, how those files are organised (by model package or discipline), and which clash tests run against which combinations of models.`,
        items: [
          'Each project can have multiple Coordination Spaces — for example, one per building or zone on a large project',
          'A Coordination Space pulls models directly from ACC Docs folders — no manual export required',
          'When a model in Docs is updated, the Coordination Space automatically uses the new version in the next coordination run',
          'Coordination Spaces are created and managed in the **Coordinate** module by users with Coordinate Admin access',
          'The output of a Coordination Space is a set of clash results — viewable and assignable within ACC without leaving the browser',
        ],
        formula: { label: 'Coordination Space Concept', text: 'Models in Docs → Coordination Space → Automatic Clash Tests → Actionable Results' },
      },
      {
        id: 's2', heading: 'Enabling the Coordinate Module', level: 'h2',
        content: `Before creating a Coordination Space, the Coordinate module must be active on the project and users must have the correct access.`,
        subsections: [
          {
            heading: 'Module Activation Steps',
            items: [
              'Project Settings → Modules → find "Model Coordination" or "Coordinate"',
              'Toggle the module on — it is now available in the left sidebar',
              'Assign Coordinate module access to team members: View (can see results) or Admin (can configure spaces and tests)',
              'BIM Managers and discipline leads typically need Admin access to the Coordinate module',
              'Site managers and contractors often need only View access to review and respond to clash results',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'Creating a Coordination Space', level: 'h2',
        content: `A Coordination Space is created from the Coordinate module. The setup process involves naming the space, selecting the source folder for models, and configuring model packages.`,
        subsections: [
          {
            heading: 'Coordination Space Setup Steps',
            items: [
              'Navigate to the Coordinate module in the left sidebar',
              'Click **+ New Space** (or "Create Coordination Space")',
              'Enter a name — be specific: "Tower A — Full Federated" or "Zone 1 — Structure vs MEP"',
              'Select the **Source Folder** — the Docs folder where your models are stored',
              'ACC lists all model files in the selected folder — choose which to include in the space',
              'Models are grouped into **Packages** (discipline groups) — configure package assignments (covered below)',
              'Click Create — the Coordination Space is created and begins its first processing run',
            ],
          },
        ],
      },
      {
        id: 's4', heading: 'Model Packages', level: 'h2',
        content: `**Model Packages** are how ACC groups models by discipline within a Coordination Space. Packages are used to define which models clash against which others.`,
        code: {
          label: 'Typical Model Package Structure',
          lines: [
            'Package: Architecture',
            '  → ProjectCode_A_Architecture_L01.rvt',
            '  → ProjectCode_A_Architecture_L02.rvt',
            '  → ProjectCode_A_Architecture_L03.rvt',
            '',
            'Package: Structure',
            '  → ProjectCode_S_Structure_All.ifc',
            '',
            'Package: Mechanical',
            '  → ProjectCode_M_HVAC_L01.rvt',
            '  → ProjectCode_M_HVAC_L02.rvt',
            '',
            'Package: Electrical',
            '  → ProjectCode_E_Electrical_L01.ifc',
            '',
            'Package: Plumbing',
            '  → ProjectCode_P_Drainage_All.rvt',
            '',
            'Clash tests run package-vs-package:',
            '  Structure vs Architecture',
            '  MEP vs Structure',
            '  MEP vs Architecture',
            '  Mechanical vs Electrical',
          ],
        },
      },
      {
        id: 's5', heading: 'Supported File Formats for Coordination', level: 'h2',
        content: `ACC Coordinate accepts models in a range of formats — not just Revit. This is important for projects with a mixed software environment.`,
        items: [
          '**RVT (Revit)** — native format; most properties and element hierarchy are preserved',
          '**IFC** — open BIM format; widely used for interoperability with non-Autodesk tools',
          '**NWC (Navisworks Cache)** — exported from Revit, Navisworks, or other tools',
          '**DWG** — AutoCAD and Civil 3D geometry; geometry only, limited property transfer',
          '**RCX** — civil infrastructure files from Civil 3D',
          'For best coordination quality, use RVT or IFC — DWG files carry limited property data, reducing the usefulness of clash results',
        ],
      },
      {
        id: 's6', heading: 'Configuring Model Updates', level: 'h2',
        content: `One of ACC Coordinate's most powerful features is automatic model update processing. When a model is updated in the source Docs folder, the Coordination Space can be set to process the new version automatically.`,
        subsections: [
          {
            heading: 'Model Update Settings',
            items: [
              'In the Coordination Space settings, each model has an "Auto-Update" toggle',
              'When enabled, uploading a new version of the model to Docs triggers automatic reprocessing in the Coordination Space',
              'The reprocessing converts the model to a web-viewable format and prepares it for clash detection',
              'Reprocessing typically takes 5–30 minutes depending on model size',
              'Team members are notified when a model has been updated and is ready for coordination',
              'A processing history shows all model versions that have been processed, with timestamps',
            ],
          },
        ],
      },
      {
        id: 's7', heading: 'Coordination Workflow Overview', level: 'h2',
        content: `With the Coordination Space set up, the ongoing weekly coordination workflow follows a consistent cycle.`,
        code: {
          label: 'Weekly Coordination Cycle in ACC',
          lines: [
            '1. Model Update',
            '   Each discipline uploads updated model to Docs [Shared]',
            '   ACC auto-processes the new version in Coordinate',
            '',
            '2. Clash Detection Runs',
            '   ACC runs configured package-vs-package clash tests',
            '   Results update automatically with new vs resolved clashes',
            '',
            '3. Clash Review Meeting',
            '   Team reviews new clashes in the ACC browser viewer',
            '   Critical clashes are assigned to responsible discipline',
            '',
            '4. Clash Resolution',
            '   Assigned designer resolves the clash in their authoring tool',
            '   Uploads new model version → clash shows as Resolved',
            '',
            '5. Coordination Report',
            '   Progress report generated from Insights or exported',
            '   Outstanding clashes tracked to closure',
          ],
        },
      },
    ],
    takeaways: [
      'A Coordination Space is the container in ACC where model coordination happens — it connects to model files in Docs and runs clash tests automatically.',
      'Models are grouped into Packages by discipline; clash tests run between package combinations (Structure vs MEP, Architecture vs MEP, etc.).',
      'ACC Coordinate supports RVT, IFC, NWC, and DWG formats; RVT and IFC provide the richest coordination data.',
      'Auto-Update processing means uploading a new model version to Docs automatically triggers a new coordination run — no manual assembly.',
      'The weekly coordination cycle: model update → automatic clash run → review meeting → resolution → updated model → clash closes.',
      'BIM Managers and discipline leads need Coordinate Admin access; contractors and site teams typically need View access only.',
    ],
    resource: { label: 'ACC Coordinate Setup Guide', type: 'PDF' },
    quiz: { label: 'Coordination Space Setup Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-8', title: 'Sharing & Collaborating — Members, Companies & Permission Sets' },
    next: { id: 'acc-10', title: 'Model Coordination — Running Clash Detection in the Cloud' },
  },

  // ============================================================
  // LESSON ACC-10 — Running Clash Detection in the Cloud
  // ============================================================
  {
    id: 'acc-10', num: '10',
    title: 'Model Coordination — Running Clash Detection in the Cloud',
    topic: 'Model Coordination', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Configure and run cloud-based clash detection tests in ACC Coordinate — test types, tolerances, and comparing results with Navisworks.',
    intro: `Cloud clash detection in ACC removes the single-point-of-failure from the coordination workflow: no longer does one person need to assemble the federated model in Navisworks and run the tests before the weekly meeting. In ACC, tests run automatically and continuously as models are updated. But automatic does not mean unconfigured — poorly set up clash tests produce so many results that teams stop reviewing them. This lesson covers how to configure meaningful clash tests that surface real coordination problems.`,
    sections: [
      {
        id: 's1', heading: 'How Cloud Clash Detection Works', level: 'h2',
        content: `ACC Coordinate uses Autodesk's cloud processing infrastructure to run clash detection tests against the models in a Coordination Space. Unlike Navisworks (which runs tests locally on a desktop), ACC runs tests in the cloud — meaning they execute automatically, without requiring anyone to be in the software.`,
        items: [
          'Clash tests are defined once at Coordination Space setup — they run every time a model is updated',
          'Tests run in the cloud without any user action — results are available when processing completes',
          'Cloud processing handles models that would be too large to run efficiently on a desktop machine',
          'Results are immediately viewable in the browser after processing — no file to open or download',
          'All team members with Coordinate View access can see the same results simultaneously',
          'The most recent clash run results are always shown by default; older runs are accessible for trend analysis',
        ],
        formula: { label: 'Cloud Advantage', text: 'Model uploaded to Docs → automatic processing → clash results available to all team members simultaneously' },
      },
      {
        id: 's2', heading: 'Creating Clash Tests', level: 'h2',
        content: `Within a Coordination Space, you define individual **Clash Tests** — each specifying which two packages (or sets of elements) are tested against each other.`,
        subsections: [
          {
            heading: 'Creating a Clash Test',
            items: [
              'Open the Coordination Space → navigate to the "Tests" tab',
              'Click **+ New Test**',
              'Name the test clearly: "Structure vs Mechanical HVAC" rather than "Test 1"',
              'Select **Package A** — the first discipline group',
              'Select **Package B** — the second discipline group being tested against Package A',
              'Set the **Clash Type** (Hard, Hard (Conservative), Clearance, or Duplicate) — covered below',
              'Set the **Tolerance** — the distance threshold for a clash to be reported',
              'Click Save — the test runs automatically with the next model processing',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'Clash Types Explained', level: 'h2',
        content: `ACC Coordinate supports four clash types. Selecting the right type is critical — choosing the wrong one produces either too many false positives or misses real clashes.`,
        code: {
          label: 'Clash Types in ACC Coordinate',
          lines: [
            'HARD CLASH',
            '  → Two objects physically overlap or intersect',
            '  → The most common test type',
            '  → Example: a steel beam intersects an HVAC duct',
            '  → Tolerance: typically 0mm (any intersection is a clash)',
            '',
            'HARD CLASH (CONSERVATIVE)',
            '  → More aggressive version; flags overlaps that might be',
            '    within modelling tolerance but represent real conflicts',
            '  → Use for cast-in items and critical coordination zones',
            '',
            'CLEARANCE CLASH',
            '  → Objects are not touching but are closer than a defined distance',
            '  → Example: duct within 50mm of a beam flange (maintenance clearance)',
            '  → Tolerance: define the minimum required clearance (e.g., 50mm)',
            '',
            'DUPLICATE',
            '  → Same object modelled in two different disciplines',
            '  → Used to detect double-modelling, e.g., columns in both',
            '    structural and architectural models',
          ],
        },
      },
      {
        id: 's4', heading: 'Setting Clash Tolerances', level: 'h2',
        content: `Tolerance defines how much overlap or how close together two elements need to be before ACC reports a clash. Setting this correctly is critical for productive coordination — too tight, and every modelling imprecision is a clash; too loose, and real problems are missed.`,
        items: [
          '**Hard Clash tolerance of 0mm** — any intersection is flagged; use this as the default for major discipline coordination',
          '**Hard Clash tolerance of 5–10mm** — avoids false positives from minor modelling precision issues near boundaries',
          '**Clearance tolerance of 50mm** — typical minimum clearance for maintenance access around MEP services',
          '**Clearance tolerance of 100–150mm** — typical minimum working clearance for service areas and plant rooms',
          'Adjust tolerances based on the building type: tight plant rooms need tighter testing than open-plan office floors',
          'Document your tolerance decisions in the BIM Execution Plan so all discipline leads understand the coordination rules',
        ],
      },
      {
        id: 's5', heading: 'ACC Coordinate vs Navisworks — When to Use Which', level: 'h2',
        content: `ACC Coordinate and Navisworks are both Autodesk clash detection tools. They are complementary, not alternatives — understanding the right tool for each task is part of a mature coordination workflow.`,
        code: {
          label: 'ACC Coordinate vs Navisworks',
          lines: [
            'ACC COORDINATE',
            '  + Runs automatically in the cloud as models update',
            '  + No specialist software needed — browser access for all',
            '  + All team members see the same results simultaneously',
            '  + Integrated with Issues, RFIs, and Docs workflow',
            '  - Less control over element selection and test configuration',
            '  - No Animator, Scripter, or TimeLiner (4D) capability',
            '',
            'NAVISWORKS',
            '  + Highly granular control — test any selection set',
            '  + Advanced result grouping, clustering, and filtering',
            '  + TimeLiner (4D) and Animator workflows',
            '  + Quantification and takeoff from federated model',
            '  - Requires someone to assemble and run the model manually',
            '  - Results only visible to people with Navisworks access',
            '',
            'Best practice: use ACC for continuous, automatic coordination;',
            '  use Navisworks for detailed manual investigation of specific issues',
          ],
        },
      },
      {
        id: 's6', heading: 'Viewing Clash Results', level: 'h2',
        content: `Once a clash test has run, results are available in the Coordination Space viewer — a 3D browser-based model viewer showing all clashing elements.`,
        items: [
          'Open the Coordination Space → select the clash test → click "View Results"',
          'The 3D viewer loads with all clashing element pairs highlighted',
          'Clashes are listed in a panel on the left or right; click any clash to fly to it in the 3D view',
          'The viewer shows the geometry of both clashing elements, including their BIM properties',
          'Use the view controls to orbit, pan, zoom, and section through the model around the clash location',
          'Clashes are colour-coded by status: New (red), Active (orange), Resolved (green), Closed (grey)',
        ],
      },
      {
        id: 's7', heading: 'Coordination Space Run History', level: 'h2',
        content: `ACC tracks the history of clash test runs within a Coordination Space. This allows you to compare clash counts between model versions and track whether coordination is improving over time.`,
        subsections: [
          {
            heading: 'Using Run History Effectively',
            items: [
              'Each time a model is updated and processed, a new Run is recorded in the Coordination Space',
              'The Run History panel shows the date, which models were updated, and clash counts per test',
              'Compare two runs to see: New clashes (introduced in the new model), Resolved clashes (fixed in the new model)',
              'A rising clash count over successive runs indicates coordination is falling behind schedule',
              'A falling clash count indicates the team is resolving issues faster than new ones are introduced — the ideal trend',
              'Export run history as evidence of coordination progress for client reports or dispute resolution',
            ],
          },
        ],
      },
    ],
    takeaways: [
      'ACC Coordinate runs clash tests automatically in the cloud as models are updated — no manual assembly required.',
      'Create Clash Tests by specifying Package A vs Package B, selecting the clash type, and setting the tolerance.',
      'The four clash types are Hard, Hard (Conservative), Clearance, and Duplicate — select based on what coordination problem you are trying to identify.',
      'Tolerance settings control the sensitivity: 0mm for any intersection; 50–150mm for clearance and maintenance access tests.',
      'ACC Coordinate and Navisworks are complementary: ACC for continuous automatic runs; Navisworks for detailed manual investigation.',
      'Run History allows you to track coordination progress over time — clash counts rising or falling tells you whether the team is keeping pace.',
    ],
    resource: { label: 'ACC Clash Detection Configuration Guide', type: 'PDF' },
    quiz: { label: 'Cloud Clash Detection Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-9', title: 'Model Coordination — Setting Up a Coordination Space' },
    next: { id: 'acc-11', title: 'Model Coordination — Reviewing, Assigning & Resolving Clashes' },
  },

  // ============================================================
  // LESSON ACC-11 — Reviewing, Assigning & Resolving Clashes
  // ============================================================
  {
    id: 'acc-11', num: '11',
    title: 'Model Coordination — Reviewing, Assigning & Resolving Clashes',
    topic: 'Model Coordination', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Work through clash results — review, triage, assign to disciplines, track resolution, and run a coordination meeting in ACC.',
    intro: `Detecting clashes is the easy part. The hard part is turning a list of hundreds of results into a managed workflow where each real problem is assigned to the right person, tracked to resolution, and verified as fixed. Without a structured approach to clash review and assignment, coordination meetings become unproductive sessions where everyone looks at the same list and nobody takes ownership. This lesson covers the ACC workflow for turning clash detection outputs into resolved coordination issues.`,
    sections: [
      {
        id: 's1', heading: 'The Clash Review Workflow', level: 'h2',
        content: `The fundamental clash review workflow in ACC Coordinate follows a triage-assign-resolve cycle. Not every detected clash is a real problem — triage is the first step.`,
        code: {
          label: 'Clash Review Cycle',
          lines: [
            '1. TRIAGE',
            '   Review new clash results',
            '   Determine: real clash vs false positive vs known issue',
            '   Set status accordingly',
            '',
            '2. ASSIGN',
            '   For real clashes: assign to responsible discipline',
            '   Set a due date and add a comment explaining the issue',
            '',
            '3. RESOLVE',
            '   Responsible discipline updates their model',
            '   Uploads new version to Docs',
            '   ACC reruns the test — clash disappears from New/Active',
            '',
            '4. VERIFY',
            '   BIM Manager confirms clash is Resolved in the next run',
            '   Clash status moves to Closed',
            '',
            '5. REPORT',
            '   Coordination progress reported to project team',
            '   Trend analysis from run history',
          ],
        },
      },
      {
        id: 's2', heading: 'Clash Statuses in ACC', level: 'h2',
        content: `ACC Coordinate uses a set of clash statuses to track where each detected clash is in the resolution workflow. Understanding these statuses is essential for running an effective coordination process.`,
        items: [
          '**New** — a clash detected for the first time in the most recent model run; needs triage',
          '**Active** — a clash that has been reviewed and is known to be a real coordination problem; assigned for resolution',
          '**Pending** — the clash has been assigned to a discipline but they need to respond or confirm before work starts',
          '**Approved** — a clash that has been reviewed and agreed as acceptable (e.g., within tolerance or by design)',
          '**Resolved** — the clash no longer appears in the model; the fix has been uploaded and reprocessed',
          '**Closed** — the clash has been reviewed in the Resolved state and formally signed off',
        ],
      },
      {
        id: 's3', heading: 'Triaging Clash Results', level: 'h2',
        content: `The first task in any coordination review is triage — identifying which clashes are real problems requiring design resolution and which are false positives, acceptable conditions, or already known.`,
        subsections: [
          {
            heading: 'Triage Decision Framework',
            items: [
              '**Real clash** — two elements genuinely intersect and cannot do so in the built work; set to Active and assign for resolution',
              '**False positive from tolerance** — elements nearly touch but no real conflict exists; set to Approved with a comment',
              '**Accepted clash by design** — the intersection is intentional (e.g., a beam passing through a grating); set to Approved with a comment explaining the decision',
              '**Duplicate clash** — the same physical conflict detected by multiple test combinations; group or close the duplicates',
              '**Known and tracked clash** — already being resolved outside ACC; note in comments and set to Pending',
            ],
          },
        ],
        formula: { label: 'Triage Rule', text: 'Not every detected clash needs resolution — but every detected clash needs a status decision within 48 hours of the run' },
      },
      {
        id: 's4', heading: 'Assigning Clashes', level: 'h2',
        content: `Once a clash is identified as a real coordination problem, it must be assigned to the discipline responsible for the resolution. ACC Coordinate has built-in assignment functionality tied to project members.`,
        subsections: [
          {
            heading: 'Assigning a Clash',
            items: [
              'In the clash result list, click the clash to open its detail panel',
              'Click "Assign" and select the responsible team member from the project member list',
              'Set a **Due Date** — typically tied to the next model coordination deadline',
              'Add a **Comment** explaining what needs to be resolved and why',
              'Optionally, attach a screenshot of the clashing geometry for clarity',
              'The assignee receives an email notification with a link to the clash in ACC',
              'The clash status changes from "New" to "Active" (or "Pending" if awaiting confirmation)',
            ],
          },
        ],
      },
      {
        id: 's5', heading: 'Linking Clashes to Issues', level: 'h2',
        content: `For complex coordination problems that require formal tracking — especially those involving cross-discipline decisions or contractor input — ACC allows you to link a clash directly to an **Issue** in the Build module.`,
        items: [
          'From a clash detail panel, click "Create Issue" to create a linked Build Issue',
          'The Issue inherits the clash location, attached screenshot, and assigned responsible party',
          'The Issue can be tracked through the full Build workflow: Open → In Review → Closed',
          'Linking clashes to Issues is particularly valuable when: the resolution requires a design decision, or a contractor needs to be involved',
          'When the Issue is resolved, the corresponding clash is also updated — the two are linked records',
          'This creates a full audit trail from detection → formal assignment → resolution → sign-off',
        ],
      },
      {
        id: 's6', heading: 'Verifying Resolution', level: 'h2',
        content: `A clash is only truly resolved when the updated model has been uploaded to Docs, reprocessed by ACC Coordinate, and the clash no longer appears in the test results.`,
        subsections: [
          {
            heading: 'Resolution Verification Steps',
            items: [
              'Responsible discipline uploads the updated model to the Shared folder in Docs',
              'ACC Coordinate detects the new model version and triggers automatic reprocessing',
              'After processing (5–30 minutes), re-run the relevant clash test',
              'If the fix is correct, the clash disappears from the Active list and appears in Resolved',
              'BIM Manager reviews the Resolved clash to confirm the fix is correct',
              'If confirmed: set the clash status to Closed',
              'If the fix is not correct or has introduced a new clash: re-assign with updated comments',
            ],
          },
        ],
      },
      {
        id: 's7', heading: 'Running a Coordination Meeting in ACC', level: 'h2',
        content: `ACC Coordinate is designed to be used directly in coordination meetings — projecting the browser-based viewer, navigating through clashes, and assigning responsibility in real time.`,
        items: [
          'Open the Coordination Space on a shared screen at the start of the meeting',
          'Navigate through New clashes first — make triage decisions as a group',
          'Use the 3D viewer to navigate to each clash: orbit, section, and highlight elements for discussion',
          'Assign clashes in real time during the meeting — all assignments are saved immediately',
          'Review the status of previously Assigned clashes — are they resolved or still pending?',
          'End the meeting with a clear list: what was decided, who is responsible, what is the due date',
          'Export the clash report after the meeting as a record of what was reviewed',
        ],
      },
    ],
    takeaways: [
      'The clash review cycle is: Triage (real clash or false positive?) → Assign → Resolve (upload updated model) → Verify → Close.',
      'ACC uses six clash statuses: New, Active, Pending, Approved, Resolved, and Closed — each representing a stage in the coordination workflow.',
      'Triage distinguishes real clashes from false positives and accepted conditions — not every detected clash requires design resolution.',
      'Assign clashes to responsible team members directly in ACC, with a due date and comment explaining the required resolution.',
      'Linking clashes to Build Issues creates a formal, tracked record for complex coordination problems requiring cross-discipline decisions.',
      'A clash is only resolved when the updated model is uploaded to Docs, reprocessed by ACC, and the clash no longer appears in test results.',
    ],
    resource: { label: 'ACC Clash Review Workflow Guide', type: 'PDF' },
    quiz: { label: 'Clash Review & Resolution Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-10', title: 'Model Coordination — Running Clash Detection in the Cloud' },
    next: { id: 'acc-12', title: 'ACC Build — Creating & Managing Issues' },
  },

  // ============================================================
  // LESSON ACC-12 — ACC Build — Creating & Managing Issues
  // ============================================================
  {
    id: 'acc-12', num: '12',
    title: 'ACC Build — Creating & Managing Issues',
    topic: 'Issues & RFIs', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Create, assign, track, and close construction issues in ACC Build — the primary tool for managing observations, defects, and tasks on site.',
    intro: `Issues in ACC Build are the day-to-day record of what needs attention on a construction project — a cracked slab, a non-conforming installation, a safety hazard, a design discrepancy identified on site. Unlike informal whatsapp messages or spreadsheet punch lists, ACC Issues are formally tracked, assigned, photographed, geolocated, and linked to the drawings and models they relate to. This lesson covers how to use the Issues workflow effectively from creation to close-out.`,
    sections: [
      {
        id: 's1', heading: 'What are Issues in ACC Build?', level: 'h2',
        content: `An **Issue** in ACC Build is a formal record of anything on a construction project that requires attention, action, or decision. Issues replace the informal systems (spreadsheets, text messages, printed punch lists) that most construction sites have historically relied on.`,
        items: [
          '**Observations** — things noticed on site that need to be recorded: "safety handrail missing from Level 3 stair"',
          '**Defects** — work that does not meet the specified standard: "tile grouting colour non-conforming to specification"',
          '**Design queries** — questions arising on site that need a design response: "column position conflicts with door swing"',
          '**Tasks** — actions required of a specific party by a specific date: "clear surplus material from Level 2 corridor"',
          '**Safety issues** — hazards or non-compliances: "temporary works not properly secured — IMMEDIATE ACTION"',
          'Issues can be created on the desktop browser or the mobile app on site — the mobile app is the primary tool for site teams',
        ],
        formula: { label: 'Issue Principle', text: 'Every site observation that requires action must be an Issue — if it isn\'t recorded, it didn\'t happen' },
      },
      {
        id: 's2', heading: 'Issue Types and Subtypes', level: 'h2',
        content: `ACC Build organises Issues by **Type** and **Subtype** — a two-level classification system that helps with filtering, reporting, and assigning responsibility.`,
        code: {
          label: 'Example Issue Types and Subtypes',
          lines: [
            'Type: Design',
            '  Subtypes: Architectural, Structural, MEP, Civil',
            '',
            'Type: Quality',
            '  Subtypes: Workmanship, Materials, Non-Conformance, Defect',
            '',
            'Type: Safety',
            '  Subtypes: Hazard, Near Miss, Incident, Compliance',
            '',
            'Type: RFI',
            '  Subtypes: Design Clarification, Scope Query, Technical Query',
            '',
            'Type: Commissioning',
            '  Subtypes: Test Failure, Punchlist, Handover Item',
            '',
            'Note: Issue Types and Subtypes are configured by the',
            'Project Admin in Project Settings → Build → Issue Configuration',
          ],
        },
      },
      {
        id: 's3', heading: 'Creating an Issue', level: 'h2',
        content: `Issues can be created from the browser or the mobile app. The mobile creation workflow is the most common for site observations — create the issue while standing in front of the problem.`,
        subsections: [
          {
            heading: 'Creating an Issue (Browser or Mobile)',
            items: [
              'Open ACC Build → Issues → click **+ New Issue** (browser) or the + button (mobile)',
              'Select the **Issue Type** and **Subtype** from the configured list',
              'Enter the **Title** — be specific: "Level 3 — Column C4 alignment off by 35mm" not "Column issue"',
              'Write a **Description** with enough detail for the assignee to understand without visiting site',
              'Attach **Photos** — take from multiple angles; show the issue clearly against a scale reference if possible',
              'Set the **Location** — pin on the floor plan, model, or enter a text location',
              'Assign to the **Responsible Party** — the person or company who must resolve the issue',
              'Set a **Due Date** for resolution',
              'Set the **Priority** if applicable: Critical, High, Medium, Low',
              'Click Save — the issue is created and the assignee is notified immediately',
            ],
          },
        ],
      },
      {
        id: 's4', heading: 'Issue Statuses and Workflow', level: 'h2',
        content: `ACC Build Issues follow a status workflow from creation through resolution. Understanding the status progression helps teams manage accountability and reporting.`,
        code: {
          label: 'Issue Status Workflow',
          lines: [
            'Open',
            '  → Issue created; awaiting action from the assignee',
            '',
            'In Review',
            '  → Assignee has responded or taken action; under review by creator',
            '',
            'Closed',
            '  → Issue resolved and confirmed by the creator or BIM Manager',
            '',
            'Void',
            '  → Issue created in error or no longer relevant; cancelled',
            '',
            'Note: Only the issue creator or a Project Admin can close or void',
            '  an issue — the assignee cannot close their own issues',
          ],
        },
      },
      {
        id: 's5', heading: 'Locating Issues on Drawings and Models', level: 'h2',
        content: `One of ACC Build's most powerful features is the ability to locate an issue precisely on a 2D drawing or a 3D model. This eliminates the ambiguity of text-only descriptions.`,
        items: [
          'When creating or editing an issue, click "Add Location"',
          'Choose to locate on a **Sheet** (2D drawing), a **3D model**, or a **Photo** (markup on a site photo)',
          'For Sheet location: select the relevant drawing from the Sheets module and click the precise location',
          'For 3D model location: the browser-based 3D viewer opens; orbit to the location and click the element',
          'The issue is then pinned to that exact location — visible to anyone viewing the drawing or model',
          'Site managers walking the floor can filter the drawings to show only issues in their zone or on their level',
        ],
      },
      {
        id: 's6', heading: 'Managing Issues Over Time', level: 'h2',
        content: `The Issues log becomes increasingly valuable as the project progresses — as an auditable record of every problem identified and resolved. Effective management keeps the log clean and actionable.`,
        items: [
          'Review the Issues list weekly: filter by status "Open" to see everything awaiting action',
          'Filter by "Overdue" to identify issues past their due date — these need attention immediately',
          'Filter by Assignee to see everything assigned to a specific person or company',
          'Filter by Type to review all Safety issues or all Quality issues separately',
          'Use the Insights module to generate issue reports by type, status, assignee, or date range',
          'Export the full issues list as a CSV or PDF for contract administration and handover records',
        ],
      },
      {
        id: 's7', heading: 'Closing and Verifying Issues', level: 'h2',
        content: `An issue is only closed when the resolution has been verified. In ACC Build, only the issue creator or a Project Admin can close an issue — the assignee marks it as "In Review" when they believe the work is done.`,
        subsections: [
          {
            heading: 'Close-out Process',
            items: [
              'Assignee completes the work and marks the issue "In Review," adding a comment and photo of the resolution',
              'Creator or BIM Manager receives a notification that the issue is ready for review',
              'Creator visits site (or reviews the photo evidence) to confirm the resolution is satisfactory',
              'If satisfactory: mark the issue "Closed" — it is permanently recorded as resolved',
              'If not satisfactory: add a comment explaining what is still required and re-open the issue',
              'Closed issues cannot be edited or re-opened — they are permanent audit records',
            ],
          },
        ],
      },
    ],
    takeaways: [
      'Issues in ACC Build formally record any site observation, defect, design query, or task requiring attention — replacing spreadsheets and text messages.',
      'Issues are classified by Type (Quality, Safety, Design) and Subtype, configured by the Project Admin to match the project workflow.',
      'Create an Issue with a specific title, description, photos, precise location on drawing or model, assignee, and due date.',
      'The Issue status workflow is: Open → In Review → Closed (or Void); only creators and Admins can close an issue.',
      'Locate issues on 2D sheets or 3D models to eliminate ambiguity about exactly where the problem is.',
      'Only the creator or a Project Admin can close an issue — the assignee marks "In Review" and the creator verifies the resolution.',
    ],
    resource: { label: 'ACC Build Issues Workflow Guide', type: 'PDF' },
    quiz: { label: 'ACC Build Issues Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-11', title: 'Model Coordination — Reviewing, Assigning & Resolving Clashes' },
    next: { id: 'acc-13', title: 'ACC Build — RFI Workflow from Creation to Close-out' },
  },

  // ============================================================
  // LESSON ACC-13 — RFI Workflow from Creation to Close-out
  // ============================================================
  {
    id: 'acc-13', num: '13',
    title: 'ACC Build — RFI Workflow from Creation to Close-out',
    topic: 'Issues & RFIs', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Manage the full RFI lifecycle in ACC Build — creation, routing, response, and close-out with formal tracking.',
    intro: `A Request for Information (RFI) is one of the most consequential documents in construction: a formal query from the contractor to the design team that, when answered, potentially changes what gets built. Poorly managed RFIs — questions answered informally, responses not recorded, revisions not issued — are a leading cause of construction disputes. ACC Build's RFI module provides the structure to manage every query formally, with a traceable ball-in-court record from question to answer to close-out.`,
    sections: [
      {
        id: 's1', heading: 'What is an RFI?', level: 'h2',
        content: `A **Request for Information (RFI)** is a formal written query from the contractor to the design team (architect, engineer, or consultant) seeking clarification on an aspect of the design, specification, or contract documents. It is one of the primary channels of formal communication during construction.`,
        items: [
          'RFIs are raised when the contractor encounters information that is unclear, missing, conflicting, or apparently incorrect',
          'Unlike an Issue (which records a problem on site), an RFI seeks information or a decision from the design team',
          'Every RFI must have a formal written response from the designer — verbal responses are not acceptable under most contracts',
          'The response to an RFI may result in a revised drawing, a specification change, or a change in scope — potentially triggering a cost change order',
          'RFI response times are usually contractually mandated — typically 7–14 working days — and late responses can entitle the contractor to an extension of time',
        ],
        formula: { label: 'RFI Purpose', text: 'RFI = formal channel for contractors to get written design decisions — not informal queries, not site instructions' },
      },
      {
        id: 's2', heading: 'Creating an RFI in ACC', level: 'h2',
        content: `The contractor creates an RFI in ACC Build and routes it to the relevant designer or consultant. The RFI system tracks exactly who has the "ball in court" — whose action is required to move the RFI forward.`,
        subsections: [
          {
            heading: 'Creating an RFI',
            items: [
              'In ACC Build, navigate to the RFI section in the left sidebar',
              'Click **+ New RFI**',
              'Enter the **RFI Subject** — be specific: "Grid C5 column base plate connection detail — specification conflict"',
              'Write the **Question** — detailed description of what needs to be clarified, including all relevant drawing references',
              'Attach supporting **Documents** — the conflicting drawings, specification clauses, or site photos',
              'Set the **Required Response Date** — based on contractual response time requirements',
              'Assign the **RFI Manager** — the person in the design team responsible for coordinating the response',
              'Optionally set the **Assignee** — the specific designer who should provide the technical response',
              'Click Save — the RFI is created and the RFI Manager and Assignee are notified',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'The Ball-in-Court Tracking System', level: 'h2',
        content: `ACC Build's RFI workflow uses a "ball-in-court" model to track responsibility. At any point in the RFI lifecycle, it is clear exactly who currently holds responsibility for the next action.`,
        code: {
          label: 'Ball-in-Court RFI Workflow',
          lines: [
            'CONTRACTOR creates RFI',
            '  Ball-in-court: Design Manager',
            '',
            'DESIGN MANAGER reviews and routes to Structural Engineer',
            '  Ball-in-court: Structural Engineer',
            '',
            'STRUCTURAL ENGINEER drafts response',
            '  Ball-in-court: Design Manager (for review)',
            '',
            'DESIGN MANAGER reviews response, adds official response',
            '  Ball-in-court: Contractor',
            '',
            'CONTRACTOR reviews response',
            '  If satisfactory → Close the RFI',
            '  If further clarification needed → raise a follow-up RFI',
            '',
            'ACC displays the current ball-in-court party clearly',
            'on every open RFI, with the overdue date highlighted if',
            'the contractual response time has elapsed',
          ],
        },
      },
      {
        id: 's4', heading: 'Responding to an RFI', level: 'h2',
        content: `The design team responds to RFIs through the same interface — adding a formal written response, attaching revised drawings or specifications if applicable, and closing the loop with the contractor.`,
        subsections: [
          {
            heading: 'Response Steps',
            items: [
              'Open the RFI assigned to you in ACC Build',
              'Review the question and all attached documents',
              'Click "Add Response" to write the formal technical response',
              'Attach any revised drawings, calculations, or specifications that form part of the response',
              'If the response results in a drawing revision, issue a transmittal for the revised drawing separately',
              'Set the response type: Accepted, Accepted as Noted, Revise and Resubmit, or For Record Only',
              'The contractor is notified when the response is submitted',
            ],
          },
        ],
      },
      {
        id: 's5', heading: 'RFI Statuses', level: 'h2',
        content: `ACC tracks the status of each RFI through its lifecycle. Status visibility is important for project managers monitoring open queries and their potential programme impact.`,
        items: [
          '**Open** — RFI created and awaiting initial routing or response',
          '**In Review** — being reviewed by the design manager or assigned consultant',
          '**Answered** — the designer has provided a formal written response; awaiting contractor review',
          '**Closed** — contractor has accepted the response and the RFI is formally complete',
          '**Void** — RFI raised in error or superseded by another document; cancelled',
          'Overdue RFIs (past the Required Response Date) are highlighted in the RFI list with a red indicator',
        ],
      },
      {
        id: 's6', heading: 'RFI Log and Reporting', level: 'h2',
        content: `The RFI Log in ACC Build is a complete register of all RFIs on the project — a critical contract administration document that must be maintained throughout the project.`,
        items: [
          'The RFI Log shows all RFIs with key data: number, subject, date raised, required response date, status, days overdue',
          'Filter by status to identify all Open, Answered, or Overdue RFIs',
          'Filter by discipline to identify all structural, MEP, or architectural queries separately',
          'Export the full RFI log as a CSV or PDF for contract administration records and dispute preparation',
          'A large number of Open or Overdue RFIs is a programme risk indicator — escalate to the project manager if the backlog is growing',
          'RFI response time performance is reportable in the Insights module — use this to manage design team accountability',
        ],
      },
      {
        id: 's7', heading: 'Common RFI Mistakes and Best Practices', level: 'h2',
        content: `**Mistake:**
Answering RFIs verbally on site and not creating a formal ACC RFI record. Verbal instructions are not contractually binding — all design decisions made on site must be recorded formally in ACC.

**Mistake:**
Creating vague RFI subjects like "Question about Level 3." The RFI title and question must be specific enough that the designer can identify exactly what is being asked without a phone call.

**Best Practice:**
Link each RFI to the relevant drawing or specification clause. ACC allows you to attach documents and pin the location on a drawing — always use both to eliminate ambiguity about where the query arises.`,
      },
    ],
    takeaways: [
      'An RFI is a formal written query from the contractor to the design team seeking clarification on design, specification, or contract documents.',
      'Create an RFI with a specific subject, detailed question, supporting documents, required response date, and assigned RFI Manager.',
      'ACC Build\'s ball-in-court system shows exactly who is responsible for the next action on every RFI at any time.',
      'Design teams respond by adding a formal written response and attaching any revised documents; the contractor is notified when the response is submitted.',
      'RFI statuses are: Open, In Review, Answered, Closed, and Void — overdue RFIs are highlighted with the days overdue.',
      'Never answer RFIs verbally on site — all design decisions must be formally recorded in ACC to be contractually binding.',
    ],
    resource: { label: 'ACC Build RFI Workflow Guide', type: 'PDF' },
    quiz: { label: 'RFI Workflow Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-12', title: 'ACC Build — Creating & Managing Issues' },
    next: { id: 'acc-14', title: 'ACC Build — Submittals, Meetings & Daily Logs' },
  },

  // ============================================================
  // LESSON ACC-14 — Submittals, Meetings & Daily Logs
  // ============================================================
  {
    id: 'acc-14', num: '14',
    title: 'ACC Build — Submittals, Meetings & Daily Logs',
    topic: 'Construction Management', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Manage contractor submittals, meeting minutes, and daily site logs in ACC Build — the core construction management tools.',
    intro: `Beyond RFIs and Issues, construction management requires tracking what the contractor is proposing to use (Submittals), what was agreed in each meeting (Meeting Minutes), and what happened on site each day (Daily Logs). In ACC Build, these three modules work together to maintain a comprehensive record of the project's construction phase — a record that becomes increasingly important as the project nears handover and any post-completion disputes need to be resolved.`,
    sections: [
      {
        id: 's1', heading: 'Submittals in ACC Build', level: 'h2',
        content: `A **Submittal** is a document or sample submitted by the contractor to the design team for approval before work proceeds. Submittals confirm that the contractor proposes to use materials and products that meet the specification requirements.`,
        items: [
          '**Shop drawings** — fabrication drawings produced by a specialist subcontractor (e.g., structural steelwork, precast concrete)',
          '**Product data** — manufacturer data sheets, technical specifications, test certificates for specified materials',
          '**Samples** — physical or photographic samples of finishes, materials, and components for approval',
          '**Method statements** — the contractor\'s proposed methods for executing specific aspects of the work',
          '**O&M Manuals** — at the end of the project, Operation and Maintenance manuals are also managed as submittals',
          'The submittal approval workflow prevents the contractor from installing non-conforming materials, protecting the client and the designer against defects',
        ],
        formula: { label: 'Submittal Purpose', text: 'Submittal = contractor seeking approval before spending money on materials that might not comply with the specification' },
      },
      {
        id: 's2', heading: 'Managing Submittals in ACC Build', level: 'h2',
        content: `ACC Build provides a structured submittal workflow with ball-in-court tracking similar to the RFI process.`,
        subsections: [
          {
            heading: 'Submittal Workflow',
            items: [
              'Contractor creates a **Submittal Package** in ACC Build → Submittals → + New Submittal',
              'Assigns a spec section number (e.g., "Section 05 12 00 — Structural Steel") and a submittal number',
              'Uploads the shop drawings, data sheets, or samples as attachments',
              'Assigns the submittal to the relevant designer for review',
              'Designer reviews the submittal and selects a review code:',
              '  **A — Approved**: proceed with fabrication/installation as submitted',
              '  **B — Approved as Noted**: proceed subject to the design team\'s marked-up comments',
              '  **C — Revise and Resubmit**: the submittal does not meet requirements; resubmit with corrections',
              '  **D — For Information Only**: no approval required; received for record',
              'Designer returns the reviewed submittal with comments and marked-up drawings',
              'Contractor acknowledges the response and closes the submittal',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'Meeting Minutes in ACC Build', level: 'h2',
        content: `The **Meetings** module in ACC Build provides a structured format for creating, distributing, and tracking actions from project meetings.`,
        code: {
          label: 'Meeting Record Structure in ACC',
          lines: [
            'Meeting Header',
            '  → Meeting name (e.g., "Weekly Coordination Meeting — Week 14")',
            '  → Date, time, location (physical or video call)',
            '  → Attendees (from project member list)',
            '',
            'Agenda Items',
            '  → Structured list of discussion topics',
            '  → Each agenda item can have a discussion note',
            '',
            'Action Items',
            '  → Specific actions arising from the meeting',
            '  → Each action: what, who, by when',
            '  → Actions are linked to individual project members',
            '  → Outstanding actions automatically appear on the next meeting',
            '',
            'Distribution',
            '  → Meeting minutes distributed by email within ACC',
            '  → Recipients notified of their assigned actions',
          ],
        },
      },
      {
        id: 's4', heading: 'Action Item Tracking', level: 'h2',
        content: `Actions from meetings are tracked in ACC Build and roll forward to subsequent meetings. This prevents the common pattern where the same action items are noted in successive meetings without anyone taking responsibility.`,
        items: [
          'Every action item has a responsible person, a description, and a due date',
          'Open action items automatically appear at the top of the next meeting of the same series',
          'Project members receive email reminders for approaching action due dates',
          'Action items can be linked to Issues or RFIs for cross-referencing',
          'The action item register provides a historical record of every decision and commitment made in project meetings',
          'Filter by person to see all actions assigned to a specific individual across all meetings',
        ],
      },
      {
        id: 's5', heading: 'Daily Logs in ACC Build', level: 'h2',
        content: `**Daily Logs** (also called Site Diaries or Daily Journals) are the day-by-day record of what happened on site. They are one of the most important documents in construction disputes — a contemporaneous record of delays, weather conditions, workforce levels, and events on site.`,
        subsections: [
          {
            heading: 'Daily Log Components',
            items: [
              '**Date and Weather** — automatically prompted; include temperature, precipitation, and visibility (wind particularly relevant to crane operations)',
              '**Labour** — workforce numbers by trade and company on site that day',
              '**Equipment** — plant and equipment on site (cranes, excavators, concrete pumps)',
              '**Materials Delivered** — deliveries received (material, quantity, supplier)',
              '**Work Completed** — what was built or installed that day, by area and activity',
              '**Incidents** — any accidents, near misses, or safety observations',
              '**Delays** — any disruption to the programme and the cause',
              '**Visitors** — notable visitors to site (client, designer, building inspector)',
            ],
          },
        ],
        formula: { label: 'Daily Log Rule', text: 'A daily log is only useful if completed daily — a retrospective log written a week later is often inadmissible in a dispute' },
      },
      {
        id: 's6', heading: 'Creating and Reviewing Daily Logs', level: 'h2',
        content: `Daily Logs are typically completed by the site manager or site foreman at the end of each working day, using the mobile app on site.`,
        items: [
          'Open ACC Mobile App → Build → Daily Logs → + New Log',
          'The log date is pre-filled with today\'s date; confirm or adjust',
          'Complete each section: weather, labour, materials, work completed, incidents',
          'Attach photos to illustrate work completed or issues encountered',
          'Submit the log — it is timestamped and locked against further editing',
          'Project Administrators can review all daily logs in ACC Build → Daily Logs',
          'Export a range of daily logs as a PDF or CSV for contract administration or dispute purposes',
        ],
      },
      {
        id: 's7', heading: 'Build Module Integration', level: 'h2',
        content: `The real value of the Build module is how its components work together. Issues, RFIs, Submittals, Meetings, and Daily Logs are not isolated records — they are linked and cross-referenced.`,
        subsections: [
          {
            heading: 'Integration Examples',
            items: [
              'An Issue on site raises a question → an RFI is created and linked to the Issue',
              'An RFI response results in a design change → a revised drawing is issued via Transmittal and the RFI is closed',
              'A design change affects a Submittal → the submittal is flagged and returned for revision with the updated specification',
              'A delay event is recorded in the Daily Log → it is referenced in the next meeting and an action is created to quantify the impact',
              'All of these records together form the project\'s as-built data — critical evidence at practical completion and handover',
            ],
          },
        ],
      },
    ],
    takeaways: [
      'Submittals are documents submitted by the contractor for designer approval before work proceeds — shop drawings, product data, method statements, samples.',
      'The submittal review codes are A (Approved), B (Approved as Noted), C (Revise and Resubmit), and D (For Information Only).',
      'Meeting Minutes in ACC Build include agenda items, discussion notes, and action items assigned to named individuals with due dates.',
      'Action items from meetings roll forward automatically to subsequent meetings until they are closed — preventing the common pattern of recurring, unresolved actions.',
      'Daily Logs record the contemporaneous site record: weather, labour, materials, work completed, incidents, and delays.',
      'Build module components (Issues, RFIs, Submittals, Meetings, Logs) are linked and cross-referenced — together they form the project\'s as-built evidence record.',
    ],
    resource: { label: 'ACC Build Construction Management Guide', type: 'PDF' },
    quiz: { label: 'Submittals, Meetings & Daily Logs Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-13', title: 'ACC Build — RFI Workflow from Creation to Close-out' },
    next: { id: 'acc-15', title: 'Cost Management — Budgets, Contracts & Change Orders for BIM Practitioners' },
  },

  // ============================================================
  // LESSON ACC-15 — Cost Management
  // ============================================================
  {
    id: 'acc-15', num: '15',
    title: 'Cost Management — Budgets, Contracts & Change Orders for BIM Practitioners',
    topic: 'Cost Management', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Understand how ACC Cost Management works — budget setup, contract management, change orders, and the link between BIM and cost control.',
    intro: `Cost management has traditionally been disconnected from the BIM model — a separate spreadsheet or procurement system that never talks to the design or construction platform. ACC Cost Management changes this by integrating budget, contracts, and change management directly into the same platform as documents, models, and site records. For BIM practitioners, understanding how Cost Management connects to the broader ACC workflow is increasingly a required skill — especially as clients and contractors expect BIM to support cost reporting as well as coordination.`,
    sections: [
      {
        id: 's1', heading: 'What is ACC Cost Management?', level: 'h2',
        content: `ACC Cost Management is the financial management layer of the ACC platform. It covers the full project cost lifecycle — from initial budget through contracts, change events, change orders, and final cost reporting.`,
        items: [
          '**Budget** — the financial plan for the project, broken down by cost codes or work packages',
          '**Contracts** — formal contracts with the main contractor and subcontractors, stored and managed within ACC',
          '**Change Events** — events on the project that may give rise to a cost change (design changes, unforeseen conditions)',
          '**Change Orders** (or Variation Orders) — formal instructions to change the scope, with agreed cost and time impacts',
          '**Cost Reports** — live reporting of budget vs committed cost vs actual expenditure',
          'Cost Management sits alongside Docs, Build, and Coordinate — all sharing the same project data',
        ],
        formula: { label: 'Cost Lifecycle', text: 'Budget → Contract Sum → Change Orders → Revised Contract Sum → Final Account' },
      },
      {
        id: 's2', heading: 'Setting Up a Budget', level: 'h2',
        content: `The project budget is the financial baseline against which all costs are measured. Setting up the budget correctly in ACC Cost Management is the first step before contracts or changes can be effectively tracked.`,
        subsections: [
          {
            heading: 'Budget Setup Steps',
            items: [
              'Navigate to the Cost module → Budget',
              'Define the **Budget Code Structure** — the hierarchy of cost codes that break the project down (e.g., by element, by trade, by BCIS category)',
              'Enter the budget amount for each code — this is the client\'s approved budget or the design estimate',
              'Add contingency and provisional sums as separate line items',
              'The budget total represents the project\'s financial ceiling',
              'Budget cannot be exceeded without a formal budget revision (approved change order or client instruction)',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'Contracts in ACC', level: 'h2',
        content: `Contracts in ACC Cost Management are records of formal agreements with the main contractor and subcontractors. Managing contracts within ACC links financial commitments directly to the project data.`,
        code: {
          label: 'Contract Record Structure',
          lines: [
            'Contract: Main Contract',
            '  → Contractor: ABC Contractors Ltd',
            '  → Contract Type: Lump Sum / Remeasured / Cost Plus',
            '  → Contract Sum: [value]',
            '  → Contract Date: [date]',
            '  → Practical Completion Date: [date]',
            '  → Retention %: [typically 5% or 2.5%]',
            '',
            'Contract: Structural Steel Subcontract',
            '  → Subcontractor: Steel Co Ltd',
            '  → Contract Sum: [value]',
            '  → Scope: Structural steelwork, levels 1-12',
            '',
            'Each contract links to:',
            '  → The relevant cost codes in the budget',
            '  → Change orders that modify the contract sum',
            '  → Payment applications and certifications',
          ],
        },
      },
      {
        id: 's4', heading: 'Change Events and Change Orders', level: 'h2',
        content: `A **Change Event** is any event that may affect the project cost — a design change, an RFI response that changes scope, an unforeseen condition, a client instruction. Change Events are the precursor to formal Change Orders (Variation Orders).`,
        items: [
          '**Change Event** — recorded as soon as a potential cost impact is identified; may or may not result in a formal change order',
          '**Change Order / Variation Order** — a formal, signed instruction to change the scope with an agreed price and time impact',
          'In ACC Cost Management, Change Events and Change Orders are linked — providing an audit trail from the initial notification to the agreed price',
          'Link a Change Event to an RFI, Issue, or Transmittal that triggered the change — maintaining the connection between design decisions and cost impacts',
          'Change Orders require approval before they are executed — the approval workflow in ACC tracks who has approved what',
          'Approved Change Orders automatically update the Contract Sum in ACC',
        ],
      },
      {
        id: 's5', heading: 'Cost Reporting in ACC', level: 'h2',
        content: `ACC Cost Management provides live cost reporting — showing the relationship between the original budget, the current contract position, committed costs, and actual expenditure.`,
        code: {
          label: 'Cost Report Structure',
          lines: [
            'Approved Budget',
            '  → The client\'s original financial approval',
            '',
            'Current Contract Sum',
            '  → Original Contract Sum + Approved Change Orders',
            '',
            'Estimated Final Cost (EFC)',
            '  → Current Contract Sum + Pending Change Events + Contingency forecast',
            '',
            'Committed Cost',
            '  → Subcontract values + purchase orders issued',
            '',
            'Actual Cost (Expenditure)',
            '  → Payment applications certified to date',
            '',
            'Budget Variance',
            '  → Approved Budget − Estimated Final Cost',
            '  → Negative = over budget; positive = under budget',
          ],
        },
      },
      {
        id: 's6', heading: 'BIM and Cost Integration', level: 'h2',
        content: `The deeper value of ACC Cost Management for BIM practitioners is the connection between the BIM model and cost data. This connection enables quantity-driven cost forecasting and links design changes to their cost impacts automatically.`,
        items: [
          'The ACC Takeoff module extracts quantities from 2D drawings and 3D models, feeding directly into Cost',
          'A change in the design (updated BIM model) → updated quantities in Takeoff → revised cost estimate in Cost',
          'This creates a live connection between model changes and financial impact — the core promise of 5D BIM',
          'For practitioners, this means that coordination decisions (changing a structural element, relocating services) have visible, traceable cost implications',
          'The client can see cost reports linked to the current model state — not to a stale estimate produced months ago',
        ],
      },
      {
        id: 's7', heading: 'Cost Management for Non-Financial BIM Practitioners', level: 'h2',
        content: `Most BIM practitioners are not quantity surveyors or cost managers — they are architects, engineers, or BIM coordinators. However, understanding ACC Cost Management well enough to support the QS team, interpret cost reports, and understand the connection between design decisions and cost is increasingly expected.`,
        subsections: [
          {
            heading: 'What BIM Practitioners Need to Know',
            items: [
              'How to link an RFI response to a Change Event — so the QS team can quantify the cost impact',
              'How to link a design revision to a Change Order — maintaining the audit trail from design change to financial instruction',
              'How to interpret a cost report — understanding budget variance, EFC, and contingency draw-down',
              'How Takeoff uses model quantities — and why model accuracy matters for cost forecasting',
              'When to notify the QS team of design changes — before they are issued, not after construction has started',
            ],
          },
        ],
      },
    ],
    takeaways: [
      'ACC Cost Management covers the full financial lifecycle: Budget → Contracts → Change Events → Change Orders → Cost Reports.',
      'The budget is set up using a cost code structure aligned to the project breakdown; it is the financial baseline against which all costs are measured.',
      'Change Events record potential cost impacts; Change Orders are the formal, approved, signed instructions to change scope with agreed price and time.',
      'ACC Cost Reports show: Approved Budget, Contract Sum, Estimated Final Cost, Committed Cost, and actual expenditure in one view.',
      'The Takeoff module extracts quantities from BIM models and 2D drawings, feeding directly into cost estimates for live 5D BIM capability.',
      'BIM practitioners need to understand how to link design changes (RFIs, revisions) to Change Events so the QS team can quantify cost impacts promptly.',
    ],
    resource: { label: 'ACC Cost Management Overview Guide', type: 'PDF' },
    quiz: { label: 'Cost Management Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-14', title: 'ACC Build — Submittals, Meetings & Daily Logs' },
    next: { id: 'acc-16', title: 'Schedule — Linking the Construction Programme to the Model' },
  },

  // ============================================================
  // LESSON ACC-16 — Schedule — Linking the Construction Programme to the Model
  // ============================================================
  {
    id: 'acc-16', num: '16',
    title: 'Schedule — Linking the Construction Programme to the Model',
    topic: 'Schedule', cat: 'intermediate', readTime: '9 min', free: false,
    desc: 'Connect the construction programme to the BIM model in ACC Schedule — 4D simulation, progress tracking, and programme management in the cloud.',
    intro: `A construction programme sits in a Primavera or MS Project file that nobody on the design team can open, while the BIM model sits in Revit and Navisworks files that few on the contracting team can access. ACC Schedule exists to bridge this gap — bringing the programme into the same platform as the model, the documents, and the site records. The result is 4D visibility that used to require specialist software, available to everyone on the project in a browser.`,
    sections: [
      {
        id: 's1', heading: 'What is ACC Schedule?', level: 'h2',
        content: `**ACC Schedule** is the construction programme management module within ACC. It allows teams to import, manage, and update the project programme within ACC — and link programme activities directly to BIM model elements for 4D simulation.`,
        items: [
          'Import construction programmes from Primavera P6, Microsoft Project, or CSV format',
          'View and update the programme directly in ACC — no Primavera licence required for most project members',
          'Link programme activities to model elements, floors, or areas in the Coordinate module',
          'Run browser-based 4D simulations showing the construction sequence over time',
          'Track planned vs actual progress against the programme baseline',
          'Integrate programme data with Issues and Daily Logs for real-time progress comparison',
        ],
        formula: { label: '4D BIM Concept', text: '3D Model + Time (Programme) = 4D BIM: seeing what should be built when, and comparing to what was actually built' },
      },
      {
        id: 's2', heading: 'Importing a Programme', level: 'h2',
        content: `The ACC Schedule module accepts programme files from the major scheduling tools used in construction. The import process preserves the activity hierarchy, dates, and dependencies.`,
        subsections: [
          {
            heading: 'Programme Import Steps',
            items: [
              'Navigate to the Schedule module in ACC',
              'Click **Import Schedule** and choose your format: Primavera P6 (XER), MS Project (MPP/XML), or CSV',
              'Upload the file — ACC processes it and creates the schedule structure',
              'Review the imported activities: check that dates, durations, and hierarchy are correct',
              'Set the **Baseline** — the original approved programme dates against which progress will be measured',
              'Share the schedule with project members who need programme visibility',
              'Update the schedule by importing a revised file or editing activities directly in ACC',
            ],
          },
        ],
      },
      {
        id: 's3', heading: 'The Programme in ACC — Viewing and Navigating', level: 'h2',
        content: `Once imported, the programme is displayed in ACC as a Gantt chart with additional views for resource and progress tracking.`,
        code: {
          label: 'Schedule Views in ACC',
          lines: [
            'GANTT VIEW',
            '  → Traditional bar chart programme',
            '  → Activities shown as horizontal bars with dependencies',
            '  → Baseline dates shown as reference bars below current bars',
            '',
            'ACTIVITY TABLE',
            '  → Spreadsheet view of all activities with all fields visible',
            '  → Sortable and filterable by responsible company, area, trade',
            '',
            '4D VIEW (linked to model)',
            '  → 3D model shown with time slider',
            '  → Model elements colour-coded by scheduled vs actual vs late',
            '',
            'PROGRESS TRACKING',
            '  → % Complete per activity tracked against baseline',
            '  → Programme delay/float calculated automatically',
          ],
        },
      },
      {
        id: 's4', heading: 'Linking Activities to Model Elements', level: 'h2',
        content: `The 4D connection in ACC Schedule is made by linking programme activities to model elements in the Coordinate module. When linked, changes to the programme automatically reflect in the 4D visualisation.`,
        subsections: [
          {
            heading: 'Linking Steps',
            items: [
              'Open the Schedule module → select the activity to link',
              'Click "Link to Model" — the Coordinate viewer opens alongside the schedule',
              'Select model elements in the 3D viewer that correspond to the activity',
              '  Example: "Structural Steel — Level 3" activity linked to all Level 3 steel elements',
              'Confirm the link — the activity and elements are now connected',
              'Repeat for all key activities — focus on major milestones and trade packages rather than every activity',
              'In the 4D view, use the time slider to animate the construction sequence',
            ],
          },
        ],
      },
      {
        id: 's5', heading: 'Progress Tracking', level: 'h2',
        content: `ACC Schedule supports progress tracking — updating the "% Complete" field for each activity to show how the actual construction compares to the planned programme.`,
        items: [
          'Progress updates are typically entered weekly by the site manager or programme manager',
          'Update % Complete for each in-progress activity based on site observations or Daily Log data',
          'ACC calculates the **Schedule Performance Index (SPI)** — a ratio of earned value to planned value',
          'SPI < 1.0 means the project is behind schedule; SPI > 1.0 means ahead',
          'The 4D view shows model elements in different colours: on-time (green), ahead (blue), behind (red)',
          'Progress data integrates with Issues — delays identified in Issues can be flagged against the affected programme activities',
        ],
      },
      {
        id: 's6', heading: '4D Simulation for Project Communication', level: 'h2',
        content: `The 4D view in ACC Schedule is one of the most effective communication tools on a construction project — showing non-technical stakeholders (client, local authority, community) what will be built and when.`,
        items: [
          'Use the 4D view at the start of a project to communicate the construction sequence to the client',
          'Use it in progress meetings to show what is planned vs what has actually been completed',
          'Export the 4D simulation as a video for client presentations or public consultation',
          'For complex projects with multiple trade interfaces, use the 4D view to identify sequencing conflicts before they happen on site',
          'Link critical milestones (practical completion, sectional completion) to the model for visual tracking',
        ],
      },
      {
        id: 's7', heading: 'Schedule Integration with the Wider ACC Platform', level: 'h2',
        content: `The Schedule module is most powerful when integrated with the rest of ACC — not used in isolation.`,
        subsections: [
          {
            heading: 'Integration Points',
            items: [
              'Link programme activities to **Issues** — a delay event created as an Issue can be tracked against the affected activity',
              'Link milestones to **Cost** change events — programme delays often have cost implications; the connection makes this traceable',
              'Compare **Daily Log** labour and productivity data to programme targets — was the planned productivity achieved?',
              'Use **Insights** to report programme performance alongside issue and cost data in a single project health dashboard',
              'Export programme data in P6 or Project format to share with specialist programme management teams',
            ],
          },
        ],
      },
    ],
    takeaways: [
      'ACC Schedule brings the construction programme into the same platform as models, documents, and site records — ending the isolation of the programme file.',
      'Import programmes from Primavera P6, MS Project, or CSV; set a baseline once imported so that progress can be tracked against it.',
      'Link programme activities to 3D model elements to create 4D simulations showing what is planned to be built and when.',
      'Progress tracking updates % Complete per activity; ACC calculates SPI and highlights delayed elements in the 4D view.',
      'The 4D simulation is a powerful client and stakeholder communication tool — export it as a video for presentations.',
      'Schedule integrates with Issues (delay events), Cost (programme-linked change orders), Daily Logs, and Insights for a complete project picture.',
    ],
    resource: { label: 'ACC Schedule & 4D BIM Guide', type: 'PDF' },
    quiz: { label: 'Schedule & 4D BIM Quiz', questions: 10, time: '5 min' },
    prev: { id: 'acc-15', title: 'Cost Management — Budgets, Contracts & Change Orders for BIM Practitioners' },
    next: { id: 'acc-17', title: 'Sheets — Publishing Drawings from Revit to ACC' },
  },

];
